INSERT OR IGNORE INTO RequirementSetRequirements VALUES
    ('BUILDING_IS_BARRACKS_STABLE_MILITARITIC_CITY_STATE', 'REQUIRES_CITY_HAS_BASILIKOI_PAIDES_BBG');
INSERT OR IGNORE INTO Requirements (RequirementId, RequirementType) VALUES
    ('REQUIRES_CITY_HAS_BASILIKOI_PAIDES_BBG', 'REQUIREMENT_CITY_HAS_BUILDING');
INSERT OR IGNORE INTO RequirementArguments (RequirementId, Name, Value) VALUES
    ('REQUIRES_CITY_HAS_BASILIKOI_PAIDES_BBG', 'BuildingType', 'BUILDING_BASILIKOI_PAIDES');

INSERT INTO Modifiers (ModifierId, ModifierType, OwnerRequirementSetId) VALUES
    ('BBG_MILITARY_COMMEMORATION_PROD_BASILIKOI', 'MODIFIER_PLAYER_CITIES_ADJUST_BUILDING_YIELD_CHANGE', 'PLAYER_HAS_GOLDEN_AGE');
INSERT INTO ModifierArguments (ModifierId, Name, Value) VALUES
    ('BBG_MILITARY_COMMEMORATION_PROD_BASILIKOI', 'BuildingType', 'BUILDING_BASILIKOI_PAIDES'),
    ('BBG_MILITARY_COMMEMORATION_PROD_BASILIKOI', 'YieldType', 'YIELD_PRODUCTION'),
    ('BBG_MILITARY_COMMEMORATION_PROD_BASILIKOI', 'Amount', 1);
INSERT INTO CommemorationModifiers (CommemorationType, ModifierId) VALUES
    ('COMMEMORATION_RELIGIOUS', 'BBG_MILITARY_COMMEMORATION_PROD_BASILIKOI');
INSERT INTO Modifiers (ModifierId, ModifierType, OwnerRequirementSetId) VALUES
    ('BBG_MILITARY_COMMEMORATION_CULTURE_BASILIKOI', 'MODIFIER_PLAYER_CITIES_ADJUST_BUILDING_YIELD_CHANGE', 'PLAYER_HAS_GOLDEN_AGE');
INSERT INTO ModifierArguments (ModifierId, Name, Value) VALUES
    ('BBG_MILITARY_COMMEMORATION_CULTURE_BASILIKOI', 'BuildingType', 'BUILDING_BASILIKOI_PAIDES'),
    ('BBG_MILITARY_COMMEMORATION_CULTURE_BASILIKOI', 'YieldType', 'YIELD_CULTURE'),
    ('BBG_MILITARY_COMMEMORATION_CULTURE_BASILIKOI', 'Amount', 1);
INSERT INTO CommemorationModifiers (CommemorationType, ModifierId) VALUES
    ('COMMEMORATION_RELIGIOUS', 'BBG_MILITARY_COMMEMORATION_CULTURE_BASILIKOI');
