INSERT INTO Requirements(RequirementId, RequirementType) VALUES
	('REQUIRES_OBJECT_0_TILES_FROM_CAPITAL', 'REQUIREMENT_PLOT_NEAR_CAPITAL');
INSERT INTO RequirementArguments(RequirementId, Name, Value) VALUES
	('REQUIRES_OBJECT_0_TILES_FROM_CAPITAL', 'MinDistance', '0'),
	('REQUIRES_OBJECT_0_TILES_FROM_CAPITAL', 'MaxDistance', '0');
INSERT INTO RequirementSets(RequirementSetId, RequirementSetType) VALUES
	('REQSET_PLOT_IS_CAPITAL_CITY_CENTER_BBCC', 'REQUIREMENTSET_TEST_ALL');
	--('REQSET_PLOT_IS_NO_CAPITAL_CITY_CENTER_BBCC', 'REQUIREMENTSET_TEST_ALL');
INSERT INTO RequirementSetRequirements(RequirementSetId, RequirementId) VALUES
	('REQSET_PLOT_IS_CAPITAL_CITY_CENTER_BBCC', 'REQUIRES_OBJECT_0_TILES_FROM_CAPITAL'),
	('REQSET_PLOT_IS_CAPITAL_CITY_CENTER_BBCC', 'REQ_PLOT_IS_CITY_CENTER_BBCC');
	--('REQSET_PLOT_IS_NO_CAPITAL_CITY_CENTER_BBCC', 'REQUIRES_OBJECT_0_TILES_FROM_CAPITAL'),
	--('REQSET_PLOT_IS_NO_CAPITAL_CITY_CENTER_BBCC', 'REQ_PLOT_IS_NO_CITY_CENTER_BBCC');
INSERT INTO Requirements(RequirementId, RequirementType, Inverse) VALUES
	('REQ_PLOT_IS_CAPITAL_CITY_CENTER_BBCC', 'REQUIREMENT_REQUIREMENTSET_IS_MET', 0),
	('REQ_PLOT_IS_NO_CAPITAL_CITY_CENTER_BBCC', 'REQUIREMENT_REQUIREMENTSET_IS_MET', 1);
INSERT INTO RequirementArguments(RequirementId, Name, Value) VALUES
	('REQ_PLOT_IS_CAPITAL_CITY_CENTER_BBCC', 'RequirementSetId', 'REQSET_PLOT_IS_CAPITAL_CITY_CENTER_BBCC'),
	('REQ_PLOT_IS_NO_CAPITAL_CITY_CENTER_BBCC', 'RequirementSetId', 'REQSET_PLOT_IS_CAPITAL_CITY_CENTER_BBCC');

UPDATE RequirementSetRequirements SET RequirementId = 'REQ_PLOT_IS_NO_CAPITAL_CITY_CENTER_BBCC' WHERE RequirementId='REQ_PLOT_IS_NO_CITY_CENTER_BBCC';
UPDATE RequirementSetRequirements SET RequirementId = 'REQ_PLOT_IS_CAPITAL_CITY_CENTER_BBCC' WHERE RequirementId='REQ_PLOT_IS_CITY_CENTER_BBCC' AND RequirementSetId<>'REQSET_PLOT_IS_CAPITAL_CITY_CENTER_BBCC';