INSERT INTO Requirements(RequirementId, RequirementType) VALUES
	('REQUIRES_PLOT_HAS_NO_HONEY_BCC', 'REQUIREMENT_PLOT_RESOURCE_TYPE_MATCHES');
INSERT INTO RequirementArguments(RequirementId, Name, Value) VALUES
	('REQUIRES_PLOT_HAS_NO_HONEY_BCC', 'ResourceType', 'RESOURCE_HONEY');
UPDATE Requirements SET Inverse=1 WHERE RequirementId='REQUIRES_PLOT_HAS_NO_HONEY_BCC';
INSERT INTO RequirementSetRequirements(RequirementSetId, RequirementId) VALUES
    ('BCC_PLOT_IS_GRASSLAND_CITY_REQUIREMENT', 'REQUIRES_PLOT_HAS_NO_HONEY_BCC'),
	('BCC_PLOT_IS_PLAINS_CITY_REQUIREMENT', 'REQUIRES_PLOT_HAS_NO_HONEY_BCC');