INSERT INTO Requirements(RequirementId, RequirementType) VALUES
	('REQUIRES_PLAYER_IS_NOT_LAURIER_BCC', 'REQUIREMENT_PLAYER_LEADER_TYPE_MATCHES');
INSERT INTO RequirementArguments(RequirementId, Name, Value) VALUES
    ('REQUIRES_PLAYER_IS_NOT_LAURIER_BCC', 'LeaderType', 'LEADER_LAURIER');	
UPDATE Requirements SET Inverse=1 WHERE RequirementId='REQUIRES_PLAYER_IS_NOT_LAURIER_BCC';
INSERT INTO Modifiers(ModifierId, ModifierType, SubjectRequirementSetId) VALUES
	('BCC_TUNDRA_HILLS_CITY_REMOVE_FOOD', 'MODIFIER_PLAYER_ADJUST_PLOT_YIELD', 'BCC_PLOT_IS_TUNDRA_HILLS_CITY_REQUIREMENT');
INSERT INTO ModifierArguments(ModifierId, Name, Value) VALUES
    ('BCC_TUNDRA_HILLS_CITY_REMOVE_FOOD', 'YieldType', 'YIELD_FOOD'),
    ('BCC_TUNDRA_HILLS_CITY_REMOVE_FOOD', 'Amount', '-1');
INSERT INTO TraitModifiers(TraitType, ModifierId) VALUES
    ('TRAIT_LEADER_LAST_BEST_WEST', 'BCC_TUNDRA_HILLS_CITY_REMOVE_FOOD');
INSERT INTO RequirementSetRequirements(RequirementSetId, RequirementId) VALUES
    ('BCC_PLOT_IS_TUNDRA_CITY_REQUIREMENT', 'REQUIRES_PLAYER_IS_NOT_LAURIER_BCC');