INSERT INTO Requirements(RequirementId, RequirementType, Inverse) VALUES
    ('REQUIRES_PLOT_HAS_NO_BAMBOO_BCC', 'REQUIREMENT_PLOT_RESOURCE_TYPE_MATCHES', '1'),
    ('REQUIRES_PLOT_HAS_NO_DATES_BCC', 'REQUIREMENT_PLOT_RESOURCE_TYPE_MATCHES', '1'),
    ('REQUIRES_PLOT_HAS_NO_FLOODPLAIN_DATES_BCC', 'REQUIREMENT_REQUIREMENTSET_IS_MET', '0');

INSERT INTO RequirementArguments(RequirementId, Name, Value) VALUES
    ('REQUIRES_PLOT_HAS_NO_BAMBOO_BCC', 'ResourceType', 'RESOURCE_BAMBOO'),
    ('REQUIRES_PLOT_HAS_NO_DATES_BCC', 'ResourceType', 'RESOURCE_DATES'),
    ('REQUIRES_PLOT_HAS_NO_FLOODPLAIN_DATES_BCC', 'RequirementSetId', 'BCC_NO_FLODPLAIN_DATES_REQUIREMENTSET');

INSERT INTO RequirementSets(RequirementSetId, RequirementSetType) VALUES
    ('BCC_NO_FLODPLAIN_DATES_REQUIREMENTSET', 'REQUIREMENTSET_TEST_ALL');

INSERT INTO RequirementSetRequirements(RequirementSetId, RequirementId) VALUES
    ('BCC_NO_FLODPLAIN_DATES_REQUIREMENTSET', 'REQUIRES_PLOT_HAS_NO_FLOODPLAINS_BCC'),
    ('BCC_NO_FLODPLAIN_DATES_REQUIREMENTSET', 'REQUIRES_PLOT_HAS_NO_DATES_BCC'),
    ('BCC_PLOT_IS_GRASSLAND_CITY_REQUIREMENT', 'REQUIRES_PLOT_HAS_NO_FLOODPLAIN_DATES_BCC'),
    ('BCC_PLOT_IS_GRASSLAND_CITY_REQUIREMENT', 'REQUIRES_PLOT_HAS_NO_BAMBOO_BCC'),
    ('BCC_PLOT_IS_DESERT_CITY_REQUIREMENT','REQUIRES_PLOT_HAS_NO_DATES_BCC'),
    ('BCC_PLOT_IS_GRASSLAND_HILLS_CITY_REQUIREMENT','REQUIRES_PLOT_HAS_NO_BAMBOO_BCC'),
    ('BCC_PLOT_IS_TUNDRA_HILLS_CITY_REQUIREMENT','REQUIRES_PLOT_HAS_NO_BAMBOO_BCC');
