-- ========================================================================
-- =                              AUSTRIA                                 =
-- ========================================================================

-- change Start Bias
DELETE FROM StartBiasTerrains WHERE CivilizationType = 'CIVILIZATION_MER_AUSTRIA';
DELETE FROM StartBiasRivers WHERE CivilizationType = 'CIVILIZATION_MER_AUSTRIA';

-- remove favor / governor
DELETE FROM TraitModifiers WHERE TraitType IN ('TRAIT_LEADER_MER_THERESIAN_REFORM') AND ModifierId IN ('MODIFIER_MER_CROWNLANDS_GOVERNOR_FAVOR_ATTACH');

-- remove free melee unit
DELETE FROM TraitModifiers WHERE TraitType IN ('TRAIT_CIVILIZATION_MER_CROWNLANDS') AND ModifierId IN ('MODIFIER_MER_THERESIAN_REFORM_FREE_MELEE_ATTACH');

-- adjust unit strength
UPDATE Units SET Combat = 60, RangedCombat = 70 WHERE UnitType = 'UNIT_MER_GRENZER';

-- -- Each City-State for which you are the Suzerain provides +15% Great Person points per turn.
-- INSERT INTO TraitModifiers (TraitType, ModifierId)
--     SELECT 'TRAIT_CIVILIZATION_MER_CROWNLANDS', 'BBG_AUSTRIA_GPP_PER_SUZ_' || LeaderType
--     FROM Leaders
--     WHERE InheritFrom IN
--         ('LEADER_MINOR_CIV_CULTURAL', 'LEADER_MINOR_CIV_INDUSTRIAL', 'LEADER_MINOR_CIV_MILITARISTIC',
--         'LEADER_MINOR_CIV_RELIGIOUS', 'LEADER_MINOR_CIV_SCIENTIFIC', 'LEADER_MINOR_CIV_TRADE');

-- INSERT INTO Modifiers (ModifierId, ModifierType, SubjectRequirementSetId)
--     SELECT 'BBG_AUSTRIA_GPP_PER_SUZ_' || LeaderType, 'MODIFIER_PLAYER_CITIES_ADJUST_GREAT_PERSON_POINT_BONUS', 'BBG_PLAYER_IS_SUZERAIN_OF_' || LeaderType || '_REQUIREMENTS'
--     FROM Leaders
--     WHERE InheritFrom IN
--         ('LEADER_MINOR_CIV_CULTURAL', 'LEADER_MINOR_CIV_INDUSTRIAL', 'LEADER_MINOR_CIV_MILITARISTIC',
--         'LEADER_MINOR_CIV_RELIGIOUS', 'LEADER_MINOR_CIV_SCIENTIFIC', 'LEADER_MINOR_CIV_TRADE');

-- INSERT INTO ModifierArguments (ModifierId, Name, Value)
--     SELECT 'BBG_AUSTRIA_GPP_PER_SUZ_' || LeaderType, 'Amount', '15'
--     FROM Leaders
--     WHERE InheritFrom IN
--         ('LEADER_MINOR_CIV_CULTURAL', 'LEADER_MINOR_CIV_INDUSTRIAL', 'LEADER_MINOR_CIV_MILITARISTIC',
--         'LEADER_MINOR_CIV_RELIGIOUS', 'LEADER_MINOR_CIV_SCIENTIFIC', 'LEADER_MINOR_CIV_TRADE');

-- remove green card ? 
DELETE FROM Modifiers WHERE ModifierId = 'MODIFIER_MER_CROWNLANDS_DIPLOMACY_SLOT';

-- implement the unique gpp that captures cs you re suz
INSERT INTO Types(Type, Kind) 
VALUES ('GREAT_PERSON_CLASS_AUSTRIAN_DIPLOMAT', 'KIND_GREAT_PERSON_CLASS'),
    ('GREAT_PERSON_INDIVIDUAL_AUSTRIA_1', 'KIND_GREAT_PERSON_INDIVIDUAL'),
    ('GREAT_PERSON_INDIVIDUAL_AUSTRIA_2', 'KIND_GREAT_PERSON_INDIVIDUAL'),
    ('GREAT_PERSON_INDIVIDUAL_AUSTRIA_3', 'KIND_GREAT_PERSON_INDIVIDUAL'),
    ('GREAT_PERSON_INDIVIDUAL_AUSTRIA_4', 'KIND_GREAT_PERSON_INDIVIDUAL'),
    ('GREAT_PERSON_INDIVIDUAL_AUSTRIA_5', 'KIND_GREAT_PERSON_INDIVIDUAL'),
    ('GREAT_PERSON_INDIVIDUAL_AUSTRIA_6', 'KIND_GREAT_PERSON_INDIVIDUAL'),
    ('GREAT_PERSON_INDIVIDUAL_AUSTRIA_7', 'KIND_GREAT_PERSON_INDIVIDUAL'),
    ('GREAT_PERSON_INDIVIDUAL_AUSTRIA_8', 'KIND_GREAT_PERSON_INDIVIDUAL'),
    ('GREAT_PERSON_INDIVIDUAL_AUSTRIA_9', 'KIND_GREAT_PERSON_INDIVIDUAL'),
    ('GREAT_PERSON_INDIVIDUAL_AUSTRIA_10', 'KIND_GREAT_PERSON_INDIVIDUAL'),
    ('GREAT_PERSON_INDIVIDUAL_AUSTRIA_11', 'KIND_GREAT_PERSON_INDIVIDUAL'),
    ('GREAT_PERSON_INDIVIDUAL_AUSTRIA_12', 'KIND_GREAT_PERSON_INDIVIDUAL'),
    ('UNIT_GREAT_DIPLOMAT', 'KIND_UNIT'),
    ('TRAIT_UNIT_GREAT_DIPLOMAT', 'KIND_TRAIT'),
    ('PSEUDOYIELD_GPP_DIPLOMAT', 'KIND_PSEUDOYIELD');

INSERT INTO PseudoYields (PseudoYieldType, DefaultValue) VALUES ('PSEUDOYIELD_GPP_DIPLOMAT', '100');

INSERT INTO CivilizationTraits (CivilizationType, TraitType) VALUES ('CIVILIZATION_MER_AUSTRIA', 'TRAIT_UNIT_GREAT_DIPLOMAT');

INSERT INTO Traits (TraitType, Name) VALUES ('TRAIT_UNIT_GREAT_DIPLOMAT', 'LOC_UNIT_GREAT_DIPLOMAT_NAME');

INSERT INTO Units (UnitType, Cost, BaseMoves, BaseSightRange, ZoneOfControl, Domain, FormationClass, Name, Description, CanCapture, CanRetreatWhenCaptured, CanTrain, TraitType) VALUES
('UNIT_GREAT_DIPLOMAT', 1, 4, 2, 0, 'DOMAIN_LAND', 'FORMATION_CLASS_CIVILIAN', 'LOC_UNIT_GREAT_DIPLOMAT_NAME', 'LOC_UNIT_GREAT_DIPLOMAT_DESCRIPTION', 0, 1, 0, 'TRAIT_UNIT_GREAT_DIPLOMAT');
INSERT INTO Units_XP2 (UnitType, CanEarnExperience, CanFormMilitaryFormation) VALUES ('UNIT_GREAT_DIPLOMAT', 0, 0);

-- diplomat ignore terrain cost
INSERT INTO Tags (Tag, Vocabulary) VALUES ('CLASS_DIPLOMAT', 'ABILITY_CLASS');

INSERT INTO TypeTags (Type, Tag)
VALUES ('UNIT_GREAT_DIPLOMAT', 'CLASS_LANDCIVILIAN'),
('UNIT_GREAT_DIPLOMAT', 'CLASS_DIPLOMAT'),
('TRAIT_UNIT_GREAT_DIPLOMAT', 'CLASS_ALL_ERAS'),
('ABILITY_IGNORE_TERRAIN_COST', 'CLASS_DIPLOMAT');


INSERT INTO GreatPersonClasses  (GreatPersonClassType, Name, UnitType, DistrictType, AvailableInTimeline, GenerateDuplicateIndividuals, IconString, ActionIcon, PseudoYieldType)    
VALUES ('GREAT_PERSON_CLASS_AUSTRIAN_DIPLOMAT', 'LOC_GREAT_PERSON_CLASS_AUSTRIAN_DIPLOMAT_NAME', 'UNIT_GREAT_DIPLOMAT', 'DISTRICT_CITY_CENTER', 1, 0, '[ICON_GreatMerchant]', 'ICON_UNITOPERATION_MERCHANT_ACTION', 'PSEUDOYIELD_GPP_DIPLOMAT');


INSERT INTO RequirementSets(RequirementSetId, RequirementSetType)
VALUES
('BBG_DIPLOMAT_PASSIVE_REQSET', 'REQUIREMENTSET_TEST_ALL');

INSERT INTO RequirementSetRequirements(RequirementSetId, RequirementId)
VALUES
('BBG_DIPLOMAT_PASSIVE_REQSET', 'BBG_PLOT_ADJACENT_PALACE');

INSERT INTO Requirements(RequirementId, RequirementType)
VALUES ('BBG_PLOT_ADJACENT_PALACE', 'REQUIREMENT_PLOT_ADJACENT_BUILDING_TYPE_MATCHES');

INSERT INTO RequirementArguments(RequirementId, Name, Value)
VALUES
('BBG_PLOT_ADJACENT_PALACE', 'BuildingType', 'BUILDING_PALACE');

-- Add requirement to check diplomat is NOT in its own territory (so it's in foreign territory)
INSERT INTO Requirements(RequirementId, RequirementType, Inverse)
VALUES ('BBG_DIPLOMAT_NOT_OWNER_TERRITORY', 'REQUIREMENT_UNIT_IN_OWNER_TERRITORY', 1);

-- Add both foreign territory requirements to the diplomat passive reqset
INSERT INTO RequirementSetRequirements(RequirementSetId, RequirementId)
VALUES
('BBG_DIPLOMAT_PASSIVE_REQSET', 'BBG_DIPLOMAT_NOT_OWNER_TERRITORY');

-- This expects a plot property `CS_ADJACENT_BBG` to be set (e.g. via Lua) on plots adjacent to a CS capital.
INSERT INTO Requirements(RequirementId, RequirementType, Inverse)
VALUES ('BBG_PLOT_NOT_ADJACENT_CS', 'REQUIREMENT_PLOT_PROPERTY_MATCHES', 1);
INSERT INTO RequirementArguments(RequirementId, Name, Value)
VALUES ('BBG_PLOT_NOT_ADJACENT_CS', 'PropertyName', 'CS_ADJACENT_BBG'),
       ('BBG_PLOT_NOT_ADJACENT_CS', 'PropertyMinimum', '1');

INSERT INTO RequirementSetRequirements(RequirementSetId, RequirementId)
VALUES ('BBG_DIPLOMAT_PASSIVE_REQSET', 'BBG_PLOT_NOT_ADJACENT_CS');

INSERT INTO Modifiers(ModifierId, ModifierType, SubjectRequirementSetId, OwnerStackLimit, SubjectStackLimit, Permanent, RunOnce)
VALUES
('BBG_DIPLOMAT_PASSIVE', 'MODIFIER_PLAYER_ADJUST_EXTRA_FAVOR_PER_TURN', 'BBG_DIPLOMAT_PASSIVE_REQSET', 1, 1, 0, 1);

INSERT INTO ModifierArguments(ModifierId, Name, Value)
VALUES
('BBG_DIPLOMAT_PASSIVE', 'Amount', '1');

INSERT INTO ModifierStrings(ModifierId, Context, Text)
VALUES
('BBG_DIPLOMAT_PASSIVE', 'Summary', 'LOC_BBG_DIPLOMAT_PASSIVE');


INSERT INTO GreatPersonIndividuals(GreatPersonIndividualType, Name, GreatPersonClassType, EraType, Gender, ActionCharges, ActionRequiresOwnedTile, ActionRequiresSuzerainTerritory, AreaHighlightRadius)
VALUES 
('GREAT_PERSON_INDIVIDUAL_AUSTRIA_1', 'LOC_GREAT_PERSON_INDIVIDUAL_AUSTRIA_1_NAME', 'GREAT_PERSON_CLASS_AUSTRIAN_DIPLOMAT', 'ERA_ATOMIC', 'M', 1, 0, 1,1),
('GREAT_PERSON_INDIVIDUAL_AUSTRIA_2', 'LOC_GREAT_PERSON_INDIVIDUAL_AUSTRIA_2_NAME', 'GREAT_PERSON_CLASS_AUSTRIAN_DIPLOMAT', 'ERA_ATOMIC', 'M', 1, 0, 1,1),
('GREAT_PERSON_INDIVIDUAL_AUSTRIA_3', 'LOC_GREAT_PERSON_INDIVIDUAL_AUSTRIA_3_NAME', 'GREAT_PERSON_CLASS_AUSTRIAN_DIPLOMAT', 'ERA_ATOMIC', 'M', 1, 0, 1,1),
('GREAT_PERSON_INDIVIDUAL_AUSTRIA_4', 'LOC_GREAT_PERSON_INDIVIDUAL_AUSTRIA_4_NAME', 'GREAT_PERSON_CLASS_AUSTRIAN_DIPLOMAT', 'ERA_ATOMIC', 'M', 1, 0, 1,1),
('GREAT_PERSON_INDIVIDUAL_AUSTRIA_5', 'LOC_GREAT_PERSON_INDIVIDUAL_AUSTRIA_5_NAME', 'GREAT_PERSON_CLASS_AUSTRIAN_DIPLOMAT', 'ERA_ATOMIC', 'M', 1, 0, 1,1),
('GREAT_PERSON_INDIVIDUAL_AUSTRIA_6', 'LOC_GREAT_PERSON_INDIVIDUAL_AUSTRIA_6_NAME', 'GREAT_PERSON_CLASS_AUSTRIAN_DIPLOMAT', 'ERA_ATOMIC', 'M', 1, 0, 1,1),
('GREAT_PERSON_INDIVIDUAL_AUSTRIA_7', 'LOC_GREAT_PERSON_INDIVIDUAL_AUSTRIA_7_NAME', 'GREAT_PERSON_CLASS_AUSTRIAN_DIPLOMAT', 'ERA_ATOMIC', 'M', 1, 0, 1,1),
('GREAT_PERSON_INDIVIDUAL_AUSTRIA_8', 'LOC_GREAT_PERSON_INDIVIDUAL_AUSTRIA_8_NAME', 'GREAT_PERSON_CLASS_AUSTRIAN_DIPLOMAT', 'ERA_ATOMIC', 'M', 1, 0, 1,1),
('GREAT_PERSON_INDIVIDUAL_AUSTRIA_9', 'LOC_GREAT_PERSON_INDIVIDUAL_AUSTRIA_9_NAME', 'GREAT_PERSON_CLASS_AUSTRIAN_DIPLOMAT', 'ERA_ATOMIC', 'M', 1, 0, 1,1),
('GREAT_PERSON_INDIVIDUAL_AUSTRIA_10', 'LOC_GREAT_PERSON_INDIVIDUAL_AUSTRIA_10_NAME', 'GREAT_PERSON_CLASS_AUSTRIAN_DIPLOMAT', 'ERA_ATOMIC', 'M', 1, 0, 1,1),
('GREAT_PERSON_INDIVIDUAL_AUSTRIA_11', 'LOC_GREAT_PERSON_INDIVIDUAL_AUSTRIA_11_NAME', 'GREAT_PERSON_CLASS_AUSTRIAN_DIPLOMAT', 'ERA_ATOMIC', 'M', 1, 0, 1,1),
('GREAT_PERSON_INDIVIDUAL_AUSTRIA_12', 'LOC_GREAT_PERSON_INDIVIDUAL_AUSTRIA_12_NAME', 'GREAT_PERSON_CLASS_AUSTRIAN_DIPLOMAT', 'ERA_ATOMIC', 'M', 1, 0, 1,1);


INSERT INTO GreatPersonIndividualBirthModifiers(GreatPersonIndividualType, ModifierId)
VALUES
('GREAT_PERSON_INDIVIDUAL_AUSTRIA_1', 'GREAT_PERSON_ENTER_FOREIGN_LANDS'),
('GREAT_PERSON_INDIVIDUAL_AUSTRIA_2', 'GREAT_PERSON_ENTER_FOREIGN_LANDS'),
('GREAT_PERSON_INDIVIDUAL_AUSTRIA_3', 'GREAT_PERSON_ENTER_FOREIGN_LANDS'),
('GREAT_PERSON_INDIVIDUAL_AUSTRIA_4', 'GREAT_PERSON_ENTER_FOREIGN_LANDS'),
('GREAT_PERSON_INDIVIDUAL_AUSTRIA_5', 'GREAT_PERSON_ENTER_FOREIGN_LANDS'),
('GREAT_PERSON_INDIVIDUAL_AUSTRIA_6', 'GREAT_PERSON_ENTER_FOREIGN_LANDS'),
('GREAT_PERSON_INDIVIDUAL_AUSTRIA_7', 'GREAT_PERSON_ENTER_FOREIGN_LANDS'),
('GREAT_PERSON_INDIVIDUAL_AUSTRIA_8', 'GREAT_PERSON_ENTER_FOREIGN_LANDS'),
('GREAT_PERSON_INDIVIDUAL_AUSTRIA_9', 'GREAT_PERSON_ENTER_FOREIGN_LANDS'),
('GREAT_PERSON_INDIVIDUAL_AUSTRIA_10', 'GREAT_PERSON_ENTER_FOREIGN_LANDS'),
('GREAT_PERSON_INDIVIDUAL_AUSTRIA_11', 'GREAT_PERSON_ENTER_FOREIGN_LANDS'),
('GREAT_PERSON_INDIVIDUAL_AUSTRIA_12', 'GREAT_PERSON_ENTER_FOREIGN_LANDS'),

('GREAT_PERSON_INDIVIDUAL_AUSTRIA_1', 'BBG_DIPLOMAT_PASSIVE'),
('GREAT_PERSON_INDIVIDUAL_AUSTRIA_2', 'BBG_DIPLOMAT_PASSIVE'),
('GREAT_PERSON_INDIVIDUAL_AUSTRIA_3', 'BBG_DIPLOMAT_PASSIVE'),
('GREAT_PERSON_INDIVIDUAL_AUSTRIA_4', 'BBG_DIPLOMAT_PASSIVE'),
('GREAT_PERSON_INDIVIDUAL_AUSTRIA_5', 'BBG_DIPLOMAT_PASSIVE'),
('GREAT_PERSON_INDIVIDUAL_AUSTRIA_6', 'BBG_DIPLOMAT_PASSIVE'),
('GREAT_PERSON_INDIVIDUAL_AUSTRIA_7', 'BBG_DIPLOMAT_PASSIVE'),
('GREAT_PERSON_INDIVIDUAL_AUSTRIA_8', 'BBG_DIPLOMAT_PASSIVE'),
('GREAT_PERSON_INDIVIDUAL_AUSTRIA_9', 'BBG_DIPLOMAT_PASSIVE'),
('GREAT_PERSON_INDIVIDUAL_AUSTRIA_10', 'BBG_DIPLOMAT_PASSIVE'),
('GREAT_PERSON_INDIVIDUAL_AUSTRIA_11', 'BBG_DIPLOMAT_PASSIVE'),
('GREAT_PERSON_INDIVIDUAL_AUSTRIA_12', 'BBG_DIPLOMAT_PASSIVE');

INSERT INTO GreatPersonIndividualActionModifiers(GreatPersonIndividualType, ModifierId, AttachmentTargetType)
VALUES
('GREAT_PERSON_INDIVIDUAL_AUSTRIA_1', 'GREATPERSON_CITY_STATE_ABSORB_EXPANSIONS', 'GREAT_PERSON_ACTION_ATTACHMENT_TARGET_UNIT_GREATPERSON'),
('GREAT_PERSON_INDIVIDUAL_AUSTRIA_2', 'GREATPERSON_CITY_STATE_ABSORB_EXPANSIONS', 'GREAT_PERSON_ACTION_ATTACHMENT_TARGET_UNIT_GREATPERSON'),
('GREAT_PERSON_INDIVIDUAL_AUSTRIA_3', 'GREATPERSON_CITY_STATE_ABSORB_EXPANSIONS', 'GREAT_PERSON_ACTION_ATTACHMENT_TARGET_UNIT_GREATPERSON'),
('GREAT_PERSON_INDIVIDUAL_AUSTRIA_4', 'GREATPERSON_CITY_STATE_ABSORB_EXPANSIONS', 'GREAT_PERSON_ACTION_ATTACHMENT_TARGET_UNIT_GREATPERSON'),
('GREAT_PERSON_INDIVIDUAL_AUSTRIA_5', 'GREATPERSON_CITY_STATE_ABSORB_EXPANSIONS', 'GREAT_PERSON_ACTION_ATTACHMENT_TARGET_UNIT_GREATPERSON'),
('GREAT_PERSON_INDIVIDUAL_AUSTRIA_6', 'GREATPERSON_CITY_STATE_ABSORB_EXPANSIONS', 'GREAT_PERSON_ACTION_ATTACHMENT_TARGET_UNIT_GREATPERSON'),
('GREAT_PERSON_INDIVIDUAL_AUSTRIA_7', 'GREATPERSON_CITY_STATE_ABSORB_EXPANSIONS', 'GREAT_PERSON_ACTION_ATTACHMENT_TARGET_UNIT_GREATPERSON'),
('GREAT_PERSON_INDIVIDUAL_AUSTRIA_8', 'GREATPERSON_CITY_STATE_ABSORB_EXPANSIONS', 'GREAT_PERSON_ACTION_ATTACHMENT_TARGET_UNIT_GREATPERSON'),
('GREAT_PERSON_INDIVIDUAL_AUSTRIA_9', 'GREATPERSON_CITY_STATE_ABSORB_EXPANSIONS', 'GREAT_PERSON_ACTION_ATTACHMENT_TARGET_UNIT_GREATPERSON'),
('GREAT_PERSON_INDIVIDUAL_AUSTRIA_10', 'GREATPERSON_CITY_STATE_ABSORB_EXPANSIONS', 'GREAT_PERSON_ACTION_ATTACHMENT_TARGET_UNIT_GREATPERSON'),
('GREAT_PERSON_INDIVIDUAL_AUSTRIA_11', 'GREATPERSON_CITY_STATE_ABSORB_EXPANSIONS', 'GREAT_PERSON_ACTION_ATTACHMENT_TARGET_UNIT_GREATPERSON'),
('GREAT_PERSON_INDIVIDUAL_AUSTRIA_12', 'GREATPERSON_CITY_STATE_ABSORB_EXPANSIONS', 'GREAT_PERSON_ACTION_ATTACHMENT_TARGET_UNIT_GREATPERSON');

INSERT INTO Modifiers(ModifierId, ModifierType, OwnerRequirementSetId, RunOnce, Permanent)
VALUES
('BBG_AUSTRIA_GRANT_DIPLOMAT_1', 'MODIFIER_SINGLE_CITY_GRANT_GREAT_PERSON_CLASS_IN_CITY','BBG_PLAYER_IS_LEADER_MER_MARIA_THERESA_REQSET', 1, 1),
('BBG_AUSTRIA_GRANT_DIPLOMAT_2', 'MODIFIER_SINGLE_CITY_GRANT_GREAT_PERSON_CLASS_IN_CITY','BBG_PLAYER_IS_LEADER_MER_MARIA_THERESA_REQSET', 1, 1),
('BBG_AUSTRIA_GRANT_DIPLOMAT_3', 'MODIFIER_SINGLE_CITY_GRANT_GREAT_PERSON_CLASS_IN_CITY','BBG_PLAYER_IS_LEADER_MER_MARIA_THERESA_REQSET', 1, 1);
        
INSERT INTO ModifierArguments(ModifierId, Name, Value)
VALUES
('BBG_AUSTRIA_GRANT_DIPLOMAT_1', 'GreatPersonClassType', 'GREAT_PERSON_CLASS_AUSTRIAN_DIPLOMAT'),
('BBG_AUSTRIA_GRANT_DIPLOMAT_2', 'GreatPersonClassType', 'GREAT_PERSON_CLASS_AUSTRIAN_DIPLOMAT'),
('BBG_AUSTRIA_GRANT_DIPLOMAT_3', 'GreatPersonClassType', 'GREAT_PERSON_CLASS_AUSTRIAN_DIPLOMAT');

INSERT INTO ModifierArguments(ModifierId, Name, Value)
VALUES
('BBG_AUSTRIA_GRANT_DIPLOMAT_1', 'Amount', '1'),
('BBG_AUSTRIA_GRANT_DIPLOMAT_2', 'Amount', '1'),
('BBG_AUSTRIA_GRANT_DIPLOMAT_3', 'Amount', '1');


-- INSERT INTO CivicModifiers(CivicType, ModifierId)
-- VALUES
-- ('CIVIC_POLITICAL_PHILOSOPHY', 'BBG_AUSTRIA_GRANT_DIPLOMAT_1'),
-- ('CIVIC_DIPLOMATIC_SERVICE', 'BBG_AUSTRIA_GRANT_DIPLOMAT_2'),
-- ('CIVIC_IDEOLOGY', 'BBG_AUSTRIA_GRANT_DIPLOMAT_3');

INSERT INTO BuildingModifiers(BuildingType, ModifierId)
VALUES
('BUILDING_GOV_TALL', 'BBG_AUSTRIA_GRANT_DIPLOMAT_1'),
('BUILDING_GOV_WIDE', 'BBG_AUSTRIA_GRANT_DIPLOMAT_1'),
('BUILDING_GOV_CONQUEST', 'BBG_AUSTRIA_GRANT_DIPLOMAT_1'),

('BUILDING_GOV_CITYSTATES', 'BBG_AUSTRIA_GRANT_DIPLOMAT_2'),
('BUILDING_GOV_SPIES', 'BBG_AUSTRIA_GRANT_DIPLOMAT_2'),
('BUILDING_GOV_FAITH', 'BBG_AUSTRIA_GRANT_DIPLOMAT_2'),

('BUILDING_GOV_MILITARY', 'BBG_AUSTRIA_GRANT_DIPLOMAT_3'),
('BUILDING_GOV_CULTURE', 'BBG_AUSTRIA_GRANT_DIPLOMAT_3'),
('BUILDING_GOV_SCIENCE', 'BBG_AUSTRIA_GRANT_DIPLOMAT_3');


-- 20% prod on gouv also boost civil units
-- remove prod toward districts as coded in the original mod as it is bugged

-- 10% flat and 5% per governor established

DELETE FROM Modifiers WHERE ModifierId IN ('MODTYPE_MER_CROWNLANDS_GOVERNOR_PRODUCTION', 'MODIFIER_MER_CROWNLANDS_GOVERNOR_PRODUCTION_ATTACH' );

INSERT INTO RequirementSets (RequirementSetId, RequirementSetType) VALUES
    ('BBG_PLAYER_IS_LEADER_MER_MARIA_THERESA_REQSET_AND_CITY_HAS_GOVERNOR', 'REQUIREMENTSET_TEST_ALL');
INSERT INTO RequirementSetRequirements (RequirementSetId, RequirementId) VALUES
    ('BBG_PLAYER_IS_LEADER_MER_MARIA_THERESA_REQSET_AND_CITY_HAS_GOVERNOR', 'BBG_PLAYER_IS_LEADER_MER_MARIA_THERESA_REQUIREMENT'),
    ('BBG_PLAYER_IS_LEADER_MER_MARIA_THERESA_REQSET_AND_CITY_HAS_GOVERNOR', 'REQUIRES_CITY_HAS_GOVERNOR');


INSERT INTO Modifiers (ModifierId, ModifierType, OwnerRequirementSetId) VALUES
    ('BBG_AUSTRIA_GOV_PROD_DISTRICT_FLAT', 'MODIFIER_SINGLE_CITY_ADJUST_DISTRICT_PRODUCTION_MODIFIER', 'BBG_PLAYER_IS_LEADER_MER_MARIA_THERESA_REQSET'),
    ('BBG_AUSTRIA_GOV_PROD_UNITS_FLAT', 'MODIFIER_SINGLE_CITY_ADJUST_UNIT_PRODUCTION_MODIFIER', 'BBG_PLAYER_IS_LEADER_MER_MARIA_THERESA_REQSET');

-- reduced prod to 15% per governor established
INSERT INTO ModifierArguments (ModifierId, Name, Value) VALUES
    ('BBG_AUSTRIA_GOV_PROD_DISTRICT_FLAT', 'Amount', '15'),
    ('BBG_AUSTRIA_GOV_PROD_UNITS_FLAT', 'Amount', '15');


INSERT INTO GovernorPromotionModifiers (GovernorPromotionType, ModifierId)
SELECT 
    gp.GovernorPromotionType,
    'BBG_AUSTRIA_GOV_PROD_' || u.prodType
FROM GovernorPromotions gp
CROSS JOIN (
    SELECT 'DISTRICT_FLAT' AS prodType
    UNION ALL SELECT 'UNITS_FLAT'
) u
WHERE gp.Level = 0;


-- add river and lake names
INSERT INTO Types(Type, Kind) VALUES
    ('NAMED_RIVER_AUSTRIA_1', 'KIND_NAMED_RIVER'),
    ('NAMED_RIVER_AUSTRIA_2', 'KIND_NAMED_RIVER'),
    ('NAMED_LAKE_AUSTRIA_1', 'KIND_NAMED_LAKE');

INSERT INTO NamedRivers(NamedRiverType, Name) VALUES
    ('NAMED_RIVER_AUSTRIA_1', 'LOC_NAMED_RIVER_AUSTRIA_1_NAME'),
    ('NAMED_RIVER_AUSTRIA_2', 'LOC_NAMED_RIVER_AUSTRIA_2_NAME');

INSERT INTO NamedLakes(NamedLakeType, Name) VALUES
    ('NAMED_LAKE_AUSTRIA_1', 'LOC_NAMED_LAKE_AUSTRIA_1_NAME');

INSERT INTO NamedRiverCivilizations(NamedRiverType, CivilizationType) VALUES
    ('NAMED_RIVER_AUSTRIA_1', 'CIVILIZATION_MER_AUSTRIA'),
    ('NAMED_RIVER_AUSTRIA_2', 'CIVILIZATION_MER_AUSTRIA'),
    ('NAMED_RIVER_RHINE', 'CIVILIZATION_MER_AUSTRIA');

INSERT INTO NamedLakeCivilizations(NamedLakeType, CivilizationType) VALUES
    ('NAMED_LAKE_AUSTRIA_1', 'CIVILIZATION_MER_AUSTRIA');

-- 04/07/26 BUILDING_MER_COFFEE_HOUSE : fix culture 
UPDATE Building_GreatWorks SET NonUniquePersonYield=4 WHERE BuildingType='BUILDING_MER_COFFEE_HOUSE';
UPDATE Building_GreatWorks SET NonUniquePersonTourism=4 WHERE BuildingType='BUILDING_MER_COFFEE_HOUSE';
