
UPDATE Units SET Bombard=35, Combat=25 WHERE UnitType='UNIT_ROMAN_ONAGER';

-- 02/01/26 Onager starts with free promotion 
INSERT INTO Types (Type, Kind) VALUES
    ('BBG_ONAGER_FREE_PROMOTION_ABILITY', 'KIND_ABILITY');
INSERT INTO TypeTags (Type, Tag) VALUES
    ('BBG_ONAGER_FREE_PROMOTION_ABILITY', 'CLASS_ROMAN_ONAGER');
INSERT INTO UnitAbilities (UnitAbilityType, Name, Description, Inactive) VALUES
    ('BBG_ONAGER_FREE_PROMOTION_ABILITY', 'LOC_BBG_ONAGER_FREE_PROMOTION_ABILITY_NAME', 'LOC_BBG_ONAGER_FREE_PROMOTION_ABILITY_DESC', 0);
INSERT INTO UnitAbilityModifiers (UnitAbilityType, ModifierId) VALUES
    ('BBG_ONAGER_FREE_PROMOTION_ABILITY', 'BBG_ONAGER_FREE_PROMOTION');
INSERT INTO Modifiers(ModifierId, ModifierType) VALUES
    ('BBG_ONAGER_FREE_PROMOTION', 'MODIFIER_PLAYER_UNIT_ADJUST_GRANT_EXPERIENCE');
INSERT INTO ModifierArguments(ModifierId, Name, Value) VALUES
    ('BBG_ONAGER_FREE_PROMOTION', 'Amount', -1);
