DELETE FROM Players WHERE CivilizationType='CIVILIZATION_MER_AUSTRIA';
DELETE FROM PlayerItems WHERE CivilizationType='CIVILIZATION_MER_AUSTRIA';

DELETE FROM Players WHERE CivilizationType='CIVILIZATION_CVS_TAINO';
DELETE FROM PlayerItems WHERE CivilizationType='CIVILIZATION_CVS_TAINO';

DELETE FROM Players WHERE CivilizationType='CIVILIZATION_MER_GOTHS';
DELETE FROM PlayerItems WHERE CivilizationType='CIVILIZATION_MER_GOTHS';

DELETE FROM Players WHERE LeaderType='LEADER_JFD_STANISLAW';
DELETE FROM PlayerItems WHERE LeaderType='LEADER_JFD_STANISLAW';
