DELETE FROM Civilizations WHERE CivilizationType='CIVILIZATION_MER_AUSTRIA';
DELETE FROM Civilizations WHERE CivilizationType='CIVILIZATION_CVS_TAINO';
DELETE FROM Civilizations WHERE CivilizationType='CIVILIZATION_MER_GOTHS';
DELETE FROM Leaders WHERE LeaderType='LEADER_JFD_STANISLAW';

DELETE FROM Buildings WHERE BuildingType='WON_CL_BUILDING_ARECIBO';
DELETE FROM Buildings WHERE BuildingType='BUILDING_PORCELAIN_TOWER';
DELETE FROM Ressources WHERE ResourceType='RESOURCE_PORCELAIN';