-- ========================================================================
-- =                       POLAND - STANISLAW                             =
-- ========================================================================

-- adjust unit to fit other unique cavalry in bbg (BaseMoves=5, Cost=310) 
UPDATE Units SET BaseMoves=5, Cost=330 WHERE UnitType = 'UNIT_JFD_UHLAN';
-- flanking bonus to 50% from 100%
UPDATE ModifierArguments SET Value=50 WHERE ModifierId='JFD_UHLAN_FLANKING_BONUS' AND Name='Percent';

-- remove leader effect 
DELETE FROM TraitModifiers WHERE TraitType='TRAIT_LEADER_JFD_NATIONAL_EDUCATION';

--22/07/26 need improved or STRATEGIC ressources
INSERT INTO RequirementSets (RequirementSetId, RequirementSetType) VALUES
('BBG_ADJACENT_TO_BARRACKS_OR_STABLE_REQUIREMENTS', 'REQUIREMENTSET_TEST_ANY'),
('BBG_IMPROVED_OR_RESSOURCE_REQUIREMENTS',  'REQUIREMENTSET_TEST_ANY'),

('BBG_ADJACENT_TO_ENCAMPMENT_IMROVED_OR_RESSOURCE_REQUIREMENTS', 'REQUIREMENTSET_TEST_ALL'),
('BBG_ADJACENT_TO_BARRACKS_OR_STABLE_IMROVED_OR_RESSOURCE_REQUIREMENTS', 'REQUIREMENTSET_TEST_ALL'),
('BBG_ADJACENT_TO_ARMORY_IMROVED_OR_RESSOURCE_REQUIREMENTS', 'REQUIREMENTSET_TEST_ALL'),
('BBG_ADJACENT_TO_MILITARY_ACADEMY_IMROVED_OR_RESSOURCE_REQUIREMENTS', 'REQUIREMENTSET_TEST_ALL'),

('BBG_PLOT_HAS_STRATEGIC_RESOURCE_REVEALED', 'REQUIREMENTSET_TEST_ALL');

INSERT INTO Requirements (RequirementId, RequirementType) VALUES
('BBG_PLOT_IS_ADJACENT_BARRACKS', 'REQUIREMENT_PLOT_ADJACENT_BUILDING_TYPE_MATCHES'),
('BBG_PLOT_IS_ADJACENT_STABLE', 'REQUIREMENT_PLOT_ADJACENT_BUILDING_TYPE_MATCHES'),
('BBG_PLOT_IS_ADJACENT_ARMORY', 'REQUIREMENT_PLOT_ADJACENT_BUILDING_TYPE_MATCHES'),
('BBG_PLOT_IS_ADJACENT_MILITARY_ACADEMY', 'REQUIREMENT_PLOT_ADJACENT_BUILDING_TYPE_MATCHES'),
('BBG_PLOT_HAS_STRATEGIC_RESOURCE_REVEALED_MET', 'REQUIREMENT_REQUIREMENTSET_IS_MET'),

('BBG_ADJACENT_TO_BARRACKS_OR_STABLE_REQUIREMENTS_MET', 'REQUIREMENT_REQUIREMENTSET_IS_MET'),
('BBG_IMPROVED_OR_RESSOURCE_REQUIREMENTS_MET', 'REQUIREMENT_REQUIREMENTSET_IS_MET');

INSERT INTO RequirementArguments (RequirementId, Name, Value) VALUES
('BBG_PLOT_IS_ADJACENT_BARRACKS', 'BuildingType', 'BUILDING_BARRACKS'),
('BBG_PLOT_IS_ADJACENT_STABLE', 'BuildingType', 'BUILDING_STABLE'),
('BBG_PLOT_IS_ADJACENT_ARMORY', 'BuildingType', 'BUILDING_ARMORY'),
('BBG_PLOT_IS_ADJACENT_MILITARY_ACADEMY', 'BuildingType', 'BUILDING_MILITARY_ACADEMY'),
('BBG_PLOT_HAS_STRATEGIC_RESOURCE_REVEALED_MET', 'RequirementSetId', 'BBG_PLOT_HAS_STRATEGIC_RESOURCE_REVEALED'),

('BBG_IMPROVED_OR_RESSOURCE_REQUIREMENTS_MET', 'RequirementSetId', 'BBG_IMPROVED_OR_RESSOURCE_REQUIREMENTS'),
('BBG_ADJACENT_TO_BARRACKS_OR_STABLE_REQUIREMENTS_MET', 'RequirementSetId', 'BBG_ADJACENT_TO_BARRACKS_OR_STABLE_REQUIREMENTS');

INSERT INTO RequirementSetRequirements (RequirementSetId, RequirementId) VALUES
('BBG_IMPROVED_OR_RESSOURCE_REQUIREMENTS', 'BBG_PLOT_HAS_STRATEGIC_RESOURCE_REVEALED_MET'), 
('BBG_IMPROVED_OR_RESSOURCE_REQUIREMENTS', 'BBG_TILE_HAS_ANY_IMPROVEMENT'),

('BBG_ADJACENT_TO_BARRACKS_OR_STABLE_REQUIREMENTS', 'BBG_PLOT_IS_ADJACENT_BARRACKS'),
('BBG_ADJACENT_TO_BARRACKS_OR_STABLE_REQUIREMENTS', 'BBG_PLOT_IS_ADJACENT_STABLE'),

('BBG_ADJACENT_TO_ENCAMPMENT_IMROVED_OR_RESSOURCE_REQUIREMENTS', 'BBG_PLOT_IS_ADJACENT_ENCAMPMENT'),
('BBG_ADJACENT_TO_ENCAMPMENT_IMROVED_OR_RESSOURCE_REQUIREMENTS', 'BBG_IMPROVED_OR_RESSOURCE_REQUIREMENTS_MET'),

('BBG_ADJACENT_TO_BARRACKS_OR_STABLE_IMROVED_OR_RESSOURCE_REQUIREMENTS', 'BBG_ADJACENT_TO_BARRACKS_OR_STABLE_REQUIREMENTS_MET'),
('BBG_ADJACENT_TO_BARRACKS_OR_STABLE_IMROVED_OR_RESSOURCE_REQUIREMENTS', 'BBG_IMPROVED_OR_RESSOURCE_REQUIREMENTS_MET'),

('BBG_ADJACENT_TO_ARMORY_IMROVED_OR_RESSOURCE_REQUIREMENTS', 'BBG_PLOT_IS_ADJACENT_ARMORY'),
('BBG_ADJACENT_TO_ARMORY_IMROVED_OR_RESSOURCE_REQUIREMENTS', 'BBG_IMPROVED_OR_RESSOURCE_REQUIREMENTS_MET'),

('BBG_ADJACENT_TO_MILITARY_ACADEMY_IMROVED_OR_RESSOURCE_REQUIREMENTS', 'BBG_PLOT_IS_ADJACENT_MILITARY_ACADEMY'),
('BBG_ADJACENT_TO_MILITARY_ACADEMY_IMROVED_OR_RESSOURCE_REQUIREMENTS', 'BBG_IMPROVED_OR_RESSOURCE_REQUIREMENTS_MET'),

('BBG_PLOT_HAS_STRATEGIC_RESOURCE_REVEALED', 'REQUIRES_PLOT_HAS_STRATEGIC'),
('BBG_PLOT_HAS_STRATEGIC_RESOURCE_REVEALED', 'REQUIRES_PLOT_HAS_VISIBLE_RESOURCE');



INSERT INTO Modifiers (ModifierId, ModifierType, SubjectRequirementSetId) VALUES
('BBG_ENCAMPMENT_ADJACENT_FOOD', 'MODIFIER_PLAYER_ADJUST_PLOT_YIELD', 'BBG_ADJACENT_TO_ENCAMPMENT_IMROVED_OR_RESSOURCE_REQUIREMENTS'),
('BBG_ENCAMPMENT_ADJACENT_CULTURE_BARRACKS', 'MODIFIER_PLAYER_ADJUST_PLOT_YIELD', 'BBG_ADJACENT_TO_BARRACKS_OR_STABLE_IMROVED_OR_RESSOURCE_REQUIREMENTS'),
('BBG_ENCAMPMENT_ADJACENT_SCIENCE_ARMORY', 'MODIFIER_PLAYER_ADJUST_PLOT_YIELD', 'BBG_ADJACENT_TO_ARMORY_IMROVED_OR_RESSOURCE_REQUIREMENTS'),
('BBG_ENCAMPMENT_ADJACENT_PRODUCTION_MILITARY_ACADEMY', 'MODIFIER_PLAYER_ADJUST_PLOT_YIELD', 'BBG_ADJACENT_TO_MILITARY_ACADEMY_IMROVED_OR_RESSOURCE_REQUIREMENTS');

INSERT INTO ModifierArguments (ModifierId, Name, Value) VALUES
('BBG_ENCAMPMENT_ADJACENT_FOOD', 'YieldType', 'YIELD_FOOD'),
('BBG_ENCAMPMENT_ADJACENT_FOOD', 'Amount', '1'),
('BBG_ENCAMPMENT_ADJACENT_CULTURE_BARRACKS', 'YieldType', 'YIELD_CULTURE'),
('BBG_ENCAMPMENT_ADJACENT_CULTURE_BARRACKS', 'Amount', '1'),
('BBG_ENCAMPMENT_ADJACENT_SCIENCE_ARMORY', 'YieldType', 'YIELD_SCIENCE'),
('BBG_ENCAMPMENT_ADJACENT_SCIENCE_ARMORY', 'Amount', '1'),
('BBG_ENCAMPMENT_ADJACENT_PRODUCTION_MILITARY_ACADEMY', 'YieldType', 'YIELD_PRODUCTION'),
('BBG_ENCAMPMENT_ADJACENT_PRODUCTION_MILITARY_ACADEMY', 'Amount', '1');

INSERT INTO TraitModifiers (TraitType, ModifierId) VALUES
('TRAIT_LEADER_JFD_NATIONAL_EDUCATION', 'BBG_ENCAMPMENT_ADJACENT_FOOD'),
('TRAIT_LEADER_JFD_NATIONAL_EDUCATION', 'BBG_ENCAMPMENT_ADJACENT_CULTURE_BARRACKS'),
('TRAIT_LEADER_JFD_NATIONAL_EDUCATION', 'BBG_ENCAMPMENT_ADJACENT_SCIENCE_ARMORY'),
('TRAIT_LEADER_JFD_NATIONAL_EDUCATION', 'BBG_ENCAMPMENT_ADJACENT_PRODUCTION_MILITARY_ACADEMY');

-- Start with Bronze Working Boost
-- INSERT INTO Modifiers (ModifierId, ModifierType) VALUES
--     ('BBG_FREE_BRONZE_WORKING_BOOST', 'MODIFIER_PLAYER_GRANT_SPECIFIC_TECH_BOOST');					
-- INSERT INTO ModifierArguments (ModifierId, Name, Value) VALUES
--     ('BBG_FREE_BRONZE_WORKING_BOOST', 'TechType', 'TECH_BRONZE_WORKING');
-- INSERT INTO TraitModifiers (TraitType, ModifierId) VALUES
--     ('TRAIT_LEADER_JFD_NATIONAL_EDUCATION', 'BBG_FREE_BRONZE_WORKING_BOOST');