-- ========================================================================
-- =                              TAINO                                  =
-- ========================================================================

-- change startBias
DELETE FROM StartBiasTerrains WHERE CivilizationType = 'CIVILIZATION_CVS_TAINO';
DELETE FROM StartBiasResources WHERE CivilizationType = 'CIVILIZATION_CVS_TAINO';
DELETE FROM StartBiasFeatures WHERE CivilizationType = 'CIVILIZATION_CVS_TAINO';

-- delete base effect
DELETE FROM Modifiers WHERE ModifierId='MODIFIER_CVS_ANACAONA_UA_FAITH_GPP';
DELETE FROM Modifiers WHERE ModifierId='MODIFIER_CVS_ANACAONA_UA_FAITH_ENVOY';
DELETE FROM Modifiers WHERE ModifierId='MODIFIER_CVS_TAINO_UI_ADJUST_AMENITY_ARENA';
DELETE FROM Modifiers WHERE ModifierId='MODIFIER_CVS_TAINO_UI_ADJUST_AMENITY_ZOO';
DELETE FROM Modifiers WHERE ModifierId='MODIFIER_CVS_TAINO_UI_ADJUST_AMENITY_STADIUM';


-- change dedication / policy card correspondance
INSERT INTO	Modifiers
		(ModifierId,													ModifierType,														SubjectRequirementSetId			)
VALUES  ('BBG_MODIFIER_WILDCARD_POLICY_SLOT_ON_DEDICATION',			'MODIFIER_PLAYER_CULTURE_ADJUST_GOVERNMENT_SLOTS_MODIFIER',			'REQSET_CVS_LEADER_IS_TAINO_AND_UNLOCKED_POLITICAL_PHILOSOPHY'	),
		('BBG_MODIFIER_ECONOMIC_POLICY_SLOT_ON_DEDICATION',			'MODIFIER_PLAYER_CULTURE_ADJUST_GOVERNMENT_SLOTS_MODIFIER',			'REQSET_CVS_LEADER_IS_TAINO_AND_UNLOCKED_POLITICAL_PHILOSOPHY'	),
		('BBG_MODIFIER_DIPLOMATIC_POLICY_SLOT_ON_DEDICATION',		'MODIFIER_PLAYER_CULTURE_ADJUST_GOVERNMENT_SLOTS_MODIFIER',			'REQSET_CVS_LEADER_IS_TAINO_AND_UNLOCKED_POLITICAL_PHILOSOPHY'	),
		('BBG_MODIFIER_MILITARY_POLICY_SLOT_ON_DEDICATION',			'MODIFIER_PLAYER_CULTURE_ADJUST_GOVERNMENT_SLOTS_MODIFIER',			'REQSET_CVS_LEADER_IS_TAINO_AND_UNLOCKED_POLITICAL_PHILOSOPHY'	);


INSERT INTO ModifierArguments
		(ModifierId,															Name,					Value													)
VALUES  ('BBG_MODIFIER_WILDCARD_POLICY_SLOT_ON_DEDICATION',					'GovernmentSlotType',	'SLOT_WILDCARD'					),
		('BBG_MODIFIER_WILDCARD_POLICY_SLOT_ON_DEDICATION',					'Amount',				1								),
		('BBG_MODIFIER_ECONOMIC_POLICY_SLOT_ON_DEDICATION',					'GovernmentSlotType',	'SLOT_ECONOMIC'					),
		('BBG_MODIFIER_ECONOMIC_POLICY_SLOT_ON_DEDICATION',					'Amount',				1								),
		('BBG_MODIFIER_DIPLOMATIC_POLICY_SLOT_ON_DEDICATION',				'GovernmentSlotType',	'SLOT_DIPLOMATIC'					),
		('BBG_MODIFIER_DIPLOMATIC_POLICY_SLOT_ON_DEDICATION',				'Amount',				1								),
		('BBG_MODIFIER_MILITARY_POLICY_SLOT_ON_DEDICATION',					'GovernmentSlotType',	'SLOT_MILITARY'					),
		('BBG_MODIFIER_MILITARY_POLICY_SLOT_ON_DEDICATION',					'Amount',				1								);

INSERT INTO	CommemorationModifiers	
		(CommemorationType,									ModifierId									)
VALUES	------Classical------------------------------------------
		('COMMEMORATION_SCIENTIFIC',				'BBG_MODIFIER_ECONOMIC_POLICY_SLOT_ON_DEDICATION'	), --FI
		('COMMEMORATION_CULTURAL',					'BBG_MODIFIER_DIPLOMATIC_POLICY_SLOT_ON_DEDICATION'	), -- P&B
		('COMMEMORATION_INFRASTRUCTURE',			'BBG_MODIFIER_WILDCARD_POLICY_SLOT_ON_DEDICATION'	), --  Monu
		('COMMEMORATION_RELIGIOUS',					'BBG_MODIFIER_MILITARY_POLICY_SLOT_ON_DEDICATION'	), -- Drums

		------Renaissance-----------------------------------------
		('COMMEMORATION_ECONOMIC',					'BBG_MODIFIER_ECONOMIC_POLICY_SLOT_ON_DEDICATION'	), --  reform
		('COMMEMORATION_EXPLORATION',				'BBG_MODIFIER_DIPLOMATIC_POLICY_SLOT_ON_DEDICATION'	), -- hin sunc
		('COMMEMORATION_INDUSTRIAL',				'BBG_MODIFIER_WILDCARD_POLICY_SLOT_ON_DEDICATION'	), -- heart of the steam
        ('COMMEMORATION_MILITARY',					'BBG_MODIFIER_MILITARY_POLICY_SLOT_ON_DEDICATION'	), -- to arms

		------Industrial-----------------------------------------
		('COMMEMORATION_TOURISM',					'BBG_MODIFIER_WILDCARD_POLICY_SLOT_ON_DEDICATION'	), -- joker  
		('COMMEMORATION_AERONAUTICAL',				'BBG_MODIFIER_ECONOMIC_POLICY_SLOT_ON_DEDICATION'	),
		('COMMEMORATION_ESPIONAGE',					'BBG_MODIFIER_DIPLOMATIC_POLICY_SLOT_ON_DEDICATION'	),
		('COMMEMORATION_AUTOMATON',					'BBG_MODIFIER_MILITARY_POLICY_SLOT_ON_DEDICATION'	);

-- from Lili of Lime
												
-- Diplo Policy Stuff

INSERT INTO PolicyModifiers
		(PolicyType,								ModifierId)
SELECT	PolicyType,									'LIME_LILI_'||PolicyType||'_AMENITIES'
FROM Policies 
	WHERE GovernmentSlotType = 'SLOT_DIPLOMATIC';

INSERT INTO Modifiers
		(ModifierId,								ModifierType,										SubjectRequirementSetId)
SELECT 'LIME_LILI_'||PolicyType||'_AMENITIES',		'MODIFIER_PLAYER_CITIES_ADJUST_POLICY_AMENITY',		'REQSET_CVS_LEADER_IS_TAINO_AND_CITY_HAS_DISTRICT'
FROM Policies
	WHERE GovernmentSlotType = 'SLOT_DIPLOMATIC';

INSERT INTO ModifierArguments
		(ModifierId,								Name,			Value)
SELECT 'LIME_LILI_'||PolicyType||'_AMENITIES',	'Amount',		1
FROM Policies
	WHERE GovernmentSlotType = 'SLOT_DIPLOMATIC';

INSERT INTO RequirementSets
		(RequirementSetId,										RequirementSetType)
VALUES	('REQSET_CVS_LEADER_IS_TAINO_AND_CITY_HAS_DISTRICT',	'REQUIREMENTSET_TEST_ALL'),
		('REQSET_CVS_LEADER_IS_TAINO_AND_UNLOCKED_POLITICAL_PHILOSOPHY','REQUIREMENTSET_TEST_ALL'),
		('REQSET_LIME_LILI_CITY_HAS_THEATRE',					'REQUIREMENTSET_TEST_ALL'),	
		('REQSET_LIME_LILI_CITY_HAS_CAMPUS',					'REQUIREMENTSET_TEST_ALL'),	
		('REQSET_LIME_LILI_CITY_HAS_INDUSTRIAL',				'REQUIREMENTSET_TEST_ALL'),
		('REQSET_LIME_LILI_CITY_HAS_HARBOUR',					'REQUIREMENTSET_TEST_ALL');

INSERT INTO RequirementSetRequirements
		(RequirementSetId,										RequirementId)
VALUES	('REQSET_CVS_LEADER_IS_TAINO_AND_CITY_HAS_DISTRICT',	'REQ_CVS_LEADER_IS_ANACAONA'),
		('REQSET_CVS_LEADER_IS_TAINO_AND_CITY_HAS_DISTRICT',	'REQUIRES_CITY_HAS_DISTRICT_CVS_TAINO_UI'),
		('REQSET_CVS_LEADER_IS_TAINO_AND_UNLOCKED_POLITICAL_PHILOSOPHY','BBG_UTILS_PLAYER_HAS_CIVIC_POLITICAL_PHILOSOPHY_REQUIREMENT'),
		('REQSET_CVS_LEADER_IS_TAINO_AND_UNLOCKED_POLITICAL_PHILOSOPHY','REQ_CVS_LEADER_IS_ANACAONA'),
		('REQSET_LIME_LILI_CITY_HAS_THEATRE',					'REQUIRES_CITY_HAS_THEATER_DISTRICT'),	
		('REQSET_LIME_LILI_CITY_HAS_CAMPUS',					'REQUIRES_CITY_HAS_CAMPUS'),	
		('REQSET_LIME_LILI_CITY_HAS_INDUSTRIAL',				'REQUIRES_CITY_HAS_INDUSTRIAL_ZONE'),
		('REQSET_LIME_LILI_CITY_HAS_HARBOUR',					'REQUIRES_CITY_HAS_HARBOR');

INSERT INTO Requirements
		(RequirementId,											RequirementType)
VALUES 	('REQUIRES_CITY_HAS_DISTRICT_CVS_TAINO_UI',				'REQUIREMENT_CITY_HAS_DISTRICT');

INSERT INTO RequirementArguments
		(RequirementId,											Name,			Value)
VALUES	('REQUIRES_CITY_HAS_DISTRICT_CVS_TAINO_UI',				'DistrictType',	'DISTRICT_CVS_TAINO_UI');

-- food from card 
    
CREATE TABLE IF NOT EXISTS TempPolicyDistricts(
	PolicyType TEXT NOT NULL,
	DistrictType TEXT NOT NULL,
	PRIMARY KEY(PolicyType, DistrictType)
);
INSERT INTO TempPolicyDistricts(PolicyType, DistrictType) VALUES
	('POLICY_FRESCOES', 'DISTRICT_THEATER'),
	('POLICY_INSPIRATION', 'DISTRICT_CAMPUS'),
	('POLICY_INVENTION', 'DISTRICT_INDUSTRIAL_ZONE'),
	('POLICY_LAISSEZ_FAIRE', 'DISTRICT_COMMERCIAL_HUB'),
	('POLICY_LAISSEZ_FAIRE', 'DISTRICT_HARBOR'),
	('POLICY_LITERARY_TRADITION', 'DISTRICT_THEATER'),
	('POLICY_MILITARY_ORGANIZATION', 'DISTRICT_ENCAMPMENT'),
	('POLICY_NAVIGATION', 'DISTRICT_HARBOR'),
	('POLICY_NOBEL_PRIZE', 'DISTRICT_CAMPUS'),
	('POLICY_NOBEL_PRIZE', 'DISTRICT_INDUSTRIAL_ZONE'),
	('POLICY_REVELATION', 'DISTRICT_HOLY_SITE'),
	('POLICY_STRATEGOS', 'DISTRICT_ENCAMPMENT'),
	('POLICY_SYMPHONIES', 'DISTRICT_THEATER'),
	('POLICY_TRAVELING_MERCHANTS', 'DISTRICT_COMMERCIAL_HUB');

--buildings +1 food
INSERT INTO PolicyModifiers(PolicyType, ModifierId)
SELECT PolicyType, 'BBG_' || PolicyType || '_FOOD_' || BuildingType 
FROM TempPolicyDistricts JOIN Buildings ON TempPolicyDistricts.DistrictType = Buildings.PrereqDistrict;

INSERT INTO Modifiers(ModifierId, ModifierType, OwnerRequirementSetId)
SELECT 'BBG_' || PolicyType || '_FOOD_' || BuildingType , 'MODIFIER_PLAYER_CITIES_ADJUST_BUILDING_YIELD_CHANGE', 'REQSET_CVS_LEADER_IS_TAINO'
FROM TempPolicyDistricts JOIN Buildings ON TempPolicyDistricts.DistrictType = Buildings.PrereqDistrict;

INSERT INTO ModifierArguments(ModifierId, Name, Value)
SELECT 'BBG_' || PolicyType || '_FOOD_' || BuildingType , 'YieldType', 'YIELD_FOOD'
FROM TempPolicyDistricts JOIN Buildings ON TempPolicyDistricts.DistrictType = Buildings.PrereqDistrict;
INSERT INTO ModifierArguments(ModifierId, Name, Value)
SELECT 'BBG_' || PolicyType || '_FOOD_' || BuildingType , 'Amount', '1'
FROM TempPolicyDistricts JOIN Buildings ON TempPolicyDistricts.DistrictType = Buildings.PrereqDistrict;
INSERT INTO ModifierArguments(ModifierId, Name, Value)
SELECT 'BBG_' || PolicyType || '_FOOD_' || BuildingType , 'BuildingType', BuildingType
FROM TempPolicyDistricts JOIN Buildings ON TempPolicyDistricts.DistrictType = Buildings.PrereqDistrict;

-- districts +2 food
INSERT INTO PolicyModifiers(PolicyType, ModifierId)
SELECT PolicyType, 'BBG_' || PolicyType || '_FOOD_' || DistrictType 
FROM TempPolicyDistricts;

INSERT INTO Modifiers(ModifierId, ModifierType,  SubjectRequirementSetId, OwnerRequirementSetId)
SELECT 'BBG_' || PolicyType || '_FOOD_' || DistrictType , 'MODIFIER_PLAYER_DISTRICTS_ADJUST_YIELD_CHANGE' ,'BBG_DISTRICT_IS_'|| DistrictType || '_REQSET', 'REQSET_CVS_LEADER_IS_TAINO'
FROM TempPolicyDistricts;
INSERT INTO ModifierArguments(ModifierId, Name, Value)
SELECT 'BBG_' || PolicyType || '_FOOD_' || DistrictType , 'YieldType', 'YIELD_FOOD'
FROM TempPolicyDistricts;
INSERT INTO ModifierArguments(ModifierId, Name, Value)
SELECT 'BBG_' || PolicyType || '_FOOD_' || DistrictType , 'Amount', '2'
FROM TempPolicyDistricts;

DROP TABLE TempPolicyDistricts;
--



-- +5 % gold  +3 amenities / 5 / 8
INSERT INTO Modifiers
		(ModifierId,											ModifierType												)
VALUES 	('BBG_TAINO_GOLD_HAPPY',					'MODIFIER_PLAYER_CITIES_ADJUST_HAPPINESS_YIELD'),
		('BBG_TAINO_GOLD_ECSTATIC',				'MODIFIER_PLAYER_CITIES_ADJUST_HAPPINESS_YIELD'),
		('BBG_TAINO_GOLD_EUPHORIC',				'MODIFIER_PLAYER_CITIES_ADJUST_HAPPINESS_YIELD');

INSERT INTO ModifierArguments(ModifierId, Name, Value) VALUES
('BBG_TAINO_GOLD_HAPPY', 'YieldType', 'YIELD_GOLD'),
('BBG_TAINO_GOLD_HAPPY', 'HappinessType', 'HAPPINESS_HAPPY'),
('BBG_TAINO_GOLD_HAPPY', 'Amount', 5),
('BBG_TAINO_GOLD_ECSTATIC', 'YieldType', 'YIELD_GOLD'),
('BBG_TAINO_GOLD_ECSTATIC', 'HappinessType', 'HAPPINESS_ECSTATIC'),
('BBG_TAINO_GOLD_ECSTATIC', 'Amount', 10),
('BBG_TAINO_GOLD_EUPHORIC', 'YieldType', 'YIELD_GOLD'),
('BBG_TAINO_GOLD_EUPHORIC', 'HappinessType', 'HAPPINESS_UNHAPPY'),
('BBG_TAINO_GOLD_EUPHORIC', 'Amount', 15);

INSERT INTO TraitModifiers (TraitType, ModifierId) VALUES
	('TRAIT_LEADER_CVS_ANACAONA_UA', 'BBG_TAINO_GOLD_HAPPY'),
	('TRAIT_LEADER_CVS_ANACAONA_UA', 'BBG_TAINO_GOLD_ECSTATIC'),
	('TRAIT_LEADER_CVS_ANACAONA_UA', 'BBG_TAINO_GOLD_EUPHORIC');


-- UD adjacency : +2 prod and 3 gold per commercial hub / harbor / City Center
INSERT INTO District_Adjacencies
		(DistrictType,				YieldChangeId)
VALUES ('DISTRICT_CVS_TAINO_UI',	'BBG_PRODUCTION_TAINO_COMMERCIAL_HUB'),
		('DISTRICT_CVS_TAINO_UI',	'BBG_PRODUCTION_TAINO_HARBOR'),
		('DISTRICT_CVS_TAINO_UI',	'BBG_GOLD_TAINO_COMMERCIAL_HUB'),
		('DISTRICT_CVS_TAINO_UI',	'BBG_GOLD_TAINO_HARBOR');
INSERT INTO Adjacency_YieldChanges(ID, Description, YieldType, YieldChange, AdjacentDistrict) VALUES
    ('BBG_PRODUCTION_TAINO_COMMERCIAL_HUB', 'LOC_BBG_PRODUCTION_TAINO_COMMERCIAL_HUB', 'YIELD_PRODUCTION', 2, 'DISTRICT_COMMERCIAL_HUB'),
    ('BBG_PRODUCTION_TAINO_HARBOR', 'LOC_BBG_PRODUCTION_TAINO_HARBOR', 'YIELD_PRODUCTION', 4, 'DISTRICT_HARBOR'),
    ('BBG_GOLD_TAINO_COMMERCIAL_HUB', 'LOC_BBG_GOLD_TAINO_COMMERCIAL_HUB', 'YIELD_GOLD', 3, 'DISTRICT_COMMERCIAL_HUB'),
    ('BBG_GOLD_TAINO_HARBOR', 'LOC_BBG_GOLD_TAINO_HARBOR', 'YIELD_GOLD', 6, 'DISTRICT_HARBOR');


-- Discount and cost need to be adjusted as a UD (copy from other UD)
UPDATE Districts SET Cost = 30, CostProgressionParam1 = 35 WHERE Districts.DistrictType = 'DISTRICT_CVS_TAINO_UI';
-- 2 amenities like base EC in bbg
UPDATE Districts SET Entertainment = 2 WHERE Districts.DistrictType = 'DISTRICT_CVS_TAINO_UI';

-- great work slot per arena
INSERT INTO Modifiers(ModifierId, ModifierType) VALUES
    ('BBG_ANACAONA_ARENA_GIVE_GREAT_WORK_SLOT', 'MODIFIER_PLAYER_CITIES_ADJUST_EXTRA_GREAT_WORK_SLOTS');
INSERT INTO ModifierArguments(ModifierId, Name, Value) VALUES
    ('BBG_ANACAONA_ARENA_GIVE_GREAT_WORK_SLOT', 'BuildingType', 'BUILDING_ARENA'),
    ('BBG_ANACAONA_ARENA_GIVE_GREAT_WORK_SLOT', 'GreatWorkSlotType', 'GREATWORKSLOT_WRITING'),
    ('BBG_ANACAONA_ARENA_GIVE_GREAT_WORK_SLOT', 'Amount', 2);
INSERT INTO TraitModifiers(TraitType, ModifierId) VALUES
    ('TRAIT_LEADER_CVS_ANACAONA_UA', 'BBG_ANACAONA_ARENA_GIVE_GREAT_WORK_SLOT');


-- gives +2 to adjacent theatres as all entertainment complexes
INSERT INTO District_Adjacencies
		(DistrictType,				YieldChangeId)
VALUES ('DISTRICT_THEATER',	'BBG_TAINO_THEATRE_CULTURE');
INSERT INTO Adjacency_YieldChanges(ID, Description, YieldType, YieldChange, AdjacentDistrict) VALUES
	('BBG_TAINO_THEATRE_CULTURE', 'LOC_BBG_TAINO_THEATRE_CULTURE', 'YIELD_CULTURE', 2, 'DISTRICT_CVS_TAINO_UI');

-- UP : double efficiency  faith generation; +20% for writers only
UPDATE Project_GreatPersonPoints SET Points = 6 WHERE ProjectType = 'PROJECT_CVS_TAINO_UP' AND GreatPersonClassType = 'GREAT_PERSON_CLASS_WRITER';
UPDATE Project_YieldConversions SET PercentOfProductionRate = PercentOfProductionRate * 2 WHERE ProjectType = 'PROJECT_CVS_TAINO_UP';

-- UU : reduce cost to match the cost of a scout 
UPDATE Units SET BaseSightRange=3, BaseMoves=3 WHERE UnitType='UNIT_CVS_TAINO_UU';


-- do not disable scout for FFA (foreign trade boost)
DELETE FROM Modifiers WHERE ModifierId='MODIFIER_CVS_TAINO_UU_DISABLE_SCOUT';


-- Ancient unit gets -5 agaisnt city center, see Base/Units.sql
INSERT INTO TypeTags (Type, Tag) VALUES
    ('UNIT_CVS_TAINO_UU', 'CLASS_MALUS_CITY_CENTER');

-- Macana like oki : 15 and +5 vs stronger units
UPDATE Units SET Combat=15 WHERE UnitType='UNIT_CVS_TAINO_UU';
-- 06/07/26 oligarchy rework 
UPDATE Units SET Combat=Combat+4 WHERE UnitType='UNIT_CVS_TAINO_UU';

INSERT OR IGNORE INTO Requirements(RequirementId, RequirementType) VALUES
    ('REQUIRES_COMBAT_AGAINST_STRONGER_UNIT','REQUIREMENT_OPPONENT_IS_STRONGER');
INSERT OR IGNORE INTO RequirementSets (RequirementSetId, RequirementSetType) VALUES
    ('COMBAT_AGAINST_STRONGER_UNIT_REQUIREMENTS', 'REQUIREMENTSET_TEST_ALL');
INSERT OR IGNORE INTO RequirementSetRequirements (RequirementSetId, RequirementId) VALUES
    ('COMBAT_AGAINST_STRONGER_UNIT_REQUIREMENTS', 'REQUIRES_COMBAT_AGAINST_STRONGER_UNIT');

INSERT INTO Modifiers (ModifierId, ModifierType, SubjectRequirementSetId) VALUES
	('BBG_CVS_TAINO_UU_AGAINST_STRONGER_UNITS', 'MODIFIER_UNIT_ADJUST_COMBAT_STRENGTH', 'COMBAT_AGAINST_STRONGER_UNIT_REQUIREMENTS');
INSERT INTO ModifierArguments (ModifierId, Name, Value) VALUES
	('BBG_CVS_TAINO_UU_AGAINST_STRONGER_UNITS', 'Amount', 5);

INSERT INTO Types (Type, Kind) VALUES
	('BBG_ABILITY_CVS_TAINO_UU_AGAINST_STRONGER_UNITS', 'KIND_ABILITY');
INSERT INTO TypeTags (Type, Tag) VALUES
    ('BBG_ABILITY_CVS_TAINO_UU_AGAINST_STRONGER_UNITS', 'CLASS_CVS_TAINO_UU');
INSERT INTO UnitAbilities (UnitAbilityType, Name, Description) VALUES
    ('BBG_ABILITY_CVS_TAINO_UU_AGAINST_STRONGER_UNITS', 'LOC_BBG_ABILITY_CVS_TAINO_UU_AGAINST_STRONGER_UNITS', 'LOC_BBG_ABILITY_CVS_TAINO_UU_AGAINST_STRONGER_UNITS_DESCRIPTION');
INSERT INTO UnitAbilityModifiers (UnitAbilityType, ModifierId) VALUES
    ('BBG_ABILITY_CVS_TAINO_UU_AGAINST_STRONGER_UNITS', 'BBG_CVS_TAINO_UU_AGAINST_STRONGER_UNITS');
INSERT INTO ModifierStrings (ModifierId, Context, Text) VALUES
    ('BBG_CVS_TAINO_UU_AGAINST_STRONGER_UNITS', 'Preview', 'LOC_BBG_ABILITY_CVS_TAINO_UU_AGAINST_STRONGER_UNITS_DESCRIPTION');


-- UI  not next to each other
UPDATE Improvements SET SameAdjacentValid = 0 WHERE ImprovementType = 'IMPROVEMENT_CVS_ANACAONA_UI';

-- UI allowed on hill
INSERT INTO Improvement_ValidTerrains(ImprovementType, TerrainType)
VALUES ('IMPROVEMENT_CVS_ANACAONA_UI', 'TERRAIN_GRASS_HILLS'),
       ('IMPROVEMENT_CVS_ANACAONA_UI', 'TERRAIN_PLAINS_HILLS'),
	   ('IMPROVEMENT_CVS_ANACAONA_UI', 'TERRAIN_TUNDRA_HILLS');

INSERT INTO	Modifiers (ModifierId, ModifierType, SubjectRequirementSetId)
VALUES ('MODIFIER_CVS_ANACAONA_UI_ADJ_GRASS_HILLS_FOOD', 'MODTYPE_CVS_ANACAONA_UI_PLOT_YIELD', 'REQSET_CVS_ANACAONA_UI_IS_GRASS_HILLS'),
       ('MODIFIER_CVS_ANACAONA_UI_ADJ_PLAINS_HILLS_FOOD', 'MODTYPE_CVS_ANACAONA_UI_PLOT_YIELD', 'REQSET_CVS_ANACAONA_UI_IS_PLAINS_HILLS'),
	   ('MODIFIER_CVS_ANACAONA_UI_ADJ_PLAINS_HILLS_PRODUCTION', 'MODTYPE_CVS_ANACAONA_UI_PLOT_YIELD', 'REQSET_CVS_ANACAONA_UI_IS_PLAINS_HILLS'),
	   ('MODIFIER_CVS_ANACAONA_UI_ADJ_TUNDRA_HILLS_FOOD', 'MODTYPE_CVS_ANACAONA_UI_PLOT_YIELD', 'REQSET_CVS_ANACAONA_UI_IS_TUNDRA_HILLS');

INSERT INTO	ModifierArguments (ModifierId, Name, Value)
VALUES  ('MODIFIER_CVS_ANACAONA_UI_ADJ_GRASS_HILLS_FOOD', 'YieldType', 'YIELD_FOOD'),
		('MODIFIER_CVS_ANACAONA_UI_ADJ_GRASS_HILLS_FOOD', 'Amount', 2),
		('MODIFIER_CVS_ANACAONA_UI_ADJ_PLAINS_HILLS_FOOD', 'YieldType', 'YIELD_FOOD'),
		('MODIFIER_CVS_ANACAONA_UI_ADJ_PLAINS_HILLS_FOOD', 'Amount', 1),
		('MODIFIER_CVS_ANACAONA_UI_ADJ_PLAINS_HILLS_PRODUCTION', 'YieldType', 'YIELD_PRODUCTION'),
		('MODIFIER_CVS_ANACAONA_UI_ADJ_PLAINS_HILLS_PRODUCTION', 'Amount', 1),
		('MODIFIER_CVS_ANACAONA_UI_ADJ_TUNDRA_HILLS_FOOD', 'YieldType', 'YIELD_FOOD'),
		('MODIFIER_CVS_ANACAONA_UI_ADJ_TUNDRA_HILLS_FOOD', 'Amount', 1);

INSERT INTO RequirementSetRequirements (RequirementSetId, RequirementId)
VALUES	('REQSET_CVS_ANACAONA_UI_IS_GRASS_HILLS', 'REQ_CVS_ANACAONA_UI_ADJ_RESOURCE_MET'),
		('REQSET_CVS_ANACAONA_UI_IS_GRASS_HILLS', 'REQ_CVS_ANACAONA_UI_PLOT_IS_GRASS_HILLS'),
		('REQSET_CVS_ANACAONA_UI_IS_PLAINS_HILLS', 'REQ_CVS_ANACAONA_UI_ADJ_RESOURCE_MET'),
		('REQSET_CVS_ANACAONA_UI_IS_PLAINS_HILLS', 'REQ_CVS_ANACAONA_UI_PLOT_IS_PLAINS_HILLS'),
		('REQSET_CVS_ANACAONA_UI_IS_TUNDRA_HILLS', 'REQ_CVS_ANACAONA_UI_ADJ_RESOURCE_MET'),
		('REQSET_CVS_ANACAONA_UI_IS_TUNDRA_HILLS', 'REQ_CVS_ANACAONA_UI_PLOT_IS_TUNDRA_HILLS');

INSERT INTO RequirementSets (RequirementSetId, RequirementSetType)
VALUES  ('REQSET_CVS_ANACAONA_UI_IS_GRASS_HILLS', 'REQUIREMENTSET_TEST_ALL'),
		('REQSET_CVS_ANACAONA_UI_IS_PLAINS_HILLS', 'REQUIREMENTSET_TEST_ALL'),
		('REQSET_CVS_ANACAONA_UI_IS_TUNDRA_HILLS', 'REQUIREMENTSET_TEST_ALL');

INSERT INTO Requirements (RequirementId, RequirementType,Inverse)
VALUES ('REQ_CVS_ANACAONA_UI_PLOT_IS_GRASS_HILLS','REQUIREMENT_PLOT_TERRAIN_TYPE_MATCHES',0),
		('REQ_CVS_ANACAONA_UI_PLOT_IS_PLAINS_HILLS','REQUIREMENT_PLOT_TERRAIN_TYPE_MATCHES',0),
		('REQ_CVS_ANACAONA_UI_PLOT_IS_TUNDRA_HILLS','REQUIREMENT_PLOT_TERRAIN_TYPE_MATCHES',0);

INSERT INTO RequirementArguments (RequirementId, Name, Value)
VALUES	('REQ_CVS_ANACAONA_UI_PLOT_IS_GRASS_HILLS', 'TerrainType', 'TERRAIN_GRASS_HILLS'),
		('REQ_CVS_ANACAONA_UI_PLOT_IS_PLAINS_HILLS', 'TerrainType', 'TERRAIN_PLAINS_HILLS'),
		('REQ_CVS_ANACAONA_UI_PLOT_IS_TUNDRA_HILLS', 'TerrainType', 'TERRAIN_TUNDRA_HILLS');
	

INSERT INTO	ImprovementModifiers (ImprovementType, ModifierId)
VALUES ('IMPROVEMENT_CVS_ANACAONA_UI', 'MODIFIER_CVS_ANACAONA_UI_ADJ_GRASS_HILLS_FOOD'),
       ('IMPROVEMENT_CVS_ANACAONA_UI', 'MODIFIER_CVS_ANACAONA_UI_ADJ_PLAINS_HILLS_FOOD'),
	   ('IMPROVEMENT_CVS_ANACAONA_UI', 'MODIFIER_CVS_ANACAONA_UI_ADJ_PLAINS_HILLS_PRODUCTION'),
	   ('IMPROVEMENT_CVS_ANACAONA_UI', 'MODIFIER_CVS_ANACAONA_UI_ADJ_TUNDRA_HILLS_FOOD');

INSERT INTO Adjacency_YieldChanges (ID,Description,YieldType,YieldChange,TilesRequired,PrereqCivic,AdjacentResourceClass)
VALUES 	('BBG_GOLD_ANACAONA_UI_BONUS','Placeholder','YIELD_GOLD',2,1,'CIVIC_MERCANTILISM','RESOURCECLASS_BONUS'),
		('BBG_GOLD_ANACAONA_UI_LUX','Placeholder','YIELD_GOLD',2,1,'CIVIC_MERCANTILISM','RESOURCECLASS_LUXURY');

INSERT INTO	Improvement_Adjacencies(ImprovementType, YieldChangeId)
VALUES 	('IMPROVEMENT_CVS_ANACAONA_UI', 'BBG_GOLD_ANACAONA_UI_BONUS'),
		('IMPROVEMENT_CVS_ANACAONA_UI', 'BBG_GOLD_ANACAONA_UI_LUX');

INSERT INTO Improvement_YieldChanges (ImprovementType, YieldType, YieldChange)
VALUES ('IMPROVEMENT_CVS_ANACAONA_UI', 'YIELD_GOLD', 0);



INSERT INTO Improvement_BonusYieldChanges
		(Id,	ImprovementType,				YieldType,			BonusYieldChange,	PrereqCivic)
VALUES  (404,	'IMPROVEMENT_CVS_ANACAONA_UI',	'YIELD_CULTURE',	1,					'CIVIC_NATURAL_HISTORY'	);

DELETE FROM Improvement_BonusYieldChanges WHERE Id = 402; -- cultural heritage