--========Natural Wonder Types========--
INSERT INTO WonderTerrainFeature_BBG(WonderType, TerrainClassType, FeatureType, Other) VALUES
	('FEATURE_EVEREST', 'TERRAIN_CLASS_MOUNTAIN', NULL, NULL),
	('FEATURE_KILIMANJARO', 'TERRAIN_CLASS_MOUNTAIN', 'FEATURE_VOLCANO', NULL),
	('FEATURE_TORRES_DEL_PAINE', 'TERRAIN_CLASS_MOUNTAIN', NULL, NULL),
	('FEATURE_PANTANAL', NULL, 'FEATURE_MARSH', NULL),
	('FEATURE_BARRIER_REEF', NULL, 'FEATURE_REEF', 'WATER'),
	('FEATURE_CRATER_LAKE', NULL, NULL, 'LAKE'),
	('FEATURE_DEAD_SEA', NULL, NULL, 'LAKE'),
	('FEATURE_PIOPIOTAHI', NULL, NULL, 'FJORD'),
	('FEATURE_GALAPAGOS', NULL, NULL, 'WATER'),
	('FEATURE_YOSEMITE', 'TERRAIN_CLASS_MOUNTAIN', NULL, NULL),
	('FEATURE_TSINGY', NULL, NULL, 'OTHER'),
	('FEATURE_CLIFFS_DOVER', NULL, NULL, 'COASTAL');