--==========
-- EGYPT (xp2)
--==========
INSERT INTO Requirements (RequirementId, RequirementType) VALUES
    ('REQUIRES_PLOT_HAS_FLOODPLAINS_GRASSLAND', 'REQUIREMENT_PLOT_FEATURE_TYPE_MATCHES'),
    ('REQUIRES_PLOT_HAS_FLOODPLAINS_PLAINS', 'REQUIREMENT_PLOT_FEATURE_TYPE_MATCHES');
INSERT INTO RequirementArguments (RequirementId, Name, Value) VALUES
    ('REQUIRES_PLOT_HAS_FLOODPLAINS_GRASSLAND', 'FeatureType', 'FEATURE_FLOODPLAINS_GRASSLAND'),
    ('REQUIRES_PLOT_HAS_FLOODPLAINS_PLAINS', 'FeatureType', 'FEATURE_FLOODPLAINS_PLAINS');
INSERT INTO RequirementSetRequirements (RequirementSetId, RequirementId) VALUES
    ('BBG_REQUIRES_PLOT_HAS_FLOODPLAINS', 'REQUIRES_PLOT_HAS_FLOODPLAINS_GRASSLAND'),
    ('BBG_REQUIRES_PLOT_HAS_FLOODPLAINS', 'REQUIRES_PLOT_HAS_FLOODPLAINS_PLAINS');

--30/09/24 Maryanus cost 5 horse
UPDATE Units SET StrategicResource='RESOURCE_HORSES' WHERE UnitType='UNIT_EGYPTIAN_CHARIOT_ARCHER';
INSERT INTO Units_XP2 (UnitType, ResourceCost) VALUES
    ('UNIT_EGYPTIAN_CHARIOT_ARCHER', 10);
