--==============================================================================================
--******				GOVERNMENT						   ******
--==============================================================================================

-- ==============================================================
-- ***                          AUTOCRACY                     *** 
-- ============================================================== 

-- 10/03/24 Autocracy gives 1 food and production to monument if the city have at least one district
INSERT INTO Modifiers (ModifierId, ModifierType, SubjectRequirementSetId) VALUES
    ('BBG_MONUMENT_FOOD_AUTOCRACY_1_DISTRICT', 'MODIFIER_PLAYER_CITIES_ADJUST_BUILDING_YIELD_CHANGE', 'CITY_HAS_1_SPECIALTY_DISTRICT'),
    ('BBG_MONUMENT_PRODUCTION_AUTOCRACY_1_DISTRICT', 'MODIFIER_PLAYER_CITIES_ADJUST_BUILDING_YIELD_CHANGE', 'CITY_HAS_1_SPECIALTY_DISTRICT');
INSERT INTO ModifierArguments(ModifierId, Name, Value) VALUES
    ('BBG_MONUMENT_FOOD_AUTOCRACY_1_DISTRICT', 'BuildingType', 'BUILDING_MONUMENT'),
    ('BBG_MONUMENT_FOOD_AUTOCRACY_1_DISTRICT', 'YieldType', 'YIELD_FOOD'),
    ('BBG_MONUMENT_FOOD_AUTOCRACY_1_DISTRICT', 'Amount', '1'),
    ('BBG_MONUMENT_PRODUCTION_AUTOCRACY_1_DISTRICT', 'BuildingType', 'BUILDING_MONUMENT'),
    ('BBG_MONUMENT_PRODUCTION_AUTOCRACY_1_DISTRICT', 'YieldType', 'YIELD_PRODUCTION'),
    ('BBG_MONUMENT_PRODUCTION_AUTOCRACY_1_DISTRICT', 'Amount', '1');
INSERT INTO GovernmentModifiers (GovernmentType, ModifierId) VALUES
    ('GOVERNMENT_AUTOCRACY', 'BBG_MONUMENT_FOOD_AUTOCRACY_1_DISTRICT'),
    ('GOVERNMENT_AUTOCRACY', 'BBG_MONUMENT_PRODUCTION_AUTOCRACY_1_DISTRICT');
INSERT INTO PolicyModifiers (PolicyType, ModifierId) VALUES
    ('POLICY_GOV_AUTOCRACY', 'BBG_MONUMENT_FOOD_AUTOCRACY_1_DISTRICT'),
    ('POLICY_GOV_AUTOCRACY', 'BBG_MONUMENT_PRODUCTION_AUTOCRACY_1_DISTRICT');

-- ==============================================================
-- ***                          OLIGARCHY                     *** 
-- ============================================================== 

DELETE FROM GovernmentModifiers WHERE GovernmentType='GOVERNMENT_OLIGARCHY' AND ModifierId='OLIGARCHY_MELEE';
DELETE FROM GovernmentModifiers WHERE GovernmentType='GOVERNMENT_OLIGARCHY' AND ModifierId='OLIGARCHY_UNIT_EXPERIENCE';
DELETE FROM PolicyModifiers WHERE PolicyType='POLICY_GOV_OLIGARCHY' AND ModifierId='OLIGARCHY_LEGACY_MELEE';

-- 04/07/26 all units currently affected by oligarchy gains +4 cs base with Philosophy Politics
-- UPDATE Modifiers SET OwnerRequirementSetId='BBG_UTILS_PLAYER_HAS_CIVIC_POLITICAL_PHILOSOPHY_REQSET' WHERE ModifierId='OLIGARCHY_MELEE';
-- INSERT INTO TraitModifiers (TraitType, ModifierId) VALUES
--     ('TRAIT_LEADER_MAJOR_CIV', 'OLIGARCHY_MELEE');

-- gov effect : +1 mp for non military units in friendly territory
INSERT INTO RequirementSets (RequirementSetId, RequirementSetType) VALUES
    ('BGB_REQUIREMENT_UNIT_IS_IN_OWNER_TERRITORY_REQUIREMENT', 'REQUIREMENTSET_TEST_ALL'),
    ('BGB_UNIT_IS_NOT_MILITARY_REQUIREMENTSET', 'REQUIREMENTSET_TEST_ANY');
INSERT INTO RequirementSetRequirements (RequirementSetId, RequirementId) VALUES
    ('BGB_REQUIREMENT_UNIT_IS_IN_OWNER_TERRITORY_REQUIREMENT', 'UNIT_IN_OWNER_TERRITORY_REQUIREMENT'),
    ('BGB_UNIT_IS_NOT_MILITARY_REQUIREMENTSET', 'BBG_UNIT_IS_FORMATION_CLASS_CIVILIAN'),
    ('BGB_UNIT_IS_NOT_MILITARY_REQUIREMENTSET', 'BBG_UNIT_IS_FORMATION_CLASS_SUPPORT');
INSERT INTO Modifiers (ModifierId, ModifierType, SubjectRequirementSetId) VALUES
    ('BBG_OLIGARCHY_UNIT_MOVEMENT_NON_MILITARY', 'MODIFIER_PLAYER_UNITS_ADJUST_FRIENDLY_TERRITORY_START_MOVEMENT', 'BGB_UNIT_IS_NOT_MILITARY_REQUIREMENTSET');
INSERT INTO ModifierArguments (ModifierId, Name, Value) VALUES
    ('BBG_OLIGARCHY_UNIT_MOVEMENT_NON_MILITARY', 'Amount', 1);
INSERT INTO GovernmentModifiers (GovernmentType, ModifierId) VALUES
    ('GOVERNMENT_OLIGARCHY', 'BBG_OLIGARCHY_UNIT_MOVEMENT_NON_MILITARY');

-- new legacy : +20% exp on units during combat and +1mp on military units
-- 12/07/26 : legacy : changed to harbors and encampments districts and buildings gives +1 gousing and +1 prod & +20% exp
-- 21/07/26 : legacy : +20%exp and +1combat strength per level (from ceasar)

-- legacy 20% xp
-- 07/08/26 : legacy at 40%
INSERT INTO Modifiers (ModifierId, ModifierType, SubjectRequirementSetId) VALUES
    ('BBG_OLIGARCHY_UNIT_EXPERIENCE', 'MODIFIER_PLAYER_UNITS_ADJUST_UNIT_EXPERIENCE_MODIFIER', NULL);
INSERT INTO ModifierArguments (ModifierId, Name, Value) VALUES
    ('BBG_OLIGARCHY_UNIT_EXPERIENCE', 'Amount', 40);
INSERT INTO GovernmentModifiers (GovernmentType, ModifierId) VALUES
    ('GOVERNMENT_OLIGARCHY', 'BBG_OLIGARCHY_UNIT_EXPERIENCE');
INSERT INTO PolicyModifiers (PolicyType, ModifierId) VALUES
    ('POLICY_GOV_OLIGARCHY', 'BBG_OLIGARCHY_UNIT_EXPERIENCE');

-- -- 12/07/26 : legacy
-- INSERT INTO Modifiers (ModifierId, ModifierType, SubjectRequirementSetId) VALUES
--     ('BBG_OLIGARCHY_BOOST_HARBOR_HOUSING', 'MODIFIER_PLAYER_DISTRICTS_ADJUST_HOUSING', 'BBG_DISTRICT_IS_DISTRICT_HARBOR_REQSET'),
--     ('BBG_OLIGARCHY_BOOST_ENCAMPMENT_HOUSING', 'MODIFIER_PLAYER_DISTRICTS_ADJUST_HOUSING', 'BBG_DISTRICT_IS_DISTRICT_ENCAMPMENT_REQSET'),
--     ('BBG_OLIGARCHY_BOOST_HARBOR_PRODUCTION', 'MODIFIER_PLAYER_DISTRICTS_ADJUST_YIELD_CHANGE','BBG_DISTRICT_IS_DISTRICT_HARBOR_REQSET'),
--     ('BBG_OLIGARCHY_BOOST_ENCAMPMENT_PRODUCTION', 'MODIFIER_PLAYER_DISTRICTS_ADJUST_YIELD_CHANGE','BBG_DISTRICT_IS_DISTRICT_ENCAMPMENT_REQSET');
-- INSERT INTO Modifiers (ModifierId, ModifierType) 
--     SELECT 'BBG_OLIGARCHY_BOOST_' || BuildingType || '_PRODUCTION', 'MODIFIER_PLAYER_CITIES_ADJUST_BUILDING_YIELD_CHANGE' FROM Buildings WHERE PrereqDistrict IN ('DISTRICT_HARBOR', 'DISTRICT_ENCAMPMENT');
-- INSERT INTO Modifiers (ModifierId, ModifierType, SubjectRequirementSetId)
--     SELECT 'BBG_OLIGARCHY_BOOST_' || BuildingType || '_HOUSING', 'MODIFIER_PLAYER_CITIES_ADJUST_POLICY_HOUSING', 'BBG_UTILS_CITY_HAS_' || BuildingType FROM Buildings WHERE PrereqDistrict IN ('DISTRICT_HARBOR', 'DISTRICT_ENCAMPMENT');

-- INSERT INTO ModifierArguments (ModifierId, Name, Value) VALUES
--     ('BBG_OLIGARCHY_BOOST_HARBOR_HOUSING', 'Amount', 1),
--     ('BBG_OLIGARCHY_BOOST_ENCAMPMENT_HOUSING', 'Amount', 1),
--     ('BBG_OLIGARCHY_BOOST_HARBOR_PRODUCTION', 'YieldType', 'YIELD_PRODUCTION'),
--     ('BBG_OLIGARCHY_BOOST_HARBOR_PRODUCTION', 'Amount', 1),
--     ('BBG_OLIGARCHY_BOOST_ENCAMPMENT_PRODUCTION', 'YieldType', 'YIELD_PRODUCTION'),
--     ('BBG_OLIGARCHY_BOOST_ENCAMPMENT_PRODUCTION', 'Amount', 1);

-- INSERT INTO ModifierArguments (ModifierId, Name, Value) 
--     SELECT 'BBG_OLIGARCHY_BOOST_' || BuildingType || '_PRODUCTION', 'YieldType', 'YIELD_PRODUCTION' FROM Buildings WHERE PrereqDistrict IN ('DISTRICT_HARBOR', 'DISTRICT_ENCAMPMENT');
-- INSERT INTO ModifierArguments (ModifierId, Name, Value) 
--     SELECT 'BBG_OLIGARCHY_BOOST_' || BuildingType || '_PRODUCTION', 'BuildingType', BuildingType FROM Buildings WHERE PrereqDistrict IN ('DISTRICT_HARBOR', 'DISTRICT_ENCAMPMENT');
-- INSERT INTO ModifierArguments (ModifierId, Name, Value) 
--     SELECT 'BBG_OLIGARCHY_BOOST_' || BuildingType || '_PRODUCTION', 'Amount', '1' FROM Buildings WHERE PrereqDistrict IN ('DISTRICT_HARBOR', 'DISTRICT_ENCAMPMENT');
-- INSERT INTO ModifierArguments (ModifierId, Name, Value) 
--     SELECT 'BBG_OLIGARCHY_BOOST_' || BuildingType || '_HOUSING', 'Amount', '1' FROM Buildings WHERE PrereqDistrict IN ('DISTRICT_HARBOR', 'DISTRICT_ENCAMPMENT');

-- INSERT INTO GovernmentModifiers (GovernmentType, ModifierId) VALUES
--     ('GOVERNMENT_OLIGARCHY', 'BBG_OLIGARCHY_BOOST_HARBOR_HOUSING'),
--     ('GOVERNMENT_OLIGARCHY', 'BBG_OLIGARCHY_BOOST_ENCAMPMENT_HOUSING'),
--     ('GOVERNMENT_OLIGARCHY', 'BBG_OLIGARCHY_BOOST_HARBOR_PRODUCTION'),
--     ('GOVERNMENT_OLIGARCHY', 'BBG_OLIGARCHY_BOOST_ENCAMPMENT_PRODUCTION');
-- INSERT INTO GovernmentModifiers (GovernmentType, ModifierId) 
--     SELECT 'GOVERNMENT_OLIGARCHY', 'BBG_OLIGARCHY_BOOST_' || BuildingType || '_PRODUCTION' FROM Buildings WHERE PrereqDistrict IN ('DISTRICT_HARBOR', 'DISTRICT_ENCAMPMENT');
-- INSERT INTO GovernmentModifiers (GovernmentType, ModifierId) 
--     SELECT 'GOVERNMENT_OLIGARCHY', 'BBG_OLIGARCHY_BOOST_' || BuildingType || '_HOUSING' FROM Buildings WHERE PrereqDistrict IN ('DISTRICT_HARBOR', 'DISTRICT_ENCAMPMENT');

-- INSERT INTO PolicyModifiers (PolicyType, ModifierId) VALUES
--     ('POLICY_GOV_OLIGARCHY', 'BBG_OLIGARCHY_BOOST_HARBOR_HOUSING'),
--     ('POLICY_GOV_OLIGARCHY', 'BBG_OLIGARCHY_BOOST_ENCAMPMENT_HOUSING'),
--     ('POLICY_GOV_OLIGARCHY', 'BBG_OLIGARCHY_BOOST_HARBOR_PRODUCTION'),
--     ('POLICY_GOV_OLIGARCHY', 'BBG_OLIGARCHY_BOOST_ENCAMPMENT_PRODUCTION');
-- INSERT INTO PolicyModifiers (PolicyType, ModifierId) 
--     SELECT 'POLICY_GOV_OLIGARCHY', 'BBG_OLIGARCHY_BOOST_' || BuildingType || '_PRODUCTION' FROM Buildings WHERE PrereqDistrict IN ('DISTRICT_HARBOR', 'DISTRICT_ENCAMPMENT');
-- INSERT INTO PolicyModifiers (PolicyType, ModifierId) 
--     SELECT 'POLICY_GOV_OLIGARCHY', 'BBG_OLIGARCHY_BOOST_' || BuildingType || '_HOUSING' FROM Buildings WHERE PrereqDistrict IN ('DISTRICT_HARBOR', 'DISTRICT_ENCAMPMENT');

-- 21/07/26 : legacy : +1combat strength per level (from ceasar)

-- oligarchy effect -- use utils custom requirements

INSERT INTO Modifiers (ModifierId, ModifierType, SubjectRequirementSetId)
    SELECT 'BBG_OLIGARCHY_' || UnitPromotionType || '_GIVER', 'MODIFIER_PLAYER_UNITS_GRANT_ABILITY' , 'BBG_UNIT_' || UnitPromotionType || '_REQUIREMENTS' FROM UnitPromotions 
    WHERE PromotionClass IN
   ('PROMOTION_CLASS_RECON', 'PROMOTION_CLASS_MELEE', 'PROMOTION_CLASS_RANGED', 'PROMOTION_CLASS_SIEGE', 'PROMOTION_CLASS_ANTI_CAVALRY', 'PROMOTION_CLASS_LIGHT_CAVALRY', 'PROMOTION_CLASS_HEAVY_CAVALRY', 'PROMOTION_CLASS_NAVAL_MELEE', 'PROMOTION_CLASS_NAVAL_RANGED', 'PROMOTION_CLASS_NAVAL_CARRIER', 'PROMOTION_CLASS_NAVAL_RAIDER', 'PROMOTION_CLASS_MONK', 'PROMOTION_CLASS_NIHANG', 'PROMOTION_CLASS_AIR_FIGHTER', 'PROMOTION_CLASS_AIR_BOMBER');

INSERT INTO ModifierArguments (ModifierId, Name, Value)
    SELECT 'BBG_OLIGARCHY_' || UnitPromotionType || '_GIVER', 'AbilityType', 'BBG_ABILITY_OLIGARCHY_' || UnitPromotionType || '_BONUS_COMBAT' FROM UnitPromotions
    WHERE PromotionClass IN
   ('PROMOTION_CLASS_RECON', 'PROMOTION_CLASS_MELEE', 'PROMOTION_CLASS_RANGED', 'PROMOTION_CLASS_SIEGE', 'PROMOTION_CLASS_ANTI_CAVALRY', 'PROMOTION_CLASS_LIGHT_CAVALRY', 'PROMOTION_CLASS_HEAVY_CAVALRY', 'PROMOTION_CLASS_NAVAL_MELEE', 'PROMOTION_CLASS_NAVAL_RANGED', 'PROMOTION_CLASS_NAVAL_CARRIER', 'PROMOTION_CLASS_NAVAL_RAIDER', 'PROMOTION_CLASS_MONK', 'PROMOTION_CLASS_NIHANG', 'PROMOTION_CLASS_AIR_FIGHTER', 'PROMOTION_CLASS_AIR_BOMBER');

INSERT INTO Types (Type, Kind)
    SELECT 'BBG_ABILITY_OLIGARCHY_' || UnitPromotionType || '_BONUS_COMBAT', 'KIND_ABILITY' FROM UnitPromotions
    WHERE PromotionClass IN
   ('PROMOTION_CLASS_RECON', 'PROMOTION_CLASS_MELEE', 'PROMOTION_CLASS_RANGED', 'PROMOTION_CLASS_SIEGE', 'PROMOTION_CLASS_ANTI_CAVALRY', 'PROMOTION_CLASS_LIGHT_CAVALRY', 'PROMOTION_CLASS_HEAVY_CAVALRY', 'PROMOTION_CLASS_NAVAL_MELEE', 'PROMOTION_CLASS_NAVAL_RANGED', 'PROMOTION_CLASS_NAVAL_CARRIER', 'PROMOTION_CLASS_NAVAL_RAIDER', 'PROMOTION_CLASS_MONK', 'PROMOTION_CLASS_NIHANG', 'PROMOTION_CLASS_AIR_FIGHTER', 'PROMOTION_CLASS_AIR_BOMBER');

INSERT INTO UnitAbilities (UnitAbilityType, Name, Description, Inactive)
    SELECT 'BBG_ABILITY_OLIGARCHY_' || UnitPromotionType || '_BONUS_COMBAT', null, null, 1 FROM UnitPromotions
    WHERE PromotionClass IN
   ('PROMOTION_CLASS_RECON', 'PROMOTION_CLASS_MELEE', 'PROMOTION_CLASS_RANGED', 'PROMOTION_CLASS_SIEGE', 'PROMOTION_CLASS_ANTI_CAVALRY', 'PROMOTION_CLASS_LIGHT_CAVALRY', 'PROMOTION_CLASS_HEAVY_CAVALRY', 'PROMOTION_CLASS_NAVAL_MELEE', 'PROMOTION_CLASS_NAVAL_RANGED', 'PROMOTION_CLASS_NAVAL_CARRIER', 'PROMOTION_CLASS_NAVAL_RAIDER', 'PROMOTION_CLASS_MONK', 'PROMOTION_CLASS_NIHANG', 'PROMOTION_CLASS_AIR_FIGHTER', 'PROMOTION_CLASS_AIR_BOMBER')
    ;
INSERT INTO TypeTags (Type, Tag)
    SELECT 'BBG_ABILITY_OLIGARCHY_' || UnitPromotionType || '_BONUS_COMBAT', 'CLASS_ALL_COMBAT_UNITS' FROM UnitPromotions
    WHERE PromotionClass IN
   ('PROMOTION_CLASS_RECON', 'PROMOTION_CLASS_MELEE', 'PROMOTION_CLASS_RANGED', 'PROMOTION_CLASS_SIEGE', 'PROMOTION_CLASS_ANTI_CAVALRY', 'PROMOTION_CLASS_LIGHT_CAVALRY', 'PROMOTION_CLASS_HEAVY_CAVALRY', 'PROMOTION_CLASS_NAVAL_MELEE', 'PROMOTION_CLASS_NAVAL_RANGED', 'PROMOTION_CLASS_NAVAL_CARRIER', 'PROMOTION_CLASS_NAVAL_RAIDER', 'PROMOTION_CLASS_MONK', 'PROMOTION_CLASS_NIHANG', 'PROMOTION_CLASS_AIR_FIGHTER', 'PROMOTION_CLASS_AIR_BOMBER');

INSERT INTO UnitAbilityModifiers (UnitAbilityType, ModifierId)
    SELECT 'BBG_ABILITY_OLIGARCHY_' || UnitPromotionType || '_BONUS_COMBAT', 'BBG_OLIGARCHY_BONUS_COMBAT_MODIFIER' FROM UnitPromotions
    WHERE PromotionClass IN
   ('PROMOTION_CLASS_RECON', 'PROMOTION_CLASS_MELEE', 'PROMOTION_CLASS_RANGED', 'PROMOTION_CLASS_SIEGE', 'PROMOTION_CLASS_ANTI_CAVALRY', 'PROMOTION_CLASS_LIGHT_CAVALRY', 'PROMOTION_CLASS_HEAVY_CAVALRY', 'PROMOTION_CLASS_NAVAL_MELEE', 'PROMOTION_CLASS_NAVAL_RANGED', 'PROMOTION_CLASS_NAVAL_CARRIER', 'PROMOTION_CLASS_NAVAL_RAIDER', 'PROMOTION_CLASS_MONK', 'PROMOTION_CLASS_NIHANG', 'PROMOTION_CLASS_AIR_FIGHTER', 'PROMOTION_CLASS_AIR_BOMBER');

INSERT INTO Modifiers (ModifierId, ModifierType , Repeatable )
    VALUES ('BBG_OLIGARCHY_BONUS_COMBAT_MODIFIER', 'MODIFIER_UNIT_ADJUST_COMBAT_STRENGTH' , 1 );

INSERT INTO ModifierArguments (ModifierId, Name, Value) 
    VALUES ('BBG_OLIGARCHY_BONUS_COMBAT_MODIFIER', 'Amount', 1);

INSERT INTO ModifierStrings (ModifierId, Context, Text)
    VALUES ('BBG_OLIGARCHY_BONUS_COMBAT_MODIFIER', 'Preview', 'LOC_BBG_OLIGARCHY_BONUS_COMBAT_MODIFIER_PREVIEW');
    
INSERT INTO GovernmentModifiers (GovernmentType, ModifierId)
    SELECT 'GOVERNMENT_OLIGARCHY', 'BBG_OLIGARCHY_' || UnitPromotionType || '_GIVER' FROM UnitPromotions
    WHERE PromotionClass IN
   ('PROMOTION_CLASS_RECON', 'PROMOTION_CLASS_MELEE', 'PROMOTION_CLASS_RANGED', 'PROMOTION_CLASS_SIEGE', 'PROMOTION_CLASS_ANTI_CAVALRY', 'PROMOTION_CLASS_LIGHT_CAVALRY', 'PROMOTION_CLASS_HEAVY_CAVALRY', 'PROMOTION_CLASS_NAVAL_MELEE', 'PROMOTION_CLASS_NAVAL_RANGED', 'PROMOTION_CLASS_NAVAL_CARRIER', 'PROMOTION_CLASS_NAVAL_RAIDER', 'PROMOTION_CLASS_MONK', 'PROMOTION_CLASS_NIHANG', 'PROMOTION_CLASS_AIR_FIGHTER', 'PROMOTION_CLASS_AIR_BOMBER');

INSERT INTO PolicyModifiers (PolicyType, ModifierId)
    SELECT 'POLICY_GOV_OLIGARCHY', 'BBG_OLIGARCHY_' || UnitPromotionType || '_GIVER' FROM UnitPromotions
    WHERE PromotionClass IN
   ('PROMOTION_CLASS_RECON', 'PROMOTION_CLASS_MELEE', 'PROMOTION_CLASS_RANGED', 'PROMOTION_CLASS_SIEGE', 'PROMOTION_CLASS_ANTI_CAVALRY', 'PROMOTION_CLASS_LIGHT_CAVALRY', 'PROMOTION_CLASS_HEAVY_CAVALRY', 'PROMOTION_CLASS_NAVAL_MELEE', 'PROMOTION_CLASS_NAVAL_RANGED', 'PROMOTION_CLASS_NAVAL_CARRIER', 'PROMOTION_CLASS_NAVAL_RAIDER', 'PROMOTION_CLASS_MONK', 'PROMOTION_CLASS_NIHANG', 'PROMOTION_CLASS_AIR_FIGHTER', 'PROMOTION_CLASS_AIR_BOMBER');
-- ==============================================================
-- ***                  MERCHANT REPUBLIC                     *** 
-- ============================================================== 

-- Government slot
UPDATE Government_SlotCounts SET NumSlots=1 WHERE GovernmentType='GOVERNMENT_MERCHANT_REPUBLIC' AND GovernmentSlotType='SLOT_DIPLOMATIC';
UPDATE Government_SlotCounts SET NumSlots=2 WHERE GovernmentType='GOVERNMENT_MERCHANT_REPUBLIC' AND GovernmentSlotType='SLOT_WILDCARD';

-- 16/03/26 new legacy bonus : +1 pm for boats and embarked units
--boat movement bonus
INSERT INTO Modifiers (ModifierId, ModifierType) VALUES
    ('BBG_MERCHANT_REPUBLIC_SEA_MOVEMENT', 'MODIFIER_PLAYER_UNITS_GRANT_ABILITY'),
    ('BBG_MERCHANT_REPUBLIC_MOVEMENT_BUFF', 'MODIFIER_PLAYER_UNIT_ADJUST_SEA_MOVEMENT');
INSERT INTO UnitAbilities (UnitAbilityType, Name, Description, Inactive) VALUES
    ('BBG_ABILITY_MERCHANT_REPUBLIC_MOVEMENT', 'LOC_BBG_ABILITY_MERCHANT_REPUBLIC_MOVEMENT_NAME', 'LOC_BBG_ABILITY_MERCHANT_REPUBLIC_MOVEMENT_DESC', 1);
INSERT INTO ModifierArguments (ModifierId, Name, Value) VALUES
    ('BBG_MERCHANT_REPUBLIC_SEA_MOVEMENT', 'AbilityType', 'BBG_ABILITY_MERCHANT_REPUBLIC_MOVEMENT'),
    ('BBG_MERCHANT_REPUBLIC_MOVEMENT_BUFF', 'Amount', 1);
INSERT INTO UnitAbilityModifiers (UnitAbilityType, ModifierId) VALUES
    ('BBG_ABILITY_MERCHANT_REPUBLIC_MOVEMENT', 'BBG_MERCHANT_REPUBLIC_MOVEMENT_BUFF');
-- embarked movement bonus
INSERT INTO Modifiers(ModifierId, ModifierType) VALUES
    ('BBG_MERCHANT_REPUBLIC_EMBARKED_MOVEMENT', 'MODIFIER_PLAYER_ADJUST_EMBARKED_MOVEMENT');
INSERT INTO ModifierArguments (ModifierId, Name, Value) VALUES
    ('BBG_MERCHANT_REPUBLIC_EMBARKED_MOVEMENT', 'Amount', 1);
-- embarked movement text only (for tooltip)
INSERT INTO Modifiers(ModifierId, ModifierType) VALUES
    ('BBG_MERCHANT_REPUBLIC_ADD_EMBARKED_ABILITY_TEXT_ONLY', 'MODIFIER_PLAYER_UNITS_GRANT_ABILITY');
INSERT INTO UnitAbilities (UnitAbilityType, Name, Description, Inactive) VALUES
    ('BBG_ABILITY_MERCHANT_REPUBLIC_EMBARKED_MOVEMENT', 'LOC_BBG_ABILITY_MERCHANT_REPUBLIC_EMBARKED_MOVEMENT_NAME', 'LOC_BBG_ABILITY_MERCHANT_REPUBLIC_EMBARKED_MOVEMENT_DESC', 1);
INSERT INTO ModifierArguments (ModifierId, Name, Value) VALUES
    ('BBG_MERCHANT_REPUBLIC_ADD_EMBARKED_ABILITY_TEXT_ONLY', 'AbilityType', 'BBG_ABILITY_MERCHANT_REPUBLIC_EMBARKED_MOVEMENT');


INSERT INTO GovernmentModifiers (GovernmentType, ModifierId) VALUES
    ('GOVERNMENT_MERCHANT_REPUBLIC', 'BBG_MERCHANT_REPUBLIC_SEA_MOVEMENT'),
    ('GOVERNMENT_MERCHANT_REPUBLIC', 'BBG_MERCHANT_REPUBLIC_EMBARKED_MOVEMENT'),
    ('GOVERNMENT_MERCHANT_REPUBLIC', 'BBG_MERCHANT_REPUBLIC_ADD_EMBARKED_ABILITY_TEXT_ONLY');

INSERT INTO PolicyModifiers(PolicyType, ModifierId) VALUES
    ('POLICY_GOV_MERCHANT_REPUBLIC', 'BBG_MERCHANT_REPUBLIC_SEA_MOVEMENT'),
    ('POLICY_GOV_MERCHANT_REPUBLIC', 'BBG_MERCHANT_REPUBLIC_EMBARKED_MOVEMENT'),
    ('POLICY_GOV_MERCHANT_REPUBLIC', 'BBG_MERCHANT_REPUBLIC_ADD_EMBARKED_ABILITY_TEXT_ONLY');

INSERT INTO Types(Type, Kind) VALUES
    ('BBG_ABILITY_MERCHANT_REPUBLIC_MOVEMENT', 'KIND_ABILITY');
INSERT INTO TypeTags(Type, Tag) VALUES
    ('BBG_ABILITY_MERCHANT_REPUBLIC_MOVEMENT', 'CLASS_NAVAL_MELEE'),
    ('BBG_ABILITY_MERCHANT_REPUBLIC_MOVEMENT', 'CLASS_NAVAL_RANGED'),
    ('BBG_ABILITY_MERCHANT_REPUBLIC_MOVEMENT', 'CLASS_NAVAL_RAIDER'),
    ('BBG_ABILITY_MERCHANT_REPUBLIC_MOVEMENT', 'CLASS_NAVAL_CARRIER');
INSERT INTO Types(Type, Kind) VALUES
    ('BBG_ABILITY_MERCHANT_REPUBLIC_EMBARKED_MOVEMENT', 'KIND_ABILITY');
INSERT INTO TypeTags(Type, Tag) VALUES
    ('BBG_ABILITY_MERCHANT_REPUBLIC_EMBARKED_MOVEMENT', 'CLASS_ANTI_CAVALRY'),
    ('BBG_ABILITY_MERCHANT_REPUBLIC_EMBARKED_MOVEMENT', 'CLASS_HEAVY_CAVALRY'),
    ('BBG_ABILITY_MERCHANT_REPUBLIC_EMBARKED_MOVEMENT', 'CLASS_LANDCIVILIAN'),
    ('BBG_ABILITY_MERCHANT_REPUBLIC_EMBARKED_MOVEMENT', 'CLASS_LIGHT_CAVALRY'),
    ('BBG_ABILITY_MERCHANT_REPUBLIC_EMBARKED_MOVEMENT', 'CLASS_MELEE'),
    ('BBG_ABILITY_MERCHANT_REPUBLIC_EMBARKED_MOVEMENT', 'CLASS_RANGED'),
    ('BBG_ABILITY_MERCHANT_REPUBLIC_EMBARKED_MOVEMENT', 'CLASS_RECON'),
    ('BBG_ABILITY_MERCHANT_REPUBLIC_EMBARKED_MOVEMENT', 'CLASS_RELIGIOUS'),
    ('BBG_ABILITY_MERCHANT_REPUBLIC_EMBARKED_MOVEMENT', 'CLASS_SIEGE'),
    ('BBG_ABILITY_MERCHANT_REPUBLIC_EMBARKED_MOVEMENT', 'CLASS_WARRIOR_MONK'),
    ('BBG_ABILITY_MERCHANT_REPUBLIC_EMBARKED_MOVEMENT', 'CLASS_GIANT_DEATH_ROBOT'),
    ('BBG_ABILITY_MERCHANT_REPUBLIC_EMBARKED_MOVEMENT', 'CLASS_SUPPORT');


-- ==============================================================
-- ***                          THEOCRACY                     *** 
-- ============================================================== 

-- 15/10/23 Theocracy discount from 15 to 10%
-- 10/03/24 Reverted
-- UPDATE ModifierArguments SET Value=10 WHERE ModifierId='THEOCRACY_FAITH_PURCHASE' and Name='Amount';


-- ==============================================================
-- ***                          DEMOCRACY                     *** 
-- ============================================================== 

-- 17/12/25 intolerance to 0 for Demo and -20 for Fascism/Communism
UPDATE Governments SET OtherGovernmentIntolerance=0 WHERE GovernmentType='GOVERNMENT_DEMOCRACY';

-- 17/12/25 Democracy rework 
-- New Deal is now a Joker card.
UPDATE Policies SET GovernmentSlotType='SLOT_WILDCARD' WHERE PolicyType='POLICY_NEW_DEAL';
-- Their Finest Hour is deleted.
DELETE FROM Policies WHERE PolicyType='POLICY_FINEST_HOUR';

-- [NEW] Prosperity Pact Green Unique card : +2 alliance points/turn with allies. It's 1=0.25
-- Increased to +5
INSERT INTO Types(Type, Kind) VALUES
    ('POLICY_PROSPERITY_PACT', 'KIND_POLICY');
INSERT INTO Policies(PolicyType, Name, Description, PrereqCivic, GovernmentSlotType) VALUES
    ('POLICY_PROSPERITY_PACT', 'LOC_POLICY_PROSPERITY_PACT_NAME', 'LOC_POLICY_PROSPERITY_PACT_DESCRIPTION', 'CIVIC_SUFFRAGE', 'SLOT_DIPLOMATIC');
INSERT INTO PolicyModifiers(PolicyType, ModifierId) VALUES
    ('POLICY_PROSPERITY_PACT', 'BBG_PROSPERITY_PACT_ALLIANCE_POINTS');
INSERT INTO Modifiers(ModifierId, ModifierType) VALUES
    ('BBG_PROSPERITY_PACT_ALLIANCE_POINTS', 'MODIFIER_PLAYER_ADJUST_ALLIANCE_POINTS');
INSERT INTO ModifierArguments(ModifierId, Name, Value) VALUES
    ('BBG_PROSPERITY_PACT_ALLIANCE_POINTS', 'Amount', 20);
INSERT INTO Policy_GovernmentExclusives_XP2 (PolicyType, GovernmentType) VALUES
    ('POLICY_PROSPERITY_PACT', 'GOVERNMENT_DEMOCRACY');

-- Legacy Effect : Traderoute 
-- 16/03/26 Democracy yields from 4f/8g to 5f/2p/4g
--DELETE FROM GovernmentModifiers WHERE ModifierId IN ('DEMOCRACY_TRADEROUTEPRODUCTIONTOALLY', 'DEMOCRACY_TRADEROUTEPRODUCTIONFROMALLY', 'DEMOCRACY_TRADEROUTEPRODUCTIONTOSUZERAIN', 'DEMOCRACY_TRADEROUTEPRODUCTIONFROMSUZERAIN', 'DEMOCRACY_ALLIANCEPOINTS');
DELETE FROM GovernmentModifiers WHERE ModifierId='DEMOCRACY_ALLIANCEPOINTS';
UPDATE ModifierArguments SET Value=5 WHERE ModifierId='DEMOCRACY_TRADEROUTEFOODTOALLY' AND Name='Amount';
UPDATE ModifierArguments SET Value=5 WHERE ModifierId='DEMOCRACY_TRADEROUTEFOODFROMALLY' AND Name='Amount';
UPDATE ModifierArguments SET Value=5 WHERE ModifierId='DEMOCRACY_TRADEROUTEFOODTOSUZERAIN' AND Name='Amount';
UPDATE ModifierArguments SET Value=5 WHERE ModifierId='DEMOCRACY_TRADEROUTEFOODFROMSUZERAIN' AND Name='Amount';


UPDATE ModifierArguments SET Value=2 WHERE ModifierId='DEMOCRACY_TRADEROUTEPRODUCTIONTOALLY' AND Name='Amount';
UPDATE ModifierArguments SET Value=2 WHERE ModifierId='DEMOCRACY_TRADEROUTEPRODUCTIONFROMALLY' AND Name='Amount';
UPDATE ModifierArguments SET Value=2 WHERE ModifierId='DEMOCRACY_TRADEROUTEPRODUCTIONTOSUZERAIN' AND Name='Amount';
UPDATE ModifierArguments SET Value=2 WHERE ModifierId='DEMOCRACY_TRADEROUTEPRODUCTIONFROMSUZERAIN' AND Name='Amount';

INSERT INTO Modifiers(ModifierId, ModifierType) VALUES
    ('BBG_DEMOCRACY_TRADE_ROUTE_GOLD_TO_ALLY', 'MODIFIER_PLAYER_ADJUST_TRADE_ROUTE_DESTINATION_YIELD_FOR_ALLY_ROUTE'),
    ('BBG_DEMOCRACY_TRADE_ROUTE_GOLD_FROM_ALLY', 'MODIFIER_PLAYER_ADJUST_TRADE_ROUTE_ORIGIN_YIELD_FOR_ALLY_ROUTE'),
    ('BBG_DEMOCRACY_TRADE_ROUTE_GOLD_TO_SUZERAIN', 'MODIFIER_PLAYER_ADJUST_TRADE_ROUTE_DESTINATION_YIELD_FOR_SUZERAIN_ROUTE'),
    ('BBG_DEMOCRACY_TRADE_ROUTE_GOLD_FROM_SUZERAIN', 'MODIFIER_PLAYER_ADJUST_TRADE_ROUTE_ORIGIN_YIELD_FOR_SUZERAIN_ROUTE');
INSERT INTO ModifierArguments(ModifierId, Name, Value) VALUES
    ('BBG_DEMOCRACY_TRADE_ROUTE_GOLD_TO_ALLY', 'YieldType', 'YIELD_GOLD'),
    ('BBG_DEMOCRACY_TRADE_ROUTE_GOLD_TO_ALLY', 'Amount', 4),
    ('BBG_DEMOCRACY_TRADE_ROUTE_GOLD_FROM_ALLY', 'YieldType', 'YIELD_GOLD'),
    ('BBG_DEMOCRACY_TRADE_ROUTE_GOLD_FROM_ALLY', 'Amount', 4),
    ('BBG_DEMOCRACY_TRADE_ROUTE_GOLD_TO_SUZERAIN', 'YieldType', 'YIELD_GOLD'),
    ('BBG_DEMOCRACY_TRADE_ROUTE_GOLD_TO_SUZERAIN', 'Amount', 4),
    ('BBG_DEMOCRACY_TRADE_ROUTE_GOLD_FROM_SUZERAIN', 'YieldType', 'YIELD_GOLD'),
    ('BBG_DEMOCRACY_TRADE_ROUTE_GOLD_FROM_SUZERAIN', 'Amount', 4);
INSERT INTO GovernmentModifiers (GovernmentType, ModifierId) VALUES
    ('GOVERNMENT_DEMOCRACY', 'BBG_DEMOCRACY_TRADE_ROUTE_GOLD_TO_ALLY'),
    ('GOVERNMENT_DEMOCRACY', 'BBG_DEMOCRACY_TRADE_ROUTE_GOLD_FROM_ALLY'),
    ('GOVERNMENT_DEMOCRACY', 'BBG_DEMOCRACY_TRADE_ROUTE_GOLD_TO_SUZERAIN'),
    ('GOVERNMENT_DEMOCRACY', 'BBG_DEMOCRACY_TRADE_ROUTE_GOLD_FROM_SUZERAIN');

DELETE FROM PolicyModifiers WHERE ModifierId IN ('DEMOCRACY_ALLIANCEPOINTS');
INSERT INTO PolicyModifiers (PolicyType, ModifierId) VALUES
    ('POLICY_GOV_DEMOCRACY', 'BBG_DEMOCRACY_TRADE_ROUTE_GOLD_TO_ALLY'),
    ('POLICY_GOV_DEMOCRACY', 'BBG_DEMOCRACY_TRADE_ROUTE_GOLD_FROM_ALLY'),
    ('POLICY_GOV_DEMOCRACY', 'BBG_DEMOCRACY_TRADE_ROUTE_GOLD_TO_SUZERAIN'),
    ('POLICY_GOV_DEMOCRACY', 'BBG_DEMOCRACY_TRADE_ROUTE_GOLD_FROM_SUZERAIN');

-- Government bonus : 15% discount on gold buy.
-- 18/01/26 +8 amenity grant +4% faith/gold/culture (for now 8 amenity is HAPPINESS_UNHAPPY because Firaxis have to hardcode everything and flemme to do lua)
INSERT INTO Modifiers (ModifierId, ModifierType) VALUES
    ('BBG_DEMOCRACY_EMPIRE_EUPHORIC_CULTURE', 'MODIFIER_PLAYER_CITIES_ADJUST_HAPPINESS_YIELD'),
    ('BBG_DEMOCRACY_EMPIRE_EUPHORIC_GOLD', 'MODIFIER_PLAYER_CITIES_ADJUST_HAPPINESS_YIELD'),
    ('BBG_DEMOCRACY_EMPIRE_EUPHORIC_FAITH', 'MODIFIER_PLAYER_CITIES_ADJUST_HAPPINESS_YIELD');
INSERT INTO ModifierArguments (ModifierId, Name, Value) VALUES
    ('BBG_DEMOCRACY_EMPIRE_EUPHORIC_CULTURE', 'HappinessType', 'HAPPINESS_UNHAPPY'),
    ('BBG_DEMOCRACY_EMPIRE_EUPHORIC_CULTURE', 'YieldType', 'YIELD_CULTURE'),
    ('BBG_DEMOCRACY_EMPIRE_EUPHORIC_CULTURE', 'Amount', 4),
    ('BBG_DEMOCRACY_EMPIRE_EUPHORIC_GOLD', 'HappinessType', 'HAPPINESS_UNHAPPY'),
    ('BBG_DEMOCRACY_EMPIRE_EUPHORIC_GOLD', 'YieldType', 'YIELD_GOLD'),
    ('BBG_DEMOCRACY_EMPIRE_EUPHORIC_GOLD', 'Amount', 4),
    ('BBG_DEMOCRACY_EMPIRE_EUPHORIC_FAITH', 'HappinessType', 'HAPPINESS_UNHAPPY'),
    ('BBG_DEMOCRACY_EMPIRE_EUPHORIC_FAITH', 'YieldType', 'YIELD_FAITH'),
    ('BBG_DEMOCRACY_EMPIRE_EUPHORIC_FAITH', 'Amount', 4);

INSERT INTO GovernmentModifiers (GovernmentType, ModifierId) VALUES
    ('GOVERNMENT_DEMOCRACY', 'BBG_DEMOCRACY_EMPIRE_EUPHORIC_CULTURE'),
    ('GOVERNMENT_DEMOCRACY', 'BBG_DEMOCRACY_EMPIRE_EUPHORIC_GOLD'),
    ('GOVERNMENT_DEMOCRACY', 'BBG_DEMOCRACY_EMPIRE_EUPHORIC_FAITH');

-- ==============================================================
-- ***                          FASCISM                       *** 
-- ============================================================== 

-- 17/12/25 intolerance to 0 for Demo and -20 for Fascism/Communism
UPDATE Governments SET OtherGovernmentIntolerance=-30 WHERE GovernmentType='GOVERNMENT_FASCISM';

-- fascism attack bonus works on defense now too
UPDATE Modifiers SET SubjectRequirementSetId=NULL WHERE ModifierId='FASCISM_ATTACK_BUFF';
UPDATE Modifiers SET SubjectRequirementSetId=NULL WHERE ModifierId='FASCISM_LEGACY_ATTACK_BUFF';

-- Facism rework
-- Martial Law (Joker Card) : War weariness reduction increased to 50% (from 25) and cities with garrisoned units get +10 loyalty per turn (from 4)
UPDATE ModifierArguments SET Value=50 WHERE ModifierId='MARTIALLAW_OVERALLWARWEARINESS' AND Name='Amount';
UPDATE ModifierArguments SET Value=10 WHERE ModifierId='MARTIALLAW_GARRISONIDENTITY' AND Name='Amount';
-- Legacy Effect : +5 Combat Strength outside of your home territory (from everywhere). (removed war weariness reduction)
DELETE FROM GovernmentModifiers WHERE ModifierId='FASCISM_WAR_WEARINESS';
DELETE FROM PolicyModifiers WHERE ModifierId='FASCISM_WAR_WEARINESS';

INSERT INTO RequirementSets (RequirementSetId, RequirementSetType) VALUES
    ('BBG_UNIT_NOT_IN_TERRITORY_REQSET', 'REQUIREMENTSET_TEST_ALL');
INSERT INTO RequirementSetRequirements (RequirementSetId, RequirementId) VALUES
    ('BBG_UNIT_NOT_IN_TERRITORY_REQSET', 'REQUIRES_UNIT_NOT_IN_OWNER_TERRITORY');
-- 17/03/26 Facism combat bonus only apply outside of your territory ONLY for legacy.
UPDATE Modifiers SET SubjectRequirementSetId='BBG_UNIT_NOT_IN_TERRITORY_REQSET' WHERE ModifierId IN ('FASCISM_LEGACY_ATTACK_BUFF');
-- Government bonus : +50% Production on units. (no change)
-- Third Alternative (Red) : no change. 
-- 14/07/26 Third Alternative : Add Seaport
INSERT INTO Modifiers(ModifierId, ModifierType) VALUES
    ('BBG_THIRDALTERNATIVE_SEAPORT_GOLD_MODIFIER', 'MODIFIER_PLAYER_CITIES_ADJUST_BUILDING_YIELD_CHANGE'),
    ('BBG_THIRDALTERNATIVE_SEAPORT_CULTURE_MODIFIER', 'MODIFIER_PLAYER_CITIES_ADJUST_BUILDING_YIELD_CHANGE');

INSERT INTO ModifierArguments(ModifierId, Name, Value) VALUES
    ('BBG_THIRDALTERNATIVE_SEAPORT_GOLD_MODIFIER', 'YieldType', 'YIELD_GOLD'),
    ('BBG_THIRDALTERNATIVE_SEAPORT_GOLD_MODIFIER', 'Amount', 4),
    ('BBG_THIRDALTERNATIVE_SEAPORT_GOLD_MODIFIER', 'BuildingType', 'BUILDING_SEAPORT'),
    ('BBG_THIRDALTERNATIVE_SEAPORT_CULTURE_MODIFIER', 'YieldType', 'YIELD_CULTURE'),
    ('BBG_THIRDALTERNATIVE_SEAPORT_CULTURE_MODIFIER', 'Amount', 2),
    ('BBG_THIRDALTERNATIVE_SEAPORT_CULTURE_MODIFIER', 'BuildingType', 'BUILDING_SEAPORT');

INSERT INTO PolicyModifiers(PolicyType, ModifierId) VALUES
    ('POLICY_THIRD_ALTERNATIVE', 'BBG_THIRDALTERNATIVE_SEAPORT_GOLD_MODIFIER'),
    ('POLICY_THIRD_ALTERNATIVE', 'BBG_THIRDALTERNATIVE_SEAPORT_CULTURE_MODIFIER');


-- ==============================================================
-- ***                          COMMUNISM                     *** 
-- ============================================================== 

-- 17/12/25 intolerance to 0 for Demo and -20 for Fascism/Communism
UPDATE Governments SET OtherGovernmentIntolerance=-30 WHERE GovernmentType='GOVERNMENT_COMMUNISM';

-- 11/12/22 Communism -1 red card +1 yellow card
-- 15/12/24 -1 yellow +1 wildcard
UPDATE Government_SlotCounts SET NumSlots=2 WHERE GovernmentType='GOVERNMENT_COMMUNISM' AND GovernmentSlotType='SLOT_MILITARY';
-- UPDATE Government_SlotCounts SET NumSlots=4 WHERE GovernmentType='GOVERNMENT_COMMUNISM' AND GovernmentSlotType='SLOT_ECONOMIC';
UPDATE Government_SlotCounts SET NumSlots=2 WHERE GovernmentType='GOVERNMENT_COMMUNISM' AND GovernmentSlotType='SLOT_WILDCARD';

-- Communism rework 
-- 17/03/26 Revert legacy bonus
-- DELETE FROM PolicyModifiers WHERE ModifierId='COMMUNISM_PRODUCTIVE_PEOPLE' AND PolicyType='POLICY_GOV_COMMUNISM';
-- 27/03/26 Legacy effect increased to 1prod (from 0.6) per population
UPDATE ModifierArguments SET Value='1' WHERE ModifierId='COMMUNISM_PRODUCTIVE_PEOPLE' AND Name='Amount';

DELETE FROM GovernmentModifiers WHERE ModifierId='COMMUNISM_SCIENCE' AND GovernmentType='GOVERNMENT_COMMUNISM';
DELETE FROM Policy_GovernmentExclusives_XP2 WHERE PolicyType='POLICY_COLLECTIVIZATION';
-- Communism : Scientific Vanguard Joker Card : Cities with Governor receive 10% Science and Production but also -2 amenity.
--27/03/26 no amenity penalty
-- 10/08/26 Policy Scientific vanguard (10% prod/science in cities with a governor) removed
-- 10/08/26 new in Government effect : 10% science in cities with a Campus
-- INSERT INTO Types(Type, Kind) VALUES
--     ('POLICY_SCIENTIFIC_VANGUARD', 'KIND_POLICY');
-- INSERT INTO Policies(PolicyType, Name, Description, PrereqCivic, GovernmentSlotType) VALUES
--     ('POLICY_SCIENTIFIC_VANGUARD', 'LOC_POLICY_SCIENTIFIC_VANGUARD_NAME', 'LOC_POLICY_SCIENTIFIC_VANGUARD_DESCRIPTION', 'CIVIC_CLASS_STRUGGLE', 'SLOT_WILDCARD');
-- INSERT INTO Modifiers (ModifierId, ModifierType, SubjectRequirementSetId) VALUES
--     ('BBG_COMMUNISM_SCIENCE_BONUS', 'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_MODIFIER', 'CITY_HAS_GOVERNOR'),
--     ('BBG_COMMUNISM_PRODUCTION_BONUS', 'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_MODIFIER', 'CITY_HAS_GOVERNOR');
-- --    ('BBG_COMMUNISM_AMENITY_BONUS', 'MODIFIER_PLAYER_CITIES_ADJUST_POLICY_AMENITY', 'CITY_HAS_GOVERNOR');
-- INSERT INTO ModifierArguments (ModifierId, Name, Value) VALUES
--     ('BBG_COMMUNISM_SCIENCE_BONUS', 'Amount', 10),
--     ('BBG_COMMUNISM_SCIENCE_BONUS', 'YieldType', 'YIELD_SCIENCE'),
--     ('BBG_COMMUNISM_PRODUCTION_BONUS', 'Amount', 10),
--     ('BBG_COMMUNISM_PRODUCTION_BONUS', 'YieldType', 'YIELD_PRODUCTION');
-- --    ('BBG_COMMUNISM_AMENITY_BONUS', 'Amount', -2);
-- INSERT INTO PolicyModifiers (PolicyType, ModifierId) VALUES
--     ('POLICY_SCIENTIFIC_VANGUARD', 'BBG_COMMUNISM_SCIENCE_BONUS'),
--     ('POLICY_SCIENTIFIC_VANGUARD', 'BBG_COMMUNISM_PRODUCTION_BONUS');
-- --    ('POLICY_SCIENTIFIC_VANGUARD', 'BBG_COMMUNISM_AMENITY_BONUS')
-- INSERT INTO Policy_GovernmentExclusives_XP2 (PolicyType, GovernmentType) VALUES
--     ('POLICY_SCIENTIFIC_VANGUARD', 'GOVERNMENT_COMMUNISM');

INSERT INTO Modifiers (ModifierId, ModifierType, SubjectRequirementSetId) VALUES
    ('BBG_COMMUNISM_SCIENCE_BONUS', 'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_MODIFIER', 'BBG_CITY_HAS_DISTRICT_CAMPUS');
INSERT INTO ModifierArguments (ModifierId, Name, Value) VALUES
    ('BBG_COMMUNISM_SCIENCE_BONUS', 'Amount', 10),
    ('BBG_COMMUNISM_SCIENCE_BONUS', 'YieldType', 'YIELD_SCIENCE');
INSERT INTO GovernmentModifiers (GovernmentType, ModifierId) VALUES
    ('GOVERNMENT_COMMUNISM', 'BBG_COMMUNISM_SCIENCE_BONUS');



-- Kolkhoz  Yellow Card : +3 Production and +3 Food for IZ and Campus.
INSERT INTO Types(Type, Kind) VALUES
    ('POLICY_KOLKHOZ', 'KIND_POLICY');
--27/03/26 Kolkoz is a red card
INSERT INTO Policies(PolicyType, Name, Description, PrereqCivic, GovernmentSlotType) VALUES
    ('POLICY_KOLKHOZ', 'LOC_POLICY_KOLKHOZ_NAME', 'LOC_POLICY_KOLKHOZ_DESCRIPTION', 'CIVIC_CLASS_STRUGGLE', 'SLOT_MILITARY');
INSERT INTO Modifiers (ModifierId, ModifierType, SubjectRequirementSetId) VALUES
    ('BBG_KOLKHOZ_FOOD_IZ', 'MODIFIER_PLAYER_DISTRICTS_ADJUST_YIELD_CHANGE', 'DISTRICT_IS_INDUSTRIAL_ZONE'),
    ('BBG_KOLKHOZ_PROD_IZ', 'MODIFIER_PLAYER_DISTRICTS_ADJUST_YIELD_CHANGE', 'DISTRICT_IS_INDUSTRIAL_ZONE'),
    ('BBG_KOLKHOZ_FOOD_CAMPUS', 'MODIFIER_PLAYER_DISTRICTS_ADJUST_YIELD_CHANGE', 'DISTRICT_IS_CAMPUS'),
    ('BBG_KOLKHOZ_PROD_CAMPUS', 'MODIFIER_PLAYER_DISTRICTS_ADJUST_YIELD_CHANGE', 'DISTRICT_IS_CAMPUS');
INSERT INTO ModifierArguments (ModifierId, Name, Value) VALUES
    ('BBG_KOLKHOZ_FOOD_IZ', 'Amount', 2),
    ('BBG_KOLKHOZ_FOOD_IZ', 'YieldType', 'YIELD_FOOD'),
    ('BBG_KOLKHOZ_PROD_IZ', 'Amount', 2),
    ('BBG_KOLKHOZ_PROD_IZ', 'YieldType', 'YIELD_PRODUCTION'),
    ('BBG_KOLKHOZ_FOOD_CAMPUS', 'Amount', 2),
    ('BBG_KOLKHOZ_FOOD_CAMPUS', 'YieldType', 'YIELD_FOOD'),
    ('BBG_KOLKHOZ_PROD_CAMPUS', 'Amount', 2),
    ('BBG_KOLKHOZ_PROD_CAMPUS', 'YieldType', 'YIELD_PRODUCTION');
INSERT INTO PolicyModifiers (PolicyType, ModifierId) VALUES
    ('POLICY_KOLKHOZ', 'BBG_KOLKHOZ_FOOD_IZ'),
    ('POLICY_KOLKHOZ', 'BBG_KOLKHOZ_PROD_IZ'),
    ('POLICY_KOLKHOZ', 'BBG_KOLKHOZ_FOOD_CAMPUS'),
    ('POLICY_KOLKHOZ', 'BBG_KOLKHOZ_PROD_CAMPUS');
INSERT INTO Policy_GovernmentExclusives_XP2 (PolicyType, GovernmentType) VALUES
    ('POLICY_KOLKHOZ', 'GOVERNMENT_COMMUNISM');

-- Legacy Effect : +5 combat strength inside or adjacent to territory 
-- 17/03/26 Reverted : communism no longer give combat bonus

-- INSERT INTO RequirementSets(RequirementSetId, RequirementSetType) VALUES
--     ('BBG_COMMUNISM_LAND_OR_ADJACENT_TO_HOME_TERRITORY_REQSET', 'REQUIREMENTSET_TEST_ANY');
-- INSERT INTO RequirementSetRequirements(RequirementSetId, RequirementId) VALUES
--     ('BBG_COMMUNISM_LAND_OR_ADJACENT_TO_HOME_TERRITORY_REQSET', 'UNIT_IN_OWNER_TERRITORY_REQUIREMENT');

-- INSERT INTO Modifiers(ModifierId, ModifierType, OwnerRequirementSetId) VALUES
--     ('BBG_COMMUNISM_COMBAT_STRENGTH_GIVER', 'MODIFIER_PLAYER_UNITS_GRANT_ABILITY', NULL),
--     ('BBG_COMMUNISM_COMBAT_STRENGTH_MODIFIER', 'MODIFIER_UNIT_ADJUST_COMBAT_STRENGTH', 'BBG_COMMUNISM_LAND_OR_ADJACENT_TO_HOME_TERRITORY_REQSET');
-- INSERT INTO ModifierArguments(ModifierId, Name, Value) VALUES
--     ('BBG_COMMUNISM_COMBAT_STRENGTH_GIVER', 'AbilityType', 'BBG_COMMUNISM_COMBAT_STRENGTH_ABILITY'),
--     ('BBG_COMMUNISM_COMBAT_STRENGTH_MODIFIER', 'Amount', 4);

-- INSERT INTO ModifierStrings(ModifierId, Context, Text) VALUES
--     ('BBG_COMMUNISM_COMBAT_STRENGTH_MODIFIER', 'Preview', 'LOC_BBG_COMMUNISM_COMBAT_STRENGTH_ABILITY_DESC');

-- INSERT INTO Types(Type, Kind) VALUES
--     ('BBG_COMMUNISM_COMBAT_STRENGTH_ABILITY', 'KIND_ABILITY');
-- INSERT INTO TypeTags(Type, Tag) VALUES
--     ('BBG_COMMUNISM_COMBAT_STRENGTH_ABILITY', 'CLASS_ALL_COMBAT_UNITS');
-- INSERT INTO UnitAbilities(UnitAbilityType, Name, Description, Inactive) VALUES
--     ('BBG_COMMUNISM_COMBAT_STRENGTH_ABILITY', 'LOC_BBG_COMMUNISM_COMBAT_STRENGTH_ABILITY_NAME', 'LOC_BBG_COMMUNISM_COMBAT_STRENGTH_ABILITY_DESC', 1);
-- INSERT INTO UnitAbilityModifiers(UnitAbilityType, ModifierId) VALUES
--     ('BBG_COMMUNISM_COMBAT_STRENGTH_ABILITY', 'BBG_COMMUNISM_COMBAT_STRENGTH_MODIFIER');
-- INSERT INTO GovernmentModifiers(GovernmentType, ModifierId) VALUES
--     ('GOVERNMENT_COMMUNISM', 'BBG_COMMUNISM_COMBAT_STRENGTH_GIVER');

-- Legacy 
-- 17/03/26 Reverted : communism get back vanilla legacy bonus
-- DELETE FROM PolicyModifiers WHERE PolicyType='POLICY_GOV_COMMUNISM';

-- INSERT INTO Modifiers(ModifierId, ModifierType, OwnerRequirementSetId) VALUES
--     ('BBG_COMMUNISM_LEGACY_COMBAT_STRENGTH_GIVER', 'MODIFIER_PLAYER_UNITS_GRANT_ABILITY', NULL),
--     ('BBG_COMMUNISM_LEGACY_COMBAT_STRENGTH_MODIFIER', 'MODIFIER_UNIT_ADJUST_COMBAT_STRENGTH', 'BBG_COMMUNISM_LAND_OR_ADJACENT_TO_HOME_TERRITORY_REQSET');
-- INSERT INTO ModifierArguments(ModifierId, Name, Value) VALUES
--     ('BBG_COMMUNISM_LEGACY_COMBAT_STRENGTH_GIVER', 'AbilityType', 'BBG_COMMUNISM_LEGACY_COMBAT_STRENGTH_ABILITY'),
--     ('BBG_COMMUNISM_LEGACY_COMBAT_STRENGTH_MODIFIER', 'Amount', 5);

-- INSERT INTO ModifierStrings(ModifierId, Context, Text) VALUES
--     ('BBG_COMMUNISM_LEGACY_COMBAT_STRENGTH_MODIFIER', 'Preview', 'LOC_BBG_COMMUNISM_LEGACY_COMBAT_STRENGTH_ABILITY_DESC');

-- INSERT INTO Types(Type, Kind) VALUES
--     ('BBG_COMMUNISM_LEGACY_COMBAT_STRENGTH_ABILITY', 'KIND_ABILITY');
-- INSERT INTO TypeTags(Type, Tag) VALUES
--     ('BBG_COMMUNISM_LEGACY_COMBAT_STRENGTH_ABILITY', 'CLASS_ALL_COMBAT_UNITS');
-- INSERT INTO UnitAbilities(UnitAbilityType, Name, Description, Inactive) VALUES
--     ('BBG_COMMUNISM_LEGACY_COMBAT_STRENGTH_ABILITY', 'LOC_BBG_COMMUNISM_LEGACY_COMBAT_STRENGTH_ABILITY_NAME', 'LOC_BBG_COMMUNISM_LEGACY_COMBAT_STRENGTH_ABILITY_DESC', 1);
-- INSERT INTO UnitAbilityModifiers(UnitAbilityType, ModifierId) VALUES
--     ('BBG_COMMUNISM_LEGACY_COMBAT_STRENGTH_ABILITY', 'BBG_COMMUNISM_COMBAT_STRENGTH_MODIFIER');
-- INSERT INTO PolicyModifiers(PolicyType, ModifierId) VALUES
--     ('POLICY_GOV_COMMUNISM', 'BBG_COMMUNISM_LEGACY_COMBAT_STRENGTH_GIVER');

-- Government bonus : +.6 prod per citizen in cities with a governor.













