--==============================================================
--******			       CITY STATES      			  ******
--==============================================================

-- Ngazargamu legacy city-state is carthage
UPDATE ModifierArguments SET Value='10' WHERE ModifierId='MINOR_CIV_CARTHAGE_BARRACKS_STABLE_PURCHASE_BONUS';
UPDATE ModifierArguments SET Value='10' WHERE ModifierId='MINOR_CIV_CARTHAGE_ARMORY_PURCHASE_BONUS';
UPDATE ModifierArguments SET Value='10' WHERE ModifierId='MINOR_CIV_CARTHAGE_MILITARY_ACADEMY_PURCHASE_BONUS';

-- Lisbon pillage apply on land too
UPDATE ModifierArguments SET Value='ABILITY_ECONOMIC_GOLDEN_AGE_PLUNDER_IMMUNITY' WHERE ModifierId='MINOR_CIV_LISBON_SEA_TRADE_ROUTE_PLUNDER_IMMUNITY_BONUS' AND Name='AbilityType';

-- Nan madol nerf to +1 culture.
UPDATE ModifierArguments SET Value='1' WHERE ModifierId='MINOR_CIV_NAN_MADOL_DISTRICTS_CULTURE_BONUS' AND Name='Amount';
-- +1 culture once exploration reach
INSERT INTO TraitModifiers(TraitType, ModifierId) VALUES
    ('MINOR_CIV_NAN_MADOL_TRAIT', 'BBG_NAN_MADOL_UNIQUE_INFLUENCE_EXPLORATION_MODIFIER');

INSERT INTO Modifiers(ModifierId, ModifierType, SubjectRequirementSetId) VALUES
    ('BBG_NAN_MADOL_UNIQUE_INFLUENCE_EXPLORATION_MODIFIER', 'MODIFIER_ALL_PLAYERS_ATTACH_MODIFIER', 'BBG_NAN_MADOL_UNIQUE_INFLUENCE_EXPLORATION_REQUIREMENTS'),
    ('BBG_NAN_MADOL_EXPLORATION_BONUS_MODIFIER', 'MODIFIER_PLAYER_DISTRICTS_ADJUST_YIELD_CHANGE', 'SPECIAL_DISTRICT_ON_COAST_BBG');

INSERT INTO ModifierArguments(ModifierId, Name, Value) VALUES
    ('BBG_NAN_MADOL_UNIQUE_INFLUENCE_EXPLORATION_MODIFIER', 'ModifierId', 'BBG_NAN_MADOL_EXPLORATION_BONUS_MODIFIER'),
    ('BBG_NAN_MADOL_EXPLORATION_BONUS_MODIFIER', 'YieldType', 'YIELD_CULTURE'),
    ('BBG_NAN_MADOL_EXPLORATION_BONUS_MODIFIER', 'Amount', '1');

INSERT INTO RequirementSets('RequirementSetId', 'RequirementSetType') VALUES
    ('BBG_NAN_MADOL_UNIQUE_INFLUENCE_EXPLORATION_REQUIREMENTS', 'REQUIREMENTSET_TEST_ALL');

INSERT INTO RequirementSetRequirements(RequirementSetId, RequirementId) VALUES
    ('BBG_NAN_MADOL_UNIQUE_INFLUENCE_EXPLORATION_REQUIREMENTS', 'REQUIRES_PLAYER_IS_SUZERAIN'),
    ('BBG_NAN_MADOL_UNIQUE_INFLUENCE_EXPLORATION_REQUIREMENTS', 'BBG_PLAYER_HAS_EXPLORATION_CIVIC');

INSERT INTO Requirements(RequirementId, RequirementType) VALUES
    ('BBG_PLAYER_HAS_EXPLORATION_CIVIC', 'REQUIREMENT_PLAYER_HAS_CIVIC');

INSERT INTO RequirementArguments(RequirementId, Name, Value) VALUES
    ('BBG_PLAYER_HAS_EXPLORATION_CIVIC', 'CivicType', 'CIVIC_EXPLORATION');
