-- ====Summer====--
-- moved from base because alliance levels didn't exist
-- 16/05/2021: +1 military power per alliance level (on better alliance)
-- 30/11/24 Removed 
-- 15/12/24 reverted
INSERT INTO Modifiers(ModifierId, ModifierType, OwnerRequirementSetId, SubjectRequirementSetId) VALUES
    ('BBG_SUMMER_COMBAT_ALLY_1', 'MODIFIER_PLAYER_UNITS_ADJUST_COMBAT_STRENGTH', 'BBG_PLAYER_IS_ALLY_EXCLUSIVE_LEVEL_1', NULL),
    ('BBG_SUMMER_COMBAT_ALLY_2', 'MODIFIER_PLAYER_UNITS_ADJUST_COMBAT_STRENGTH', 'BBG_PLAYER_IS_ALLY_EXCLUSIVE_LEVEL_2', NULL),
    ('BBG_SUMMER_COMBAT_ALLY_3', 'MODIFIER_PLAYER_UNITS_ADJUST_COMBAT_STRENGTH', 'BBG_PLAYER_IS_ALLY_EXCLUSIVE_LEVEL_3', NULL);

INSERT INTO ModifierArguments(ModifierId, Name, Value) VALUES
    ('BBG_SUMMER_COMBAT_ALLY_1', 'Amount', 1),
    ('BBG_SUMMER_COMBAT_ALLY_2', 'Amount', 2),
    ('BBG_SUMMER_COMBAT_ALLY_3', 'Amount', 3);

INSERT INTO ModifierStrings(ModifierId, Context, Text) VALUES
    ('BBG_SUMMER_COMBAT_ALLY_1', 'Preview', 'LOC_BBG_SUMMER_COMBAT_ALLY_1'),
    ('BBG_SUMMER_COMBAT_ALLY_2', 'Preview', 'LOC_BBG_SUMMER_COMBAT_ALLY_2'),
    ('BBG_SUMMER_COMBAT_ALLY_3', 'Preview', 'LOC_BBG_SUMMER_COMBAT_ALLY_3');

INSERT INTO TraitModifiers(TraitType, ModifierId) VALUES
    ('TRAIT_LEADER_ADVENTURES_ENKIDU', 'BBG_SUMMER_COMBAT_ALLY_1'),
    ('TRAIT_LEADER_ADVENTURES_ENKIDU', 'BBG_SUMMER_COMBAT_ALLY_2'),
    ('TRAIT_LEADER_ADVENTURES_ENKIDU', 'BBG_SUMMER_COMBAT_ALLY_3');


