INSERT INTO WonderTerrainFeature_BBG(WonderType, TerrainClassType, FeatureType, Other) VALUES
	('FEATURE_FOUNTAIN_OF_YOUTH', NULL, 'FEATURE_OASIS', NULL),
	('FEATURE_BERMUDA_TRIANGLE', NULL, NULL, 'WATER'),
	('FEATURE_PAITITI', NULL, NULL, 'OTHER');