
-- Kublai +1 Science +1 Culture per international traderoute.
INSERT INTO Modifiers(ModifierId, ModifierType) VALUES
    ('BBG_KUBLAI_INTERNATIONAL_SCIENCE', 'MODIFIER_PLAYER_ADJUST_TRADE_ROUTE_YIELD_FOR_INTERNATIONAL'),
    ('BBG_KUBLAI_INTERNATIONAL_CULTURE', 'MODIFIER_PLAYER_ADJUST_TRADE_ROUTE_YIELD_FOR_INTERNATIONAL');

INSERT INTO ModifierArguments(ModifierId, Name, Value) VALUES
    ('BBG_KUBLAI_INTERNATIONAL_SCIENCE', 'Amount', '1'),
    ('BBG_KUBLAI_INTERNATIONAL_SCIENCE', 'YieldType', 'YIELD_SCIENCE'),
    ('BBG_KUBLAI_INTERNATIONAL_CULTURE', 'Amount', '1'),
    ('BBG_KUBLAI_INTERNATIONAL_CULTURE', 'YieldType', 'YIELD_CULTURE');

INSERT INTO TraitModifiers(TraitType, ModifierId) VALUES
    ('TRAIT_LEADER_KUBLAI', 'BBG_KUBLAI_INTERNATIONAL_SCIENCE'),
    ('TRAIT_LEADER_KUBLAI', 'BBG_KUBLAI_INTERNATIONAL_CULTURE');