-- Add GrandComandante mouvement point
--15/12/22 reverted
-- INSERT OR IGNORE INTO GreatPersonIndividualBirthModifiers(GreatPersonIndividualType, ModifierId) VALUES
--     ('GREAT_PERSON_INDIVIDUAL_COMMANDANTE_JOSE_DE_SUCRE', 'GREATPERSON_COMANDANTE_MOVEMENT_AOE_LAND'),
--     ('GREAT_PERSON_INDIVIDUAL_COMMANDANTE_PAULA_SANTANDER', 'GREATPERSON_COMANDANTE_MOVEMENT_AOE_LAND'),
--     ('GREAT_PERSON_INDIVIDUAL_COMMANDANTE_ANTONIO_PAEZ', 'GREATPERSON_COMANDANTE_MOVEMENT_AOE_LAND'),
--     ('GREAT_PERSON_INDIVIDUAL_COMMANDANTE_URDANETA', 'GREATPERSON_COMANDANTE_MOVEMENT_AOE_LAND'),
--     ('GREAT_PERSON_INDIVIDUAL_COMMANDANTE_MARINO', 'GREATPERSON_COMANDANTE_MOVEMENT_AOE_LAND'),
--     ('GREAT_PERSON_INDIVIDUAL_COMMANDANTE_MACGREGOR', 'GREATPERSON_COMANDANTE_MOVEMENT_AOE_LAND'),
--     ('GREAT_PERSON_INDIVIDUAL_COMMANDANTE_PIAR', 'GREATPERSON_COMANDANTE_MOVEMENT_AOE_LAND'),
--     ('GREAT_PERSON_INDIVIDUAL_COMMANDANTE_NARINO', 'GREATPERSON_COMANDANTE_MOVEMENT_AOE_LAND'),
--     ('GREAT_PERSON_INDIVIDUAL_COMMANDANTE_MONTILLA', 'GREATPERSON_COMANDANTE_MOVEMENT_AOE_LAND'),
--     ('GREAT_PERSON_INDIVIDUAL_COMMANDANTE_RIBAS', 'GREATPERSON_COMANDANTE_MOVEMENT_AOE_LAND');

--Simon's Plantation Bias With Olives
INSERT OR IGNORE INTO StartBiasResources(CivilizationType, ResourceType, Tier) VALUES
    ('CIVILIZATION_GRAN_COLOMBIA', 'RESOURCE_OLIVES', 5);
--Maya's Plantation Bias with Olives
INSERT OR IGNORE INTO StartBiasResources(CivilizationType, ResourceType, Tier) VALUES
    ('CIVILIZATION_MAYA', 'RESOURCE_OLIVES', 3);
