INSERT OR IGNORE INTO RequirementSetRequirements VALUES
    ('BUILDING_IS_BARRACKS_STABLE_MILITARITIC_CITY_STATE', 'REQUIRES_CITY_HAS_ORDU_BBG');
INSERT OR IGNORE INTO Requirements (RequirementId, RequirementType) VALUES
    ('REQUIRES_CITY_HAS_ORDU_BBG', 'REQUIREMENT_CITY_HAS_BUILDING');
INSERT OR IGNORE INTO RequirementArguments (RequirementId, Name, Value) VALUES
    ('REQUIRES_CITY_HAS_ORDU_BBG', 'BuildingType', 'BUILDING_ORDU');

-- Add GrandComandante mouvement point
--15/12/22 reverted
-- INSERT OR IGNORE INTO GreatPersonIndividualBirthModifiers(GreatPersonIndividualType, ModifierId) VALUES
--     ('GREAT_PERSON_INDIVIDUAL_COMMANDANTE_JOSE_DE_SUCRE', 'GREATPERSON_COMANDANTE_MOVEMENT_AOE_LAND'),
--     ('GREAT_PERSON_INDIVIDUAL_COMMANDANTE_PAULA_SANTANDER', 'GREATPERSON_COMANDANTE_MOVEMENT_AOE_LAND'),
--     ('GREAT_PERSON_INDIVIDUAL_COMMANDANTE_ANTONIO_PAEZ', 'GREATPERSON_COMANDANTE_MOVEMENT_AOE_LAND'),
--     ('GREAT_PERSON_INDIVIDUAL_COMMANDANTE_URDANETA', 'GREATPERSON_COMANDANTE_MOVEMENT_AOE_LAND'),
--     ('GREAT_PERSON_INDIVIDUAL_COMMANDANTE_MARINO', 'GREATPERSON_COMANDANTE_MOVEMENT_AOE_LAND'),
--     ('GREAT_PERSON_INDIVIDUAL_COMMANDANTE_MACGREGOR', 'GREATPERSON_COMANDANTE_MOVEMENT_AOE_LAND'),
--     ('GREAT_PERSON_INDIVIDUAL_COMMANDANTE_PIAR', 'GREATPERSON_COMANDANTE_MOVEMENT_AOE_LAND'),
--     ('GREAT_PERSON_INDIVIDUAL_COMMANDANTE_NARINO', 'GREATPERSON_COMANDANTE_MOVEMENT_AOE_LAND'),
--     ('GREAT_PERSON_INDIVIDUAL_COMMANDANTE_MONTILLA', 'GREATPERSON_COMANDANTE_MOVEMENT_AOE_LAND'),
--     ('GREAT_PERSON_INDIVIDUAL_COMMANDANTE_RIBAS', 'GREATPERSON_COMANDANTE_MOVEMENT_AOE_LAND');
