INSERT INTO WonderTerrainFeature_BBG(WonderType, TerrainClassType, FeatureType, Other) VALUES
	('FEATURE_RORAIMA', 'TERRAIN_CLASS_MOUNTAIN', NULL, NULL),
	('FEATURE_MATTERHORN', 'TERRAIN_CLASS_MOUNTAIN', NULL, NULL),
	('FEATURE_ZHANGYE_DANXIA', 'TERRAIN_CLASS_MOUNTAIN', NULL, NULL),
	('FEATURE_LAKE_RETBA', NULL, NULL, 'LAKE'),
	('FEATURE_UBSUNUR_HOLLOW', NULL, 'FEATURE_MARSH', NULL),
	('FEATURE_DELICATE_ARCH', 'TERRAIN_CLASS_DESERT', NULL, NULL),
	('FEATURE_EYE_OF_THE_SAHARA', 'TERRAIN_CLASS_DESERT', NULL, NULL);
