--communism 5.2. This didn't exist in base
UPDATE ModifierArguments SET Value=1 WHERE ModifierId='COMMUNISM_PRODUCTIVE_PEOPLE' and Name="Amount";

--5.2.5 buff autocracy (extend bonus to plaza/diplo quarter district AND diplo quarter buildings) -- moved from base
INSERT INTO GovernmentModifiers (GovernmentType, ModifierId) VALUES
    ('GOVERNMENT_AUTOCRACY', 'AUTOCRACY_PLAZA_DISTRICT'),
    ('GOVERNMENT_AUTOCRACY', 'AUTOCRACY_DIPLOMATIC_DISTRICT');
INSERT INTO Modifiers (ModifierId, ModifierType, SubjectRequirementSetId) VALUES
    ('AUTOCRACY_PLAZA_DISTRICT', 'MODIFIER_PLAYER_CITIES_ADJUST_CITY_ALL_YIELDS_CHANGE', 'CITY_HAS_GOV_DISTRICT_BBG_REQSET'),
    ('AUTOCRACY_DIPLOMATIC_DISTRICT', 'MODIFIER_PLAYER_CITIES_ADJUST_CITY_ALL_YIELDS_CHANGE', 'CITY_HAS_DIPLOMATIC_DISTRICT_BBG_REQSET');
INSERT INTO ModifierArguments (ModifierId, Name, Value) VALUES
    ('AUTOCRACY_PLAZA_DISTRICT', 'Amount', '1'),
    ('AUTOCRACY_DIPLOMATIC_DISTRICT', 'Amount', '1');
INSERT INTO RequirementSets (RequirementSetId, RequirementSetType) VALUES
    ('CITY_HAS_DIPLOMATIC_DISTRICT_BBG_REQSET', 'REQUIREMENTSET_TEST_ALL'),
    ('CITY_HAS_GOV_DISTRICT_BBG_REQSET', 'REQUIREMENTSET_TEST_ALL');
INSERT INTO RequirementSetRequirements (RequirementSetId, RequirementId) VALUES
    ('CITY_HAS_DIPLOMATIC_DISTRICT_BBG_REQSET', 'CITY_HAS_DIPLOMATIC_DISTRICT_BBG_REQ'),
    ('CITY_HAS_GOV_DISTRICT_BBG_REQSET', 'CITY_HAS_GOV_DISTRICT_BBG_REQ');
INSERT INTO Requirements (RequirementId, RequirementType) VALUES
    ('CITY_HAS_DIPLOMATIC_DISTRICT_BBG_REQ', 'REQUIREMENT_CITY_HAS_DISTRICT'),
    ('CITY_HAS_GOV_DISTRICT_BBG_REQ', 'REQUIREMENT_CITY_HAS_DISTRICT');
INSERT INTO RequirementArguments (RequirementId, Name, Value) VALUES
    ('CITY_HAS_DIPLOMATIC_DISTRICT_BBG_REQ', 'DistrictType', 'DISTRICT_DIPLOMATIC_QUARTER'),
    ('CITY_HAS_GOV_DISTRICT_BBG_REQ', 'DistrictType', 'DISTRICT_GOVERNMENT');