INSERT INTO WonderTerrainFeature_BBG(WonderType, TerrainClassType, FeatureType, Other) VALUES
	('FEATURE_DEVILSTOWER', NULL, NULL, 'OTHER'),
	('FEATURE_VESUVIUS', 'TERRAIN_CLASS_MOUNTAIN', 'FEATURE_VOLCANO', NULL),
	('FEATURE_IKKIL', NULL, NULL, 'OTHER'),
	('FEATURE_CHOCOLATEHILLS', NULL, NULL, 'HILLS'),
	('FEATURE_UBSUNUR_HOLLOW', NULL, 'FEATURE_MARSH', NULL),
	('FEATURE_PAMUKKALE', NULL, NULL, 'OTHER'),
	('FEATURE_WHITEDESERT', 'TERRAIN_CLASS_DESERT', NULL, NULL);