--===========================================================
--                     Policies
--===========================================================
-- fascism attack bonus working for GDR
INSERT OR IGNORE INTO TypeTags (Type, Tag) VALUES ('ABILITY_FASCISM_ATTACK_BUFF', 'CLASS_GIANT_DEATH_ROBOT');
INSERT OR IGNORE INTO TypeTags (Type, Tag) VALUES ('ABILITY_FASCISM_LEGACY_ATTACK_BUFF', 'CLASS_GIANT_DEATH_ROBOT');


-- 17/07/26 Upgrade card nerfed and multiples tiers, mercenaries 30%, natio 40%, ideo 50%
-- 10/08/26 40/45/50
INSERT INTO Types (Type, Kind) VALUES
    ('BBG_POLICY_MILITARY_STANDARDIZATION', 'KIND_POLICY');

UPDATE ModifierArguments SET Value=40 WHERE ModifierId='PROFESSIONAL_ARMY_UNITUPGRADEDISCOUNT' AND Name='Amount';

INSERT INTO Modifiers (ModifierId, ModifierType) VALUES
    ('BBG_UPGRADE_DISCOUNT_45', 'MODIFIER_PLAYER_ADJUST_UNIT_UPGRADE_DISCOUNT_PERCENT'),
    ('BBG_UPGRADE_DISCOUNT_50', 'MODIFIER_PLAYER_ADJUST_UNIT_UPGRADE_DISCOUNT_PERCENT');
INSERT INTO ModifierArguments (ModifierId, Name, Value) VALUES
    ('BBG_UPGRADE_DISCOUNT_45', 'Amount', 45),
    ('BBG_UPGRADE_DISCOUNT_50', 'Amount', 50);
UPDATE ObsoletePolicies SET ObsoletePolicy='BBG_POLICY_MILITARY_STANDARDIZATION' WHERE PolicyType='POLICY_PROFESSIONAL_ARMY';

-- 40% at natio Military Standadization
INSERT INTO Policies (PolicyType, Name, Description, PrereqCivic, GovernmentSlotType) VALUES
    ('BBG_POLICY_MILITARY_STANDARDIZATION', 'LOC_POLICY_MILITARY_STANDARDIZATION_NAME', 'LOC_POLICY_MILITARY_STANDARDIZATION_DESCRIPTION', 'CIVIC_NATIONALISM', 'SLOT_MILITARY');
INSERT INTO PolicyModifiers (PolicyType, ModifierId) VALUES
    ('BBG_POLICY_MILITARY_STANDARDIZATION', 'BBG_UPGRADE_DISCOUNT_45');
INSERT INTO ObsoletePolicies (PolicyType, ObsoletePolicy) VALUES
    ('BBG_POLICY_MILITARY_STANDARDIZATION', 'POLICY_FORCE_MODERNIZATION');

-- 50% at ideo
UPDATE Policies SET PrereqCivic='CIVIC_IDEOLOGY' WHERE PolicyType='POLICY_FORCE_MODERNIZATION';
UPDATE PolicyModifiers SET ModifierId='BBG_UPGRADE_DISCOUNT_50' WHERE PolicyType='POLICY_FORCE_MODERNIZATION' AND ModifierId='PROFESSIONAL_ARMY_UNITUPGRADEDISCOUNT';

-- retinues policy card is 50% of resource cost for produced and upgrade units
INSERT OR IGNORE INTO Modifiers (ModifierId, ModifierType)
    VALUES ('PROFESSIONAL_ARMY_RESOURCE_DISCOUNT_MODIFIER_CPLMOD', 'MODIFIER_CITY_ADJUST_STRATEGIC_RESOURCE_REQUIREMENT_MODIFIER');
INSERT OR IGNORE INTO ModifierArguments (ModifierId, Name, Value)
    VALUES ('PROFESSIONAL_ARMY_RESOURCE_DISCOUNT_MODIFIER_CPLMOD', 'Amount', '50');
INSERT OR IGNORE INTO Modifiers (ModifierId, ModifierType)
    VALUES ('PROFESSIONAL_ARMY_RESOURCE_DISCOUNT_CPLMOD', 'MODIFIER_PLAYER_CITIES_ATTACH_MODIFIER');
INSERT OR IGNORE INTO ModifierArguments (ModifierId, Name, Value)
    VALUES ('PROFESSIONAL_ARMY_RESOURCE_DISCOUNT_CPLMOD', 'ModifierId', 'PROFESSIONAL_ARMY_RESOURCE_DISCOUNT_MODIFIER_CPLMOD');
INSERT OR IGNORE INTO PolicyModifiers (PolicyType, ModifierId)
    VALUES
    ('POLICY_RETINUES', 'PROFESSIONAL_ARMY_RESOURCE_DISCOUNT_CPLMOD'),
    ('POLICY_FORCE_MODERNIZATION', 'PROFESSIONAL_ARMY_RESOURCE_DISCOUNT_CPLMOD');
-- get +1 resource when revealed (niter and above only)
-- Ressources cards give flat ressources in addition to 1 extra per mine.
INSERT INTO Modifiers(ModifierId, ModifierType, SubjectRequirementSetId) VALUES
    ('BBG_POLICY_GIVE_FREE_HORSE', 'MODIFIER_PLAYER_ADJUST_FREE_RESOURCE_IMPORT_EXTRACTION', 'BBG_PLAYER_CAN_SEE_RESOURCE_HORSES_REQSET'),
    ('BBG_POLICY_GIVE_FREE_IRON', 'MODIFIER_PLAYER_ADJUST_FREE_RESOURCE_IMPORT_EXTRACTION', 'BBG_PLAYER_CAN_SEE_RESOURCE_IRON_REQSET'),
    ('BBG_POLICY_GIVE_FREE_NITER', 'MODIFIER_PLAYER_ADJUST_FREE_RESOURCE_IMPORT_EXTRACTION', 'BBG_PLAYER_CAN_SEE_RESOURCE_NITER_REQSET'),
    ('BBG_POLICY_GIVE_FREE_COAL', 'MODIFIER_PLAYER_ADJUST_FREE_RESOURCE_IMPORT_EXTRACTION', 'BBG_PLAYER_CAN_SEE_RESOURCE_COAL_REQSET'),
    ('BBG_POLICY_GIVE_FREE_ALUMINUM', 'MODIFIER_PLAYER_ADJUST_FREE_RESOURCE_IMPORT_EXTRACTION', 'BBG_PLAYER_CAN_SEE_RESOURCE_ALUMINUM_REQSET'),
    ('BBG_POLICY_GIVE_FREE_OIL', 'MODIFIER_PLAYER_ADJUST_FREE_RESOURCE_IMPORT_EXTRACTION', 'BBG_PLAYER_CAN_SEE_RESOURCE_OIL_REQSET');
INSERT INTO ModifierArguments(ModifierId, Name, Value) VALUES
    ('BBG_POLICY_GIVE_FREE_HORSE', 'ResourceType', 'RESOURCE_HORSES'),
    ('BBG_POLICY_GIVE_FREE_HORSE', 'Amount', '2'),
    ('BBG_POLICY_GIVE_FREE_IRON', 'ResourceType', 'RESOURCE_IRON'),
    ('BBG_POLICY_GIVE_FREE_IRON', 'Amount', '2'),
    ('BBG_POLICY_GIVE_FREE_NITER', 'ResourceType', 'RESOURCE_NITER'),
    ('BBG_POLICY_GIVE_FREE_NITER', 'Amount', '2'),
    ('BBG_POLICY_GIVE_FREE_COAL', 'ResourceType', 'RESOURCE_COAL'),
    ('BBG_POLICY_GIVE_FREE_COAL', 'Amount', '2'),
    ('BBG_POLICY_GIVE_FREE_ALUMINUM', 'ResourceType', 'RESOURCE_ALUMINUM'),
    ('BBG_POLICY_GIVE_FREE_ALUMINUM', 'Amount', '2'),
    ('BBG_POLICY_GIVE_FREE_OIL', 'ResourceType', 'RESOURCE_OIL'),
    ('BBG_POLICY_GIVE_FREE_OIL', 'Amount', '2');
INSERT INTO PolicyModifiers(PolicyType, ModifierId) VALUES
    ('POLICY_EQUESTRIAN_ORDERS', 'BBG_POLICY_GIVE_FREE_HORSE'),
    ('POLICY_EQUESTRIAN_ORDERS', 'BBG_POLICY_GIVE_FREE_IRON'),
    ('POLICY_DRILL_MANUALS', 'BBG_POLICY_GIVE_FREE_NITER'),
    ('POLICY_DRILL_MANUALS', 'BBG_POLICY_GIVE_FREE_COAL'),
    ('POLICY_RESOURCE_MANAGEMENT', 'BBG_POLICY_GIVE_FREE_ALUMINUM'),
    ('POLICY_RESOURCE_MANAGEMENT', 'BBG_POLICY_GIVE_FREE_OIL');

-- 14/07/26 Resource Management : +2 production to all improved strategic resources
INSERT INTO Modifiers(ModifierId, ModifierType, SubjectRequirementSetId) VALUES
    ('BBG_RESOURCE_MANAGEMENT_IMPROVED_STRATEGIC_RESOURCE_PRODUCTION', 'MODIFIER_PLAYER_ADJUST_PLOT_YIELD', 'PLOT_HAS_STRATEGIC_IMPROVED_REQUIREMENTS');
INSERT INTO ModifierArguments(ModifierId, Name, Value) VALUES
    ('BBG_RESOURCE_MANAGEMENT_IMPROVED_STRATEGIC_RESOURCE_PRODUCTION', 'YieldType', 'YIELD_PRODUCTION'),
    ('BBG_RESOURCE_MANAGEMENT_IMPROVED_STRATEGIC_RESOURCE_PRODUCTION', 'Amount', '2');
INSERT INTO PolicyModifiers(PolicyType, ModifierId) VALUES
    ('POLICY_RESOURCE_MANAGEMENT', 'BBG_RESOURCE_MANAGEMENT_IMPROVED_STRATEGIC_RESOURCE_PRODUCTION');

-- 06/07/24 Fixed bug in the "Strategic Air Force" policy card.
-- Now boosts production for Atomic-era air fighters/bombers and modern-era air fighters.
INSERT INTO Modifiers(ModifierId, ModifierType) VALUES
    ('BBG_ATOMIC_AIRFIGHTER_PRODUCTION', 'MODIFIER_PLAYER_CITIES_ADJUST_UNIT_TAG_ERA_PRODUCTION'),
    ('BBG_ATOMIC_AIRBOMBER_PRODUCTION', 'MODIFIER_PLAYER_CITIES_ADJUST_UNIT_TAG_ERA_PRODUCTION'),
    ('BBG_MODERN_AIRFIGHTER_PRODUCTION', 'MODIFIER_PLAYER_CITIES_ADJUST_UNIT_TAG_ERA_PRODUCTION');
INSERT INTO ModifierArguments(ModifierId, Name, Value) VALUES
    ('BBG_ATOMIC_AIRFIGHTER_PRODUCTION', 'UnitPromotionClass', 'PROMOTION_CLASS_AIR_FIGHTER'),
    ('BBG_ATOMIC_AIRFIGHTER_PRODUCTION', 'EraType', 'ERA_ATOMIC'),
    ('BBG_ATOMIC_AIRFIGHTER_PRODUCTION', 'Amount', '50'),
    ('BBG_ATOMIC_AIRBOMBER_PRODUCTION', 'UnitPromotionClass', 'PROMOTION_CLASS_AIR_BOMBER'),
    ('BBG_ATOMIC_AIRBOMBER_PRODUCTION', 'EraType', 'ERA_ATOMIC'),
    ('BBG_ATOMIC_AIRBOMBER_PRODUCTION', 'Amount', '50'),
    ('BBG_MODERN_AIRFIGHTER_PRODUCTION', 'UnitPromotionClass', 'PROMOTION_CLASS_AIR_FIGHTER'),
    ('BBG_MODERN_AIRFIGHTER_PRODUCTION', 'EraType', 'ERA_MODERN'),
    ('BBG_MODERN_AIRFIGHTER_PRODUCTION', 'Amount', '50');
INSERT INTO PolicyModifiers(PolicyType, ModifierId) VALUES
    ('POLICY_STRATEGIC_AIR_FORCE', 'BBG_ATOMIC_AIRFIGHTER_PRODUCTION'),
    ('POLICY_STRATEGIC_AIR_FORCE', 'BBG_ATOMIC_AIRBOMBER_PRODUCTION'),
    ('POLICY_STRATEGIC_AIR_FORCE', 'BBG_MODERN_AIRFIGHTER_PRODUCTION');


-- 30/03/25 +7 late game card now works on planes
INSERT INTO TypeTags (Type, Tag) VALUES
    ('ABILITY_GLOBAL_COALITION_FRIENDLY_TERRITORY', 'CLASS_AIR_FIGHTER'),
    ('ABILITY_GLOBAL_COALITION_FRIENDLY_TERRITORY', 'CLASS_AIR_BOMBER');

-- 15/05/26 POLICY_REVELATION never obsolete and never disabled (+2 prophet points for anacoana)
DELETE FROM ObsoletePolicies  WHERE PolicyType='POLICY_REVELATION';


-- 14/07/26 legacy cards only available when in a higher tier government
-- 26/08/26 revert
-- INSERT INTO Policy_GovernmentExclusives_XP2 (PolicyType, GovernmentType)
-- SELECT g1.PolicyToUnlock, g2.GovernmentType
-- FROM Governments g1
-- JOIN Governments g2
--     ON (
--         CASE g2.Tier
--             WHEN 'Tier1' THEN 1
--             WHEN 'Tier2' THEN 2
--             WHEN 'Tier3' THEN 3
--             WHEN 'Tier4' THEN 4
--         END
--         >=
--         CASE g1.Tier
--             WHEN 'Tier1' THEN 1
--             WHEN 'Tier2' THEN 2
--             WHEN 'Tier3' THEN 3
--             WHEN 'Tier4' THEN 4
--         END + 1
--     )
-- WHERE g1.PolicyToUnlock IS NOT NULL;
