-- 16/04/23 Change Elizabeth bonus trade routes from first admiral to one for Shipbuilding, Exploration and Mercantilism

DELETE FROM TraitModifiers WHERE ModifierId='ELIZABETH_TRADE_ROUTES_MODIFIER';
INSERT INTO Modifiers (ModifierId, ModifierType, OwnerRequirementSetId) VALUES
	('BBG_ELIZABETH_TRADEROUTE_SHIPBUILDING', 'MODIFIER_PLAYER_ADJUST_TRADE_ROUTE_CAPACITY', 'BBG_UTILS_PLAYER_HAS_TECH_SHIPBUILDING'),
	('BBG_ELIZABETH_TRADEROUTE_EXPLORATION', 'MODIFIER_PLAYER_ADJUST_TRADE_ROUTE_CAPACITY', 'BBG_PLAYER_HAS_CIVIC_EXPLORATION_REQSET'),
	('BBG_ELIZABETH_TRADEROUTE_MERCANTILISM', 'MODIFIER_PLAYER_ADJUST_TRADE_ROUTE_CAPACITY', 'BBG_PLAYER_HAS_CIVIC_MERCANTILISM_REQSET');
INSERT INTO ModifierArguments (ModifierId, Name, Value) VALUES
	('BBG_ELIZABETH_TRADEROUTE_SHIPBUILDING', 'Amount', '1'),
	('BBG_ELIZABETH_TRADEROUTE_EXPLORATION', 'Amount', '1'),
	('BBG_ELIZABETH_TRADEROUTE_MERCANTILISM', 'Amount', '1');
INSERT INTO TraitModifiers (TraitType, ModifierId) VALUES
	('TRAIT_LEADER_ELIZABETH', 'BBG_ELIZABETH_TRADEROUTE_SHIPBUILDING'),
	('TRAIT_LEADER_ELIZABETH', 'BBG_ELIZABETH_TRADEROUTE_EXPLORATION'),
	('TRAIT_LEADER_ELIZABETH', 'BBG_ELIZABETH_TRADEROUTE_MERCANTILISM');