INSERT INTO Modifiers(ModifierId, ModifierType) VALUES
	('BBG_MODIFIER_BOOST_INDUSTRIAL_ZONE_PRODUCTION', 'MODIFIER_PLAYER_CITIES_ADJUST_DISTRICT_PRODUCTION');

INSERT INTO ModifierArguments(ModifierId, Name, Value) VALUES
	('BBG_MODIFIER_BOOST_INDUSTRIAL_ZONE_PRODUCTION','DistrictType','DISTRICT_INDUSTRIAL_ZONE'),
	('BBG_MODIFIER_BOOST_INDUSTRIAL_ZONE_PRODUCTION','Amount','100');

INSERT INTO TraitModifiers(TraitType, ModifierId) VALUES
	('TRAIT_LEADER_LINCOLN', 'BBG_MODIFIER_BOOST_INDUSTRIAL_ZONE_PRODUCTION');

UPDATE ModifierStrings SET Text='LOC_ABILITY_LINCOLN_MELEE_UNITS_COMBAT_DESCRIPTION' WHERE ModifierId='LINCOLN_MELEE_BUFF';

-- 16/04/23 +100% toward aqueducs
INSERT INTO TraitModifiers (TraitType, ModifierId) VALUES
	('TRAIT_LEADER_LINCOLN', 'BBG_LINCOLN_AQUEDUCT_BONUS_PRODUCTION');
INSERT INTO Modifiers (ModifierId, ModifierType) VALUES
	('BBG_LINCOLN_AQUEDUCT_BONUS_PRODUCTION', 'MODIFIER_PLAYER_CITIES_ADJUST_DISTRICT_PRODUCTION');
INSERT INTO ModifierArguments (ModifierId, Name, Value) VALUES
	('BBG_LINCOLN_AQUEDUCT_BONUS_PRODUCTION', 'DistrictType', 'DISTRICT_AQUEDUCT'),
	('BBG_LINCOLN_AQUEDUCT_BONUS_PRODUCTION', 'Amount', '100');

-- Base unit discount
-- 14/10/23 removed
-- INSERT INTO Modifiers (ModifierId, ModifierType) VALUES
--     ('BBG_LINCOLN_UNITMAINTENANCEDISCOUNT', 'MODIFIER_PLAYER_ADJUST_UNIT_MAINTENANCE_DISCOUNT');
-- INSERT INTO ModifierArguments (ModifierId, Name, Value) VALUES
--     ('BBG_LINCOLN_UNITMAINTENANCEDISCOUNT', 'Amount', '1');
-- INSERT INTO TraitModifiers (TraitType, ModifierId) VALUES
--     ('TRAIT_LEADER_LINCOLN', 'BBG_LINCOLN_UNITMAINTENANCEDISCOUNT');

-- 19/06/25 Free units no longer get +5
DELETE FROM UnitAbilityModifiers WHERE ModifierId='LINCOLN_MELEE_BUFF';

-- 14/07/26 +2 culture for all IZ buildings
INSERT INTO Modifiers(ModifierId, ModifierType) 
	SELECT 'BBG_LINCOLN_INDUSTRIAL_ZONE_CULTURE_' || buildingType, 'MODIFIER_PLAYER_CITIES_ADJUST_BUILDING_YIELD_CHANGE' 
FROM Buildings WHERE PrereqDistrict='DISTRICT_INDUSTRIAL_ZONE';

INSERT INTO ModifierArguments(ModifierId, Name, Value) 
	SELECT 'BBG_LINCOLN_INDUSTRIAL_ZONE_CULTURE_' || buildingType, 'BuildingType', buildingType
	FROM Buildings WHERE PrereqDistrict='DISTRICT_INDUSTRIAL_ZONE';

INSERT INTO ModifierArguments(ModifierId, Name, Value) 
	SELECT 'BBG_LINCOLN_INDUSTRIAL_ZONE_CULTURE_' || buildingType, 'Amount', '2'
	FROM Buildings WHERE PrereqDistrict='DISTRICT_INDUSTRIAL_ZONE';

INSERT INTO ModifierArguments(ModifierId, Name, Value) 
	SELECT 'BBG_LINCOLN_INDUSTRIAL_ZONE_CULTURE_' || buildingType, 'YieldType', 'YIELD_CULTURE'
	FROM Buildings WHERE PrereqDistrict='DISTRICT_INDUSTRIAL_ZONE';

INSERT INTO TraitModifiers(TraitType, ModifierId) 
	SELECT 'TRAIT_LEADER_LINCOLN', 'BBG_LINCOLN_INDUSTRIAL_ZONE_CULTURE_' || buildingType
	FROM Buildings WHERE PrereqDistrict='DISTRICT_INDUSTRIAL_ZONE';

