INSERT INTO Modifiers(ModifierId, ModifierType) VALUES
	('BBG_MODIFIER_BOOST_INDUSTRIAL_ZONE_PRODUCTION', 'MODIFIER_PLAYER_CITIES_ADJUST_DISTRICT_PRODUCTION');

INSERT INTO ModifierArguments(ModifierId, Name, Value) VALUES
	('BBG_MODIFIER_BOOST_INDUSTRIAL_ZONE_PRODUCTION','DistrictType','DISTRICT_INDUSTRIAL_ZONE'),
	('BBG_MODIFIER_BOOST_INDUSTRIAL_ZONE_PRODUCTION','Amount','100');

INSERT INTO TraitModifiers(TraitType, ModifierId) VALUES
	('TRAIT_LEADER_LINCOLN', 'BBG_MODIFIER_BOOST_INDUSTRIAL_ZONE_PRODUCTION');

