-- INSERT INTO TypeTags(Type, Tag) VALUES
-- 	('BBG_ABILITY_SALADIN_UNIT_SUPPORT', 'CLASS_GIANT_DEATH_ROBOT'),
-- 	('BBG_ABILITY_SALADIN_UNIT_SUPPORT', 'CLASS_GURU');

-- 05/03/2024 -1 units maintenance cost
INSERT INTO Modifiers (ModifierId, ModifierType) VALUES
     ('BBG_SULTAN_UNITMAINTENANCEDISCOUNT', 'MODIFIER_PLAYER_ADJUST_UNIT_MAINTENANCE_DISCOUNT');
INSERT INTO ModifierArguments (ModifierId, Name, Value) VALUES
     ('BBG_SULTAN_UNITMAINTENANCEDISCOUNT', 'Amount', '1');
 INSERT INTO TraitModifiers (TraitType, ModifierId) VALUES
     ('TRAIT_LEADER_SALADIN_ALT', 'BBG_SULTAN_UNITMAINTENANCEDISCOUNT');