INSERT INTO Modifiers(ModifierId, ModifierType) VALUES
	('BBG_MODIFIER_BOOST_INDUSTRIAL_ZONE_PRODUCTION', 'MODIFIER_PLAYER_CITIES_ADJUST_DISTRICT_PRODUCTION');

INSERT INTO ModifierArguments(ModifierId, Name, Value) VALUES
	('BBG_MODIFIER_BOOST_INDUSTRIAL_ZONE_PRODUCTION','DistrictType','DISTRICT_INDUSTRIAL_ZONE'),
	('BBG_MODIFIER_BOOST_INDUSTRIAL_ZONE_PRODUCTION','Amount','100');

INSERT INTO TraitModifiers(TraitType, ModifierId) VALUES
	('TRAIT_LEADER_LINCOLN', 'BBG_MODIFIER_BOOST_INDUSTRIAL_ZONE_PRODUCTION');

UPDATE ModifierStrings SET Text='LOC_ABILITY_LINCOLN_MELEE_UNITS_COMBAT_DESCRIPTION' WHERE ModifierId='LINCOLN_MELEE_BUFF';

-- 16/04/23 +100% toward aqueducs
INSERT INTO TraitModifiers (TraitType, ModifierId) VALUES
	('TRAIT_LEADER_LINCOLN', 'BBG_LINCOLN_AQUEDUCT_BONUS_PRODUCTION');
INSERT INTO Modifiers (ModifierId, ModifierType) VALUES
	('BBG_LINCOLN_AQUEDUCT_BONUS_PRODUCTION', 'MODIFIER_PLAYER_CITIES_ADJUST_DISTRICT_PRODUCTION');
INSERT INTO ModifierArguments (ModifierId, Name, Value) VALUES
	('BBG_LINCOLN_AQUEDUCT_BONUS_PRODUCTION', 'DistrictType', 'DISTRICT_AQUEDUCT'),
	('BBG_LINCOLN_AQUEDUCT_BONUS_PRODUCTION', 'Amount', '100');

-- Base unit discount
-- 14/10/23 removed
-- INSERT INTO Modifiers (ModifierId, ModifierType) VALUES
--     ('BBG_LINCOLN_UNITMAINTENANCEDISCOUNT', 'MODIFIER_PLAYER_ADJUST_UNIT_MAINTENANCE_DISCOUNT');
-- INSERT INTO ModifierArguments (ModifierId, Name, Value) VALUES
--     ('BBG_LINCOLN_UNITMAINTENANCEDISCOUNT', 'Amount', '1');
-- INSERT INTO TraitModifiers (TraitType, ModifierId) VALUES
--     ('TRAIT_LEADER_LINCOLN', 'BBG_LINCOLN_UNITMAINTENANCEDISCOUNT');
