--Firaxis coded support and flanking for saladin as one ability
--Splitting them
INSERT INTO Types(Type, Kind) VALUES
	('BBG_ABILITY_SALADIN_UNIT_SUPPORT', 'KIND_ABILITY');
INSERT INTO UnitAbilities(UnitAbilityType, Name, Description, Inactive) VALUES
	('BBG_ABILITY_SALADIN_UNIT_SUPPORT', 'LOC_BBG_ABILITY_SALADIN_UNIT_SUPPORT_NAME', 'LOC_BBG_ABILITY_SALADIN_UNIT_SUPPORT_DESCRIPTION','1');
INSERT INTO UnitAbilityModifiers(UnitAbilityType, ModifierId) VALUES
	('BBG_ABILITY_SALADIN_UNIT_SUPPORT','SALADIN_SUPPORT_BONUS_UNITS');
DELETE FROM UnitAbilityModifiers WHERE UnitAbilityType='ABILITY_SALADIN_FLANKING_UNITS' AND ModifierId = 'SALADIN_SUPPORT_BONUS_UNITS';

INSERT INTO Modifiers(ModifierId, ModifierType) VALUES
	('SALADIN_ALT_SUPPORT_ABILITY','MODIFIER_PLAYER_UNITS_GRANT_ABILITY');
INSERT INTO ModifierArguments(ModifierId, Name, Value) VALUES
	('SALADIN_ALT_SUPPORT_ABILITY', 'AbilityType', 'BBG_ABILITY_SALADIN_SUPPORT_UNITS');
INSERT INTO TraitModifiers(TraitType, ModifierId) VALUES
	('TRAIT_LEADER_SALADIN_ALT', 'SALADIN_ALT_SUPPORT_ABILITY');
--adding appropriate tags
INSERT INTO TypeTags(Type, Tag) VALUES
	('BBG_ABILITY_SALADIN_UNIT_SUPPORT', 'CLASS_MELEE'),
	('BBG_ABILITY_SALADIN_UNIT_SUPPORT', 'CLASS_ANTI_CAVALRY'),
	('BBG_ABILITY_SALADIN_UNIT_SUPPORT', 'CLASS_RECON'),
	('BBG_ABILITY_SALADIN_UNIT_SUPPORT', 'CLASS_HEAVY_CAVALRY'),
	('BBG_ABILITY_SALADIN_UNIT_SUPPORT', 'CLASS_LIGHT_CAVALRY'),
	('BBG_ABILITY_SALADIN_UNIT_SUPPORT', 'CLASS_NAVAL_MELEE'),
	('BBG_ABILITY_SALADIN_UNIT_SUPPORT', 'CLASS_WARRIOR_MONK'),
	('BBG_ABILITY_SALADIN_UNIT_SUPPORT', 'CLASS_GIANT_DEATH_ROBOT'),
	('BBG_ABILITY_SALADIN_UNIT_SUPPORT', 'CLASS_NAVAL_CARRIER');