--5.6. Disable:
--building reqs (reqs are dynamically controlled via Lua)
/*
INSERT INTO Requirements(RequirementId, RequirementType) VALUES
	('DISTRICT_IS_INCOMPLETE_WONDER_REQ_BBG','REQUIREMENT_PLOT_PROPERTY_MATCHES');
INSERT INTO RequirementArguments(RequirementId, Name, Value) VALUES
	('DISTRICT_IS_INCOMPLETE_WONDER_REQ_BBG', 'PropertyName', 'DISTRICT_INCOMPLETE_WONDER'),
	('DISTRICT_IS_INCOMPLETE_WONDER_REQ_BBG', 'PropertyMinimum', '1');
INSERT INTO RequirementSets(RequirementSetId, RequirementSetType) VALUES
	('DISTRICT_IS_INCOMPLETE_WONDER_REQSET_BBG', 'REQUIREMENTSET_TEST_ALL');
INSERT INTO RequirementSetRequirements(RequirementSetId, RequirementId) VALUES
	('DISTRICT_IS_INCOMPLETE_WONDER_REQSET_BBG', 'DISTRICT_IS_INCOMPLETE_WONDER_REQ_BBG');
INSERT INTO Modifiers(ModifierId, ModifierType, SubjectRequirementSetId) VALUES
	('MODIFIER_LUDWIG_REMOVE_INCOMPLETE_WONDER_ADJ_BBG','MODIFIER_PLAYER_DISTRICTS_ADJUST_YIELD_MODIFIER', 'DISTRICT_IS_INCOMPLETE_WONDER_REQSET_BBG');
INSERT INTO ModifierArguments(ModifierId, Name, Value) VALUES
	('MODIFIER_LUDWIG_REMOVE_INCOMPLETE_WONDER_ADJ_BBG', 'YieldType', 'YIELD_CULTURE'),
	('MODIFIER_LUDWIG_REMOVE_INCOMPLETE_WONDER_ADJ_BBG', 'Amount', '-100');
INSERT INTO TraitModifiers(TraitType, ModifierId) VALUES
	('TRAIT_LEADER_LUDWIG', 'MODIFIER_LUDWIG_REMOVE_INCOMPLETE_WONDER_ADJ_BBG');
*/
--5.6: 1 cult on incomplete wonders
UPDATE ModifierArguments SET Value = '1' WHERE ModifierId = 'LUDWIG_WONDER_ADJACENCY' AND Name = 'Amount';

-- 19/12/23 +1 culture at philo po
-- 27/03/24 nerf to +1 culture at drama and poetry
-- 26/02/25 removed
-- INSERT INTO Modifiers (ModifierId, ModifierType, OwnerRequirementSetId) VALUES
-- 	('BBG_LUDWIG_WONDER_ADJACENCY_DRAMA_POETRY', 'MODIFIER_PLAYER_CITIES_DISTRICT_ADJACENCY', 'BBG_UTILS_PLAYER_HAS_CIVIC_DRAMA_POETRY_REQSET');
-- INSERT INTO ModifierArguments (ModifierId, Name, Value) VALUES
-- 	('BBG_LUDWIG_WONDER_ADJACENCY_DRAMA_POETRY', 'DistrictType', 'DISTRICT_WONDER'),
-- 	('BBG_LUDWIG_WONDER_ADJACENCY_DRAMA_POETRY', 'YieldType', 'YIELD_CULTURE'),
-- 	('BBG_LUDWIG_WONDER_ADJACENCY_DRAMA_POETRY', 'Amount', 1),
-- 	('BBG_LUDWIG_WONDER_ADJACENCY_DRAMA_POETRY', 'Description', 'LOC_DISTRICT_DISTRICT_1_CULTURE');
-- INSERT INTO TraitModifiers (TraitType, ModifierId) VALUES
-- 	('TRAIT_LEADER_LUDWIG', 'BBG_LUDWIG_WONDER_ADJACENCY_DRAMA_POETRY');

-- Trying to do +2 and removing the original +1 doesnt work
-- INSERT INTO Requirements (RequirementId, RequirementType, Inverse) VALUES
-- 	('BBG_UTILS_PLAYER_DOESNT_HAVE_CIVIC_POLITICAL_PHILOSOPHY_REQUIREMENT', 'REQUIREMENT_PLAYER_HAS_CIVIC', 1);
-- INSERT INTO RequirementArguments (RequirementId, Name, Value) VALUES
-- 	('BBG_UTILS_PLAYER_DOESNT_HAVE_CIVIC_POLITICAL_PHILOSOPHY_REQUIREMENT', 'CivicType', 'CIVIC_POLITICAL_PHILOSOPHY');
-- INSERT INTO RequirementSets (RequirementSetId, RequirementSetType) VALUES
-- 	('BBG_UTILS_PLAYER_DOESNT_HAVE_CIVIC_POLITICAL_PHILOSOPHY_REQSET', 'REQUIREMENTSET_TEST_ALL');
-- INSERT INTO RequirementSetRequirements (RequirementSetId, RequirementId) VALUES
-- 	('BBG_UTILS_PLAYER_DOESNT_HAVE_CIVIC_POLITICAL_PHILOSOPHY_REQSET', 'BBG_UTILS_PLAYER_DOESNT_HAVE_CIVIC_POLITICAL_PHILOSOPHY_REQUIREMENT');
-- UPDATE Modifiers SET OwnerRequirementSetId='BBG_UTILS_PLAYER_DOESNT_HAVE_CIVIC_POLITICAL_PHILOSOPHY_REQSET' WHERE ModifierId='LUDWIG_WONDER_ADJACENCY';