UPDATE ModifierArguments SET Value = '10, 10' WHERE ModifierId = 'TRAIT_SULEIMAN_ALT_SCIENCE_CULTURE_GOLDEN_AGE' AND Name = 'Amount';

INSERT INTO Modifiers (ModifierId, ModifierType, SubjectRequirementSetId) VALUES
    ('BBG_SULEIMAN_ALT_COMBAT_ABILITY', 'MODIFIER_PLAYER_UNITS_GRANT_ABILITY', 'PLAYER_NO_GOLDEN_AGE_REQUIREMENTS'),
    ('BBG_SULEIMAN_COMBAT_BUFF', 'MODIFIER_UNIT_ADJUST_COMBAT_STRENGTH', 'OPPONENT_IS_IN_GOLDEN_AGE_REQUIREMENTS');
INSERT INTO ModifierArguments (ModifierId, Name, Value) VALUES
    ('BBG_SULEIMAN_ALT_COMBAT_ABILITY', 'AbilityType', 'BBG_ABILITY_SULEIMAN_ALT_COMBAT'),
    ('BBG_SULEIMAN_COMBAT_BUFF', 'Amount', 2);
INSERT INTO UnitAbilities (UnitAbilityType, Name, Description, Inactive) VALUES
    ('BBG_ABILITY_SULEIMAN_ALT_COMBAT', 'LOC_BBG_ABILITY_SULEIMAN_ALT_COMBAT_NAME', 'LOC_BBG_ABILITY_SULEIMAN_ALT_COMBAT_DESC', 1);
INSERT INTO UnitAbilityModifiers (UnitAbilityType, ModifierId) VALUES
    ('BBG_ABILITY_SULEIMAN_ALT_COMBAT', 'BBG_SULEIMAN_COMBAT_BUFF');
INSERT INTO TypeTags (Type, Tag) VALUES
    ('BBG_ABILITY_SULEIMAN_ALT_COMBAT', 'CLASS_ALL_COMBAT_UNITS');
INSERT INTO Types (Type, Kind) VALUES
    ('BBG_ABILITY_SULEIMAN_ALT_COMBAT', 'KIND_ABILITY');
INSERT INTO ModifierStrings(ModifierId, Context, Text) VALUES
    ('BBG_SULEIMAN_COMBAT_BUFF', 'Preview', 'LOC_BBG_ABILITY_SULEIMAN_ALT_COMBAT_PREVIEW');
INSERT INTO TraitModifiers (TraitType, ModifierId) VALUES
    ('TRAIT_LEADER_SULEIMAN_ALT', 'BBG_SULEIMAN_ALT_COMBAT_ABILITY');