/*
--Seige Ignore Obstacles--
INSERT INTO RequirementSets(RequirementSetId, RequirementSetType) VALUES
	('BBG_PROMOTION_CLASS_SIEGE_REQSET', 'REQUIREMENTSET_TEST_ALL');
INSERT INTO RequirementSetRequirements(RequirementSetId, RequirementId) VALUES
	('BBG_PROMOTION_CLASS_SIEGE_REQSET', 'REQUIREMENT_UNIT_IS_SIEGE');

INSERT INTO Modifiers(ModifierId, ModifierType, SubjectRequirementSetId) VALUES
	('BBG_CAESAR_SIEGE_IGNORE_FEATURES', 'MODIFIER_PLAYER_UNITS_ATTACH_MODIFIER', 'BBG_PROMOTION_CLASS_SIEGE_REQSET'),
	('BBG_CAESAR_SIEGE_IGNORE_FEATURES_MODIFIER', 'MODIFIER_PLAYER_UNIT_ADJUST_SEE_THROUGH_FEATURES', NULL),
	('BBG_CAESAR_SIEGE_IGNORE_TERRAIN', 'MODIFIER_PLAYER_UNITS_ATTACH_MODIFIER', 'BBG_PROMOTION_CLASS_SIEGE_REQSET'),
	('BBG_CAESAR_SIEGE_IGNORE_TERRAIN_MODIFIER', 'MODIFIER_PLAYER_UNIT_ADJUST_SEE_THROUGH_TERRAIN', NULL);

INSERT INTO ModifierArguments(ModifierId, Name, Value) VALUES
	('BBG_CAESAR_SIEGE_IGNORE_FEATURES_MODIFIER', 'CanSee', '1'),
	('BBG_CAESAR_SIEGE_IGNORE_FEATURES', 'ModifierId', 'BBG_CAESAR_SIEGE_IGNORE_FEATURES_MODIFIER'),
	('BBG_CAESAR_SIEGE_IGNORE_TERRAIN_MODIFIER', 'CanSee', '1'),
	('BBG_CAESAR_SIEGE_IGNORE_TERRAIN', 'ModifierId', 'BBG_CAESAR_SIEGE_IGNORE_TERRAIN_MODIFIER');

INSERT INTO TraitModifiers(TraitType, ModifierId) VALUES
	('TRAIT_LEADER_CAESAR', 'BBG_CAESAR_SIEGE_IGNORE_FEATURES'),
	('TRAIT_LEADER_CAESAR', 'BBG_CAESAR_SIEGE_IGNORE_TERRAIN');
*/