-- 15/06/23 Nader Shah combat bonus to +7 (from +5)
-- 12/07/23 en fait non
UPDATE ModifierArguments SET Value=5 WHERE ModifierId='NADER_SHAH_COMBAT_BUFF';
DELETE FROM RequirementSetRequirements WHERE RequirementId='COMBAT_IS_NOT_DISTRICT_WARLORDS';


--14/04/23 rework trade route, gives science now instead of culture
-- Remove old bonus
DELETE FROM TraitModifiers WHERE ModifierId='NADER_SHAH_TRADE_GOLD';
DELETE FROM TraitModifiers WHERE ModifierId='NADER_SHAH_TRADE_FAITH';
--internal trades routes scale on science
INSERT INTO Modifiers (ModifierId, ModifierType, SubjectRequirementSetId) VALUES
    ('TRAIT_NADER_INTERNAL_TRADE_SCIENCE_BASE', 'MODIFIER_PLAYER_ADJUST_TRADE_ROUTE_YIELD_FOR_DOMESTIC', NULL),
    ('TRAIT_NADER_INTERNAL_TRADE_SCIENCE_AT_EDUCATION', 'MODIFIER_PLAYER_ADJUST_TRADE_ROUTE_YIELD_FOR_DOMESTIC', 'BBG_UTILS_PLAYER_HAS_TECH_EDUCATION'),
    ('TRAIT_NADER_INTERNAL_TRADE_SCIENCE_AT_SCIENTIFIC_THEORY', 'MODIFIER_PLAYER_ADJUST_TRADE_ROUTE_YIELD_FOR_DOMESTIC', 'BBG_UTILS_PLAYER_HAS_TECH_SCIENTIFIC_THEORY');
INSERT INTO ModifierArguments (ModifierId, Name, Value) VALUES
    ('TRAIT_NADER_INTERNAL_TRADE_SCIENCE_BASE', 'YieldType', 'YIELD_SCIENCE'),
    ('TRAIT_NADER_INTERNAL_TRADE_SCIENCE_BASE', 'Amount', '1'),
    ('TRAIT_NADER_INTERNAL_TRADE_SCIENCE_AT_EDUCATION', 'YieldType', 'YIELD_SCIENCE'),
    ('TRAIT_NADER_INTERNAL_TRADE_SCIENCE_AT_EDUCATION', 'Amount', '2'),
    ('TRAIT_NADER_INTERNAL_TRADE_SCIENCE_AT_SCIENTIFIC_THEORY', 'YieldType', 'YIELD_SCIENCE'),
    ('TRAIT_NADER_INTERNAL_TRADE_SCIENCE_AT_SCIENTIFIC_THEORY', 'Amount', '2');
INSERT INTO TraitModifiers (TraitType, ModifierId) VALUES
    ('TRAIT_LEADER_NADER_SHAH', 'TRAIT_NADER_INTERNAL_TRADE_SCIENCE_BASE'),
    ('TRAIT_LEADER_NADER_SHAH', 'TRAIT_NADER_INTERNAL_TRADE_SCIENCE_AT_EDUCATION'),
    ('TRAIT_LEADER_NADER_SHAH', 'TRAIT_NADER_INTERNAL_TRADE_SCIENCE_AT_SCIENTIFIC_THEORY');