--16/04/23 Cleopatra get bonus only on improved tiles
INSERT OR IGNORE INTO Requirements (RequirementId, RequirementType) VALUES
	('BBG_TILE_HAS_ANY_IMPROVEMENT', 'REQUIREMENT_PLOT_HAS_ANY_IMPROVEMENT');
INSERT INTO RequirementSets (RequirementSetId, RequirementSetType) VALUES
	('BBG_TILE_HAS_ANY_IMPROVEMENT_ON_FLOODPLAIN_RESSOURCES_REQSET', 'REQUIREMENTSET_TEST_ALL');
INSERT INTO RequirementSetRequirements (RequirementSetId, RequirementId) VALUES
	('BBG_TILE_HAS_ANY_IMPROVEMENT_ON_FLOODPLAIN_RESSOURCES_REQSET', 'BBG_TILE_HAS_ANY_IMPROVEMENT'),
	('BBG_TILE_HAS_ANY_IMPROVEMENT_ON_FLOODPLAIN_RESSOURCES_REQSET', 'REQUIRES_PLOT_HAS_VISIBLE_RESOURCE'),
	('BBG_TILE_HAS_ANY_IMPROVEMENT_ON_FLOODPLAIN_RESSOURCES_REQSET', 'REQUIRES_FLOODPLAINS_REQUIREMENT');

UPDATE Modifiers SET SubjectRequirementSetId='BBG_TILE_HAS_ANY_IMPROVEMENT_ON_FLOODPLAIN_RESSOURCES_REQSET' WHERE ModifierId='CLEOPATRA_FLOODPLAINS_RESOURCE_YIELD';