
--21/06/23 Varangian gets 50% toward holy site building
INSERT INTO Modifiers (ModifierId, ModifierType) VALUES
    ('BBG_VARANGIAN_HOLY_SITE_BONUS_PRODUCTION_BUILDING', 'MODIFIER_PLAYER_CITIES_ADJUST_BUILDING_PRODUCTION');
INSERT INTO ModifierArguments (ModifierId, Name, Value) VALUES
    ('BBG_VARANGIAN_HOLY_SITE_BONUS_PRODUCTION_BUILDING', 'DistrictType', 'DISTRICT_HOLY_SITE');
INSERT INTO ModifierArguments (ModifierId, Name, Value) VALUES
    ('BBG_VARANGIAN_HOLY_SITE_BONUS_PRODUCTION_BUILDING', 'Amount', '50');
INSERT INTO TraitModifiers (TraitType, ModifierId) VALUES
	('TRAIT_LEADER_HARALD_ALT', 'BBG_VARANGIAN_HOLY_SITE_BONUS_PRODUCTION_BUILDING');
