INSERT INTO Colors (Type, Color) VALUES
    ('COLOR_STANDARD_BBG_GREEN_LT', "0,204,102,255"),
    ('COLOR_STANDARD_BBG_BLACK_DK', "0,0,0,255"),
    ('COLOR_STANDARD_BBG_BLUE_MD', "0,0,204,255"),
    ('COLOR_STANDARD_BBG_BLUE_LT', "153,204,255,255"),
    ('COLOR_STANDARD_BBG_GREY_DK', "60,60,60,255"),
    ('COLOR_STANDARD_BBG_AQBLUE_DK', "0,204,204,255"),
    ('COLOR_STANDARD_BBG_PINK_MD', "204,0,102,255"),
    ('COLOR_STANDARD_BBG_GREY_MD', "96,96,96,255"),
    ('COLOR_STANDARD_BBG_GREEN_MD', "0,102,102,255"),
    ('COLOR_STANDARD_BBG_WHITE_LT', "224,224,224,255"),
    ('COLOR_STANDARD_BBG_GOLD_DK', "255,185,15,255"),
    ('COLOR_STANDARD_BBG_KBLUE_DK', "0,70,240,255"),
    ('COLOR_STANDARD_BBG_PINK_DK', "153,0,76,255"); 


-- Al Hasan 
-- So it doesn't clash with Cree
UPDATE PlayerColors SET Alt3PrimaryColor='COLOR_STANDARD_BBG_GREEN_MD' WHERE Type='LEADER_SUK_AL_HASAN';

-- Amanitore Nubia
UPDATE PlayerColors SET Alt1PrimaryColor='COLOR_STANDARD_BBG_PINK_DK', Alt1SecondaryColor='COLOR_STANDARD_BBG_GOLD_DK' WHERE Type='LEADER_AMANITORE';
UPDATE PlayerColors SET Alt3PrimaryColor='COLOR_STANDARD_BBG_GOLD_DK', Alt3SecondaryColor='COLOR_STANDARD_BBG_KBLUE_DK' WHERE Type='LEADER_AMANITORE';

-- Ba Trieu
UPDATE PlayerColors SET Alt1PrimaryColor='COLOR_STANDARD_BBG_GREEN_LT', Alt1SecondaryColor='COLOR_STANDARD_BBG_BLACK_DK' WHERE Type='LEADER_LADY_TRIEU';

-- Chandragupta
UPDATE PlayerColors SET Alt3PrimaryColor='COLOR_STANDARD_BBG_GREY_DK', Alt3SecondaryColor='COLOR_STANDARD_BBG_AQBLUE_DK' WHERE Type='LEADER_CHANDRAGUPTA';

-- Gorgo
UPDATE PlayerColors SET Alt2PrimaryColor='COLOR_STANDARD_BBG_PINK_DK', Alt2SecondaryColor='COLOR_STANDARD_BBG_BLACK_DK' WHERE Type='LEADER_GORGO';

-- Lautaro
-- UPDATE PlayerColors SET Alt2PrimaryColor='COLOR_STANDARD_BBG_GOLD_DK', Alt2SecondaryColor='COLOR_STANDARD_BBG_PINK_DK' WHERE Type='LEADER_LAUTARO';

-- Poundmaker
UPDATE PlayerColors SET Alt3PrimaryColor='COLOR_STANDARD_BBG_GREEN_MD', Alt3SecondaryColor='COLOR_STANDARD_BBG_WHITE_LT' WHERE Type='LEADER_POUNDMAKER';

-- Vercingetorix
UPDATE PlayerColors SET Alt1PrimaryColor='COLOR_STANDARD_ORANGE_MD', Alt1SecondaryColor='COLOR_STANDARD_GREEN_DK' WHERE Type='LEADER_SUK_VERCINGETORIX_DLC';
UPDATE PlayerColors SET Alt1PrimaryColor='COLOR_STANDARD_ORANGE_MD', Alt1SecondaryColor='COLOR_STANDARD_GREEN_DK' WHERE Type='LEADER_SUK_VERCINGETORIX';

-- Wilfier Laurier
UPDATE PlayerColors SET Alt2PrimaryColor='COLOR_STANDARD_BBG_BLUE_MD', Alt2SecondaryColor='COLOR_STANDARD_BBG_BLUE_LT' WHERE Type='LEADER_LAURIER';

-- Wilhelmine
UPDATE PlayerColors SET Alt2PrimaryColor='COLOR_STANDARD_BBG_GREY_DK', Alt2SecondaryColor='COLOR_STANDARD_ORANGE_MD' WHERE Type='LEADER_WILHELMINA';