-- Reduce Imhotep to 1 charge
UPDATE GreatPersonIndividuals SET ActionCharges=1 WHERE GreatPersonIndividualType='GREAT_PERSON_INDIVIDUAL_IMHOTEP';

-- Fix Ibn Khaldun Bug
UPDATE ModifierArguments SET Value=4 WHERE Name='Amount' AND ModifierId IN
    ('GREAT_PERSON_INDIVIDUAL_IBN_KHALDUN_EMPIRE_HAPPY_SCIENCE', 'GREAT_PERSON_INDIVIDUAL_IBN_KHALDUN_EMPIRE_HAPPY_CULTURE', 'GREAT_PERSON_INDIVIDUAL_IBN_KHALDUN_EMPIRE_HAPPY_PRODUCTION',
    'GREAT_PERSON_INDIVIDUAL_IBN_KHALDUN_EMPIRE_HAPPY_GOLD', 'GREAT_PERSON_INDIVIDUAL_IBN_KHALDUN_EMPIRE_HAPPY_FAITH');
UPDATE ModifierArguments SET Value=8 WHERE Name='Amount' AND ModifierId IN
    ('GREAT_PERSON_INDIVIDUAL_IBN_KHALDUN_EMPIRE_ECSTATIC_SCIENCE', 'GREAT_PERSON_INDIVIDUAL_IBN_KHALDUN_EMPIRE_ECSTATIC_CULTURE', 'GREAT_PERSON_INDIVIDUAL_IBN_KHALDUN_EMPIRE_ECSTATIC_PRODUCTION',
    'GREAT_PERSON_INDIVIDUAL_IBN_KHALDUN_EMPIRE_ECSTATIC_GOLD', 'GREAT_PERSON_INDIVIDUAL_IBN_KHALDUN_EMPIRE_ECSTATIC_FAITH');

-- Alfred Nobel grants one diplo point
INSERT INTO Modifiers (ModifierId, ModifierType) VALUES
    ('BBG_GREATPERSON_1DIPLOPOINT', 'MODIFIER_PLAYER_ADJUST_DIPLOMATIC_VICTORY_POINTS');
INSERT INTO ModifierArguments (ModifierId, Name, Value) VALUES
    ('BBG_GREATPERSON_1DIPLOPOINT', 'Amount', '1');
INSERT INTO GreatPersonIndividualActionModifiers (GreatPersonIndividualType, ModifierId, AttachmentTargetType) VALUES
    ('GREAT_PERSON_INDIVIDUAL_ALFRED_NOBEL', 'BBG_GREATPERSON_1DIPLOPOINT', 'GREAT_PERSON_ACTION_ATTACHMENT_TARGET_PLAYER');


---- GREAT MERCHANTS
-- John Spilsbury
UPDATE ModifierArguments SET Value='2' WHERE ModifierId='GREATPERSON_GRANT_TOYS' AND Name='Amount';

-- Jamsetji Tata
UPDATE ModifierArguments SET Value='50' WHERE ModifierId='GREATPERSON_CAMPUS_TOURISM' AND Name='Amount';

-- Masary Ibuka
UPDATE ModifierArguments SET Value='50' WHERE ModifierId='GREATPERSON_INDUSTRIAL_ZONE_TOURISM' AND Name='Amount';

-- Raja Toda Mal
UPDATE ModifierArguments SET Value='1.0' WHERE ModifierId='GREATPERSON_DOMESTIC_ROUTE_GOLD_PER_SPECIALTY_DISTRICT' AND Name='Amount';

-- Stamford Raffles
UPDATE GreatPersonIndividuals SET ActionRequiresCityStateTerritory=1, ActionRequiresSuzerainTerritory=0 WHERE GreatPersonIndividualType='GREAT_PERSON_INDIVIDUAL_STAMFORD_RAFFLES';

-- Sarah Breedlove
INSERT INTO GreatPersonIndividualActionModifiers (GreatPersonIndividualType, ModifierId, AttachmentTargetType) VALUES
    ('GREAT_PERSON_INDIVIDUAL_SARAH_BREEDLOVE', 'GREATPERSON_EXTRA_TRADE_ROUTE_CAPACITY', 'GREAT_PERSON_ACTION_ATTACHMENT_TARGET_DISTRICT_IN_TILE');

    