-- by: iElden

-- 15/07/2022: Reverted
-- INSERT INTO Modifiers(ModifierId, ModifierType) VALUES
--     ('BBG_APPLY_TRADE_TREATY_DOMESTIC_TRADE_ROUTE_DISABLED', 'MODIFIER_CONGRESS_ATTACH_MODIFIER_TO_PLAYERTYPE'),
--     ('BBB_APPLY_TRADE_TREATY_DOMESTIC_TRADE_ROUTE_GOLD', 'MODIFIER_CONGRESS_ATTACH_MODIFIER_TO_PLAYERTYPE'),
--     ('BBG_TRADE_TREATY_DOMESTIC_TRADE_ROUTE_DISABLED', 'MODIFIER_PLAYER_TRADE_ROUTES_DISABLE'),
--     ('BBG_TRADE_TREATY_DOMESTIC_TRADE_ROUTE_GOLD', 'MODIFIER_PLAYER_ADJUST_TRADE_ROUTE_YIELD_FOR_DOMESTIC');

-- INSERT INTO ModifierArguments(ModifierId, Name, Value) VALUES
--     ('BBG_APPLY_TRADE_TREATY_DOMESTIC_TRADE_ROUTE_DISABLED', 'ModifierId', 'BBG_TRADE_TREATY_DOMESTIC_TRADE_ROUTE_DISABLED'),
--     ('BBB_APPLY_TRADE_TREATY_DOMESTIC_TRADE_ROUTE_GOLD', 'ModifierId', 'BBG_TRADE_TREATY_DOMESTIC_TRADE_ROUTE_GOLD'),
--     ('BBG_TRADE_TREATY_DOMESTIC_TRADE_ROUTE_DISABLED', 'InternationalMinors', '0'),
--     ('BBG_TRADE_TREATY_DOMESTIC_TRADE_ROUTE_DISABLED', 'InternationalMajors', '0'),
--     ('BBG_TRADE_TREATY_DOMESTIC_TRADE_ROUTE_DISABLED', 'Domestic', '1'),
--     ('BBG_TRADE_TREATY_DOMESTIC_TRADE_ROUTE_GOLD', 'YieldType', 'YIELD_GOLD'),
--     ('BBG_TRADE_TREATY_DOMESTIC_TRADE_ROUTE_GOLD', 'Amount', '4'),
--     ('BBG_TRADE_TREATY_DOMESTIC_TRADE_ROUTE_GOLD', 'Intercontinental', '0');

-- INSERT INTO ResolutionEffects(ResolutionEffectId, ResolutionType, WhichEffect, ModifierId) VALUES
--     -- (23, 'WC_RES_TRADE_TREATY', 1, 'BBG_APPLY_TRADE_TREATY_DOMESTIC_TRADE_ROUTE_DISABLED'),
--     (28, 'WC_RES_TRADE_TREATY', 2, 'BBG_APPLY_DECREASES_TRADE_TO_GOLD_TO_PLAYER');

-- 15/07/2022: B now reduces golds for traders form/to target by 4 (possible negative)

INSERT INTO Modifiers (ModifierId, ModifierType) VALUES
	('BBG_DECREASES_INTERNATIONAL_TRADE_ROUTE_GOLD_TO_PLAYERS', 'MODIFIER_PLAYER_ADJUST_TRADE_ROUTE_YIELD_FOR_INTERNATIONAL'),
	('BBG_DECREASES_INTERNATIONAL_TRADE_ROUTE_GOLD_FROM_PLAYERS', 'MODIFIER_PLAYER_CITIES_ADJUST_TRADE_ROUTE_YIELD_TO_OTHERS');

INSERT INTO Modifiers(ModifierId, ModifierType) VALUES
    ('BBG_APPLY_DECREASES_TRADE_TO_GOLD_TO_PLAYER', 'MODIFIER_CONGRESS_ATTACH_MODIFIER_TO_PLAYERTYPE'),
    ('BBG_APPLY_DECREASES_TRADE_TO_GOLD_FROM_PLAYER', 'MODIFIER_CONGRESS_ATTACH_MODIFIER_TO_PLAYERTYPE');

INSERT INTO ModifierArguments(ModifierId, Name, Value) VALUES
	('BBG_DECREASES_INTERNATIONAL_TRADE_ROUTE_GOLD_TO_PLAYERS', 'YieldType', 'YIELD_GOLD'),
    ('BBG_DECREASES_INTERNATIONAL_TRADE_ROUTE_GOLD_TO_PLAYERS', 'Amount', -4),
    ('BBG_APPLY_DECREASES_TRADE_TO_GOLD_TO_PLAYER', 'ModifierId', 'BBG_DECREASES_INTERNATIONAL_TRADE_ROUTE_GOLD_TO_PLAYERS');

INSERT INTO ModifierArguments(ModifierId, Name, Value) VALUES
    ('BBG_DECREASES_INTERNATIONAL_TRADE_ROUTE_GOLD_FROM_PLAYERS', 'YieldType', 'YIELD_GOLD'),
    ('BBG_DECREASES_INTERNATIONAL_TRADE_ROUTE_GOLD_FROM_PLAYERS', 'Amount', -4),
    ('BBG_APPLY_DECREASES_TRADE_TO_GOLD_FROM_PLAYER', 'ModifierId', 'BBG_DECREASES_INTERNATIONAL_TRADE_ROUTE_GOLD_FROM_PLAYERS');
	
INSERT INTO ResolutionEffects(ResolutionEffectId, ResolutionType, WhichEffect, ModifierId) VALUES
    (26, 'WC_RES_TRADE_TREATY', 2, 'BBG_APPLY_DECREASES_TRADE_TO_GOLD_TO_PLAYER'),
    (27, 'WC_RES_TRADE_TREATY', 2, 'BBG_APPLY_DECREASES_TRADE_TO_GOLD_FROM_PLAYER');

-- UPDATE Modifiers SET RunOnce='True' WHERE ModifierId='APPLY_INTERNATIONAL_MAJOR_TRADE_ROUTES_DISABLED';

DELETE FROM ResolutionEffects WHERE ResolutionEffectId=25;
